// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AppGetHistPower.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from AppGetHistPower.proto</summary>
public static partial class AppGetHistPowerReflection {

  #region Descriptor
  /// <summary>File descriptor for AppGetHistPower.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AppGetHistPowerReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVBcHBHZXRIaXN0UG93ZXIucHJvdG8iYgoVQXBwR2V0SGlzdFBvd2VyUmVz",
          "RFRPEgoKAmNwGAEgASgFEg4KBm9mZnNldBgCIAEoBRIWCg5yZXF1ZXN0ZWRf",
          "dGltZRgDIAEoDRIVCg1yZXF1ZXN0ZWRfZGF5GAQgASgNIrUCChVBcHBHZXRI",
          "aXN0UG93ZXJSZXFEVE8SFQoNc2VyaWFsX251bWJlchgBIAEoAxIKCgJhcBgC",
          "IAEoBRIKCgJjcBgDIAEoBRIOCgZvZmZzZXQYBCABKAUSFAoMcmVxdWVzdF90",
          "aW1lGAUgASgNEhIKCnN0YXJ0X3RpbWUYBiABKA0SFwoPbG9uZ190ZXJtX3N0",
          "YXJ0GAcgASgNEhYKDmFic29sdXRlX3N0YXJ0GAggASgNEhEKCXN0ZXBfdGlt",
          "ZRgJIAEoDRIWCg5yZWxhdGl2ZV9wb3dlchgKIAEoDRIUCgx0b3RhbF9lbmVy",
          "Z3kYCyABKA0SFAoMZGFpbHlfZW5lcmd5GAwgASgNEhMKC3Bvd2VyX2FycmF5",
          "GA0gAygFEhYKDndhcm5pbmdfbnVtYmVyGA4gASgNYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AppGetHistPowerResDTO), global::AppGetHistPowerResDTO.Parser, new[]{ "Cp", "Offset", "RequestedTime", "RequestedDay" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AppGetHistPowerReqDTO), global::AppGetHistPowerReqDTO.Parser, new[]{ "SerialNumber", "Ap", "Cp", "Offset", "RequestTime", "StartTime", "LongTermStart", "AbsoluteStart", "StepTime", "RelativePower", "TotalEnergy", "DailyEnergy", "PowerArray", "WarningNumber" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AppGetHistPowerResDTO : pb::IMessage<AppGetHistPowerResDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AppGetHistPowerResDTO> _parser = new pb::MessageParser<AppGetHistPowerResDTO>(() => new AppGetHistPowerResDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AppGetHistPowerResDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AppGetHistPowerReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistPowerResDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistPowerResDTO(AppGetHistPowerResDTO other) : this() {
    cp_ = other.cp_;
    offset_ = other.offset_;
    requestedTime_ = other.requestedTime_;
    requestedDay_ = other.requestedDay_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistPowerResDTO Clone() {
    return new AppGetHistPowerResDTO(this);
  }

  /// <summary>Field number for the "cp" field.</summary>
  public const int CpFieldNumber = 1;
  private int cp_;
  /// <summary>
  /// Control point identifier
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Cp {
    get { return cp_; }
    set {
      cp_ = value;
    }
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 2;
  private int offset_;
  /// <summary>
  /// Offset value
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Offset {
    get { return offset_; }
    set {
      offset_ = value;
    }
  }

  /// <summary>Field number for the "requested_time" field.</summary>
  public const int RequestedTimeFieldNumber = 3;
  private uint requestedTime_;
  /// <summary>
  /// Time requested
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RequestedTime {
    get { return requestedTime_; }
    set {
      requestedTime_ = value;
    }
  }

  /// <summary>Field number for the "requested_day" field.</summary>
  public const int RequestedDayFieldNumber = 4;
  private uint requestedDay_;
  /// <summary>
  /// Day requested
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RequestedDay {
    get { return requestedDay_; }
    set {
      requestedDay_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AppGetHistPowerResDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AppGetHistPowerResDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Cp != other.Cp) return false;
    if (Offset != other.Offset) return false;
    if (RequestedTime != other.RequestedTime) return false;
    if (RequestedDay != other.RequestedDay) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Cp != 0) hash ^= Cp.GetHashCode();
    if (Offset != 0) hash ^= Offset.GetHashCode();
    if (RequestedTime != 0) hash ^= RequestedTime.GetHashCode();
    if (RequestedDay != 0) hash ^= RequestedDay.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Cp != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Cp);
    }
    if (Offset != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Offset);
    }
    if (RequestedTime != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(RequestedTime);
    }
    if (RequestedDay != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(RequestedDay);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Cp != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Cp);
    }
    if (Offset != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Offset);
    }
    if (RequestedTime != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(RequestedTime);
    }
    if (RequestedDay != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(RequestedDay);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Cp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Cp);
    }
    if (Offset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
    }
    if (RequestedTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RequestedTime);
    }
    if (RequestedDay != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RequestedDay);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AppGetHistPowerResDTO other) {
    if (other == null) {
      return;
    }
    if (other.Cp != 0) {
      Cp = other.Cp;
    }
    if (other.Offset != 0) {
      Offset = other.Offset;
    }
    if (other.RequestedTime != 0) {
      RequestedTime = other.RequestedTime;
    }
    if (other.RequestedDay != 0) {
      RequestedDay = other.RequestedDay;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Cp = input.ReadInt32();
          break;
        }
        case 16: {
          Offset = input.ReadInt32();
          break;
        }
        case 24: {
          RequestedTime = input.ReadUInt32();
          break;
        }
        case 32: {
          RequestedDay = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Cp = input.ReadInt32();
          break;
        }
        case 16: {
          Offset = input.ReadInt32();
          break;
        }
        case 24: {
          RequestedTime = input.ReadUInt32();
          break;
        }
        case 32: {
          RequestedDay = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AppGetHistPowerReqDTO : pb::IMessage<AppGetHistPowerReqDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AppGetHistPowerReqDTO> _parser = new pb::MessageParser<AppGetHistPowerReqDTO>(() => new AppGetHistPowerReqDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AppGetHistPowerReqDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AppGetHistPowerReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistPowerReqDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistPowerReqDTO(AppGetHistPowerReqDTO other) : this() {
    serialNumber_ = other.serialNumber_;
    ap_ = other.ap_;
    cp_ = other.cp_;
    offset_ = other.offset_;
    requestTime_ = other.requestTime_;
    startTime_ = other.startTime_;
    longTermStart_ = other.longTermStart_;
    absoluteStart_ = other.absoluteStart_;
    stepTime_ = other.stepTime_;
    relativePower_ = other.relativePower_;
    totalEnergy_ = other.totalEnergy_;
    dailyEnergy_ = other.dailyEnergy_;
    powerArray_ = other.powerArray_.Clone();
    warningNumber_ = other.warningNumber_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistPowerReqDTO Clone() {
    return new AppGetHistPowerReqDTO(this);
  }

  /// <summary>Field number for the "serial_number" field.</summary>
  public const int SerialNumberFieldNumber = 1;
  private long serialNumber_;
  /// <summary>
  /// Device serial number
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long SerialNumber {
    get { return serialNumber_; }
    set {
      serialNumber_ = value;
    }
  }

  /// <summary>Field number for the "ap" field.</summary>
  public const int ApFieldNumber = 2;
  private int ap_;
  /// <summary>
  /// All Pages identifier
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Ap {
    get { return ap_; }
    set {
      ap_ = value;
    }
  }

  /// <summary>Field number for the "cp" field.</summary>
  public const int CpFieldNumber = 3;
  private int cp_;
  /// <summary>
  /// Current Page identifier
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Cp {
    get { return cp_; }
    set {
      cp_ = value;
    }
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 4;
  private int offset_;
  /// <summary>
  /// Offset value
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Offset {
    get { return offset_; }
    set {
      offset_ = value;
    }
  }

  /// <summary>Field number for the "request_time" field.</summary>
  public const int RequestTimeFieldNumber = 5;
  private uint requestTime_;
  /// <summary>
  /// Timestamp of the request
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RequestTime {
    get { return requestTime_; }
    set {
      requestTime_ = value;
    }
  }

  /// <summary>Field number for the "start_time" field.</summary>
  public const int StartTimeFieldNumber = 6;
  private uint startTime_;
  /// <summary>
  /// Start timestamp
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint StartTime {
    get { return startTime_; }
    set {
      startTime_ = value;
    }
  }

  /// <summary>Field number for the "long_term_start" field.</summary>
  public const int LongTermStartFieldNumber = 7;
  private uint longTermStart_;
  /// <summary>
  /// Long-term start timestamp
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint LongTermStart {
    get { return longTermStart_; }
    set {
      longTermStart_ = value;
    }
  }

  /// <summary>Field number for the "absolute_start" field.</summary>
  public const int AbsoluteStartFieldNumber = 8;
  private uint absoluteStart_;
  /// <summary>
  /// Absolute start timestamp
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint AbsoluteStart {
    get { return absoluteStart_; }
    set {
      absoluteStart_ = value;
    }
  }

  /// <summary>Field number for the "step_time" field.</summary>
  public const int StepTimeFieldNumber = 9;
  private uint stepTime_;
  /// <summary>
  /// Step time
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint StepTime {
    get { return stepTime_; }
    set {
      stepTime_ = value;
    }
  }

  /// <summary>Field number for the "relative_power" field.</summary>
  public const int RelativePowerFieldNumber = 10;
  private uint relativePower_;
  /// <summary>
  /// Relative power
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RelativePower {
    get { return relativePower_; }
    set {
      relativePower_ = value;
    }
  }

  /// <summary>Field number for the "total_energy" field.</summary>
  public const int TotalEnergyFieldNumber = 11;
  private uint totalEnergy_;
  /// <summary>
  /// Total energy
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint TotalEnergy {
    get { return totalEnergy_; }
    set {
      totalEnergy_ = value;
    }
  }

  /// <summary>Field number for the "daily_energy" field.</summary>
  public const int DailyEnergyFieldNumber = 12;
  private uint dailyEnergy_;
  /// <summary>
  /// Daily energy
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint DailyEnergy {
    get { return dailyEnergy_; }
    set {
      dailyEnergy_ = value;
    }
  }

  /// <summary>Field number for the "power_array" field.</summary>
  public const int PowerArrayFieldNumber = 13;
  private static readonly pb::FieldCodec<int> _repeated_powerArray_codec
      = pb::FieldCodec.ForInt32(106);
  private readonly pbc::RepeatedField<int> powerArray_ = new pbc::RepeatedField<int>();
  /// <summary>
  /// Array of power values
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> PowerArray {
    get { return powerArray_; }
  }

  /// <summary>Field number for the "warning_number" field.</summary>
  public const int WarningNumberFieldNumber = 14;
  private uint warningNumber_;
  /// <summary>
  /// Warning number
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint WarningNumber {
    get { return warningNumber_; }
    set {
      warningNumber_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AppGetHistPowerReqDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AppGetHistPowerReqDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SerialNumber != other.SerialNumber) return false;
    if (Ap != other.Ap) return false;
    if (Cp != other.Cp) return false;
    if (Offset != other.Offset) return false;
    if (RequestTime != other.RequestTime) return false;
    if (StartTime != other.StartTime) return false;
    if (LongTermStart != other.LongTermStart) return false;
    if (AbsoluteStart != other.AbsoluteStart) return false;
    if (StepTime != other.StepTime) return false;
    if (RelativePower != other.RelativePower) return false;
    if (TotalEnergy != other.TotalEnergy) return false;
    if (DailyEnergy != other.DailyEnergy) return false;
    if(!powerArray_.Equals(other.powerArray_)) return false;
    if (WarningNumber != other.WarningNumber) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SerialNumber != 0L) hash ^= SerialNumber.GetHashCode();
    if (Ap != 0) hash ^= Ap.GetHashCode();
    if (Cp != 0) hash ^= Cp.GetHashCode();
    if (Offset != 0) hash ^= Offset.GetHashCode();
    if (RequestTime != 0) hash ^= RequestTime.GetHashCode();
    if (StartTime != 0) hash ^= StartTime.GetHashCode();
    if (LongTermStart != 0) hash ^= LongTermStart.GetHashCode();
    if (AbsoluteStart != 0) hash ^= AbsoluteStart.GetHashCode();
    if (StepTime != 0) hash ^= StepTime.GetHashCode();
    if (RelativePower != 0) hash ^= RelativePower.GetHashCode();
    if (TotalEnergy != 0) hash ^= TotalEnergy.GetHashCode();
    if (DailyEnergy != 0) hash ^= DailyEnergy.GetHashCode();
    hash ^= powerArray_.GetHashCode();
    if (WarningNumber != 0) hash ^= WarningNumber.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SerialNumber != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(SerialNumber);
    }
    if (Ap != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Ap);
    }
    if (Cp != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Cp);
    }
    if (Offset != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Offset);
    }
    if (RequestTime != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(RequestTime);
    }
    if (StartTime != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(StartTime);
    }
    if (LongTermStart != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(LongTermStart);
    }
    if (AbsoluteStart != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(AbsoluteStart);
    }
    if (StepTime != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(StepTime);
    }
    if (RelativePower != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(RelativePower);
    }
    if (TotalEnergy != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(TotalEnergy);
    }
    if (DailyEnergy != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(DailyEnergy);
    }
    powerArray_.WriteTo(output, _repeated_powerArray_codec);
    if (WarningNumber != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(WarningNumber);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SerialNumber != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(SerialNumber);
    }
    if (Ap != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Ap);
    }
    if (Cp != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Cp);
    }
    if (Offset != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Offset);
    }
    if (RequestTime != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(RequestTime);
    }
    if (StartTime != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(StartTime);
    }
    if (LongTermStart != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(LongTermStart);
    }
    if (AbsoluteStart != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(AbsoluteStart);
    }
    if (StepTime != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(StepTime);
    }
    if (RelativePower != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(RelativePower);
    }
    if (TotalEnergy != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(TotalEnergy);
    }
    if (DailyEnergy != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(DailyEnergy);
    }
    powerArray_.WriteTo(ref output, _repeated_powerArray_codec);
    if (WarningNumber != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(WarningNumber);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SerialNumber != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(SerialNumber);
    }
    if (Ap != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Ap);
    }
    if (Cp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Cp);
    }
    if (Offset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
    }
    if (RequestTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RequestTime);
    }
    if (StartTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StartTime);
    }
    if (LongTermStart != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LongTermStart);
    }
    if (AbsoluteStart != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AbsoluteStart);
    }
    if (StepTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StepTime);
    }
    if (RelativePower != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RelativePower);
    }
    if (TotalEnergy != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TotalEnergy);
    }
    if (DailyEnergy != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DailyEnergy);
    }
    size += powerArray_.CalculateSize(_repeated_powerArray_codec);
    if (WarningNumber != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WarningNumber);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AppGetHistPowerReqDTO other) {
    if (other == null) {
      return;
    }
    if (other.SerialNumber != 0L) {
      SerialNumber = other.SerialNumber;
    }
    if (other.Ap != 0) {
      Ap = other.Ap;
    }
    if (other.Cp != 0) {
      Cp = other.Cp;
    }
    if (other.Offset != 0) {
      Offset = other.Offset;
    }
    if (other.RequestTime != 0) {
      RequestTime = other.RequestTime;
    }
    if (other.StartTime != 0) {
      StartTime = other.StartTime;
    }
    if (other.LongTermStart != 0) {
      LongTermStart = other.LongTermStart;
    }
    if (other.AbsoluteStart != 0) {
      AbsoluteStart = other.AbsoluteStart;
    }
    if (other.StepTime != 0) {
      StepTime = other.StepTime;
    }
    if (other.RelativePower != 0) {
      RelativePower = other.RelativePower;
    }
    if (other.TotalEnergy != 0) {
      TotalEnergy = other.TotalEnergy;
    }
    if (other.DailyEnergy != 0) {
      DailyEnergy = other.DailyEnergy;
    }
    powerArray_.Add(other.powerArray_);
    if (other.WarningNumber != 0) {
      WarningNumber = other.WarningNumber;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SerialNumber = input.ReadInt64();
          break;
        }
        case 16: {
          Ap = input.ReadInt32();
          break;
        }
        case 24: {
          Cp = input.ReadInt32();
          break;
        }
        case 32: {
          Offset = input.ReadInt32();
          break;
        }
        case 40: {
          RequestTime = input.ReadUInt32();
          break;
        }
        case 48: {
          StartTime = input.ReadUInt32();
          break;
        }
        case 56: {
          LongTermStart = input.ReadUInt32();
          break;
        }
        case 64: {
          AbsoluteStart = input.ReadUInt32();
          break;
        }
        case 72: {
          StepTime = input.ReadUInt32();
          break;
        }
        case 80: {
          RelativePower = input.ReadUInt32();
          break;
        }
        case 88: {
          TotalEnergy = input.ReadUInt32();
          break;
        }
        case 96: {
          DailyEnergy = input.ReadUInt32();
          break;
        }
        case 106:
        case 104: {
          powerArray_.AddEntriesFrom(input, _repeated_powerArray_codec);
          break;
        }
        case 112: {
          WarningNumber = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          SerialNumber = input.ReadInt64();
          break;
        }
        case 16: {
          Ap = input.ReadInt32();
          break;
        }
        case 24: {
          Cp = input.ReadInt32();
          break;
        }
        case 32: {
          Offset = input.ReadInt32();
          break;
        }
        case 40: {
          RequestTime = input.ReadUInt32();
          break;
        }
        case 48: {
          StartTime = input.ReadUInt32();
          break;
        }
        case 56: {
          LongTermStart = input.ReadUInt32();
          break;
        }
        case 64: {
          AbsoluteStart = input.ReadUInt32();
          break;
        }
        case 72: {
          StepTime = input.ReadUInt32();
          break;
        }
        case 80: {
          RelativePower = input.ReadUInt32();
          break;
        }
        case 88: {
          TotalEnergy = input.ReadUInt32();
          break;
        }
        case 96: {
          DailyEnergy = input.ReadUInt32();
          break;
        }
        case 106:
        case 104: {
          powerArray_.AddEntriesFrom(ref input, _repeated_powerArray_codec);
          break;
        }
        case 112: {
          WarningNumber = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
