// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AppGetHistED.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from AppGetHistED.proto</summary>
public static partial class AppGetHistEDReflection {

  #region Descriptor
  /// <summary>File descriptor for AppGetHistED.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AppGetHistEDReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJBcHBHZXRIaXN0RUQucHJvdG8iOwoSQXBwR2V0SGlzdEVEUmVzRFRPEgoK",
          "AmNwGAEgASgFEgsKA29mdBgCIAEoBRIMCgR0aW1lGAMgASgNIi0KD0FQUEVu",
          "ZXJneUluZm9NTxIKCgJlZBgBIAEoDRIOCgZyX3RpbWUYAiABKA0iXAoSQXBw",
          "R2V0SGlzdEVEUmVxRFRPEgoKAnNuGAEgASgDEgsKA29mdBgCIAEoBRIMCgR0",
          "aW1lGAMgASgNEh8KBWVuZXJnGAQgAygLMhAuQVBQRW5lcmd5SW5mb01PYgZw",
          "cm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AppGetHistEDResDTO), global::AppGetHistEDResDTO.Parser, new[]{ "Cp", "Oft", "Time" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::APPEnergyInfoMO), global::APPEnergyInfoMO.Parser, new[]{ "Ed", "RTime" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AppGetHistEDReqDTO), global::AppGetHistEDReqDTO.Parser, new[]{ "Sn", "Oft", "Time", "Energ" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AppGetHistEDResDTO : pb::IMessage<AppGetHistEDResDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AppGetHistEDResDTO> _parser = new pb::MessageParser<AppGetHistEDResDTO>(() => new AppGetHistEDResDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AppGetHistEDResDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AppGetHistEDReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistEDResDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistEDResDTO(AppGetHistEDResDTO other) : this() {
    cp_ = other.cp_;
    oft_ = other.oft_;
    time_ = other.time_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistEDResDTO Clone() {
    return new AppGetHistEDResDTO(this);
  }

  /// <summary>Field number for the "cp" field.</summary>
  public const int CpFieldNumber = 1;
  private int cp_;
  /// <summary>
  /// Control point identifier
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Cp {
    get { return cp_; }
    set {
      cp_ = value;
    }
  }

  /// <summary>Field number for the "oft" field.</summary>
  public const int OftFieldNumber = 2;
  private int oft_;
  /// <summary>
  /// Offset value
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Oft {
    get { return oft_; }
    set {
      oft_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 3;
  private uint time_;
  /// <summary>
  /// Timestamp of the response
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AppGetHistEDResDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AppGetHistEDResDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Cp != other.Cp) return false;
    if (Oft != other.Oft) return false;
    if (Time != other.Time) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Cp != 0) hash ^= Cp.GetHashCode();
    if (Oft != 0) hash ^= Oft.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Cp != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Cp);
    }
    if (Oft != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Oft);
    }
    if (Time != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Cp != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Cp);
    }
    if (Oft != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Oft);
    }
    if (Time != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Cp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Cp);
    }
    if (Oft != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Oft);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AppGetHistEDResDTO other) {
    if (other == null) {
      return;
    }
    if (other.Cp != 0) {
      Cp = other.Cp;
    }
    if (other.Oft != 0) {
      Oft = other.Oft;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Cp = input.ReadInt32();
          break;
        }
        case 16: {
          Oft = input.ReadInt32();
          break;
        }
        case 24: {
          Time = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Cp = input.ReadInt32();
          break;
        }
        case 16: {
          Oft = input.ReadInt32();
          break;
        }
        case 24: {
          Time = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class APPEnergyInfoMO : pb::IMessage<APPEnergyInfoMO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<APPEnergyInfoMO> _parser = new pb::MessageParser<APPEnergyInfoMO>(() => new APPEnergyInfoMO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<APPEnergyInfoMO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AppGetHistEDReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public APPEnergyInfoMO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public APPEnergyInfoMO(APPEnergyInfoMO other) : this() {
    ed_ = other.ed_;
    rTime_ = other.rTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public APPEnergyInfoMO Clone() {
    return new APPEnergyInfoMO(this);
  }

  /// <summary>Field number for the "ed" field.</summary>
  public const int EdFieldNumber = 1;
  private uint ed_;
  /// <summary>
  /// Energy data
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Ed {
    get { return ed_; }
    set {
      ed_ = value;
    }
  }

  /// <summary>Field number for the "r_time" field.</summary>
  public const int RTimeFieldNumber = 2;
  private uint rTime_;
  /// <summary>
  /// Relative timestamp
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RTime {
    get { return rTime_; }
    set {
      rTime_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as APPEnergyInfoMO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(APPEnergyInfoMO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Ed != other.Ed) return false;
    if (RTime != other.RTime) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Ed != 0) hash ^= Ed.GetHashCode();
    if (RTime != 0) hash ^= RTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Ed != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Ed);
    }
    if (RTime != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(RTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Ed != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Ed);
    }
    if (RTime != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(RTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Ed != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Ed);
    }
    if (RTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RTime);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(APPEnergyInfoMO other) {
    if (other == null) {
      return;
    }
    if (other.Ed != 0) {
      Ed = other.Ed;
    }
    if (other.RTime != 0) {
      RTime = other.RTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Ed = input.ReadUInt32();
          break;
        }
        case 16: {
          RTime = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Ed = input.ReadUInt32();
          break;
        }
        case 16: {
          RTime = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AppGetHistEDReqDTO : pb::IMessage<AppGetHistEDReqDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AppGetHistEDReqDTO> _parser = new pb::MessageParser<AppGetHistEDReqDTO>(() => new AppGetHistEDReqDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AppGetHistEDReqDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AppGetHistEDReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistEDReqDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistEDReqDTO(AppGetHistEDReqDTO other) : this() {
    sn_ = other.sn_;
    oft_ = other.oft_;
    time_ = other.time_;
    energ_ = other.energ_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AppGetHistEDReqDTO Clone() {
    return new AppGetHistEDReqDTO(this);
  }

  /// <summary>Field number for the "sn" field.</summary>
  public const int SnFieldNumber = 1;
  private long sn_;
  /// <summary>
  /// Serial number
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Sn {
    get { return sn_; }
    set {
      sn_ = value;
    }
  }

  /// <summary>Field number for the "oft" field.</summary>
  public const int OftFieldNumber = 2;
  private int oft_;
  /// <summary>
  /// Offset value
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Oft {
    get { return oft_; }
    set {
      oft_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 3;
  private uint time_;
  /// <summary>
  /// Timestamp of the request
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  /// <summary>Field number for the "energ" field.</summary>
  public const int EnergFieldNumber = 4;
  private static readonly pb::FieldCodec<global::APPEnergyInfoMO> _repeated_energ_codec
      = pb::FieldCodec.ForMessage(34, global::APPEnergyInfoMO.Parser);
  private readonly pbc::RepeatedField<global::APPEnergyInfoMO> energ_ = new pbc::RepeatedField<global::APPEnergyInfoMO>();
  /// <summary>
  /// APPEnergyInfoMO data array
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::APPEnergyInfoMO> Energ {
    get { return energ_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AppGetHistEDReqDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AppGetHistEDReqDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Sn != other.Sn) return false;
    if (Oft != other.Oft) return false;
    if (Time != other.Time) return false;
    if(!energ_.Equals(other.energ_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Sn != 0L) hash ^= Sn.GetHashCode();
    if (Oft != 0) hash ^= Oft.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    hash ^= energ_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Sn != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Sn);
    }
    if (Oft != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Oft);
    }
    if (Time != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Time);
    }
    energ_.WriteTo(output, _repeated_energ_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Sn != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Sn);
    }
    if (Oft != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Oft);
    }
    if (Time != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Time);
    }
    energ_.WriteTo(ref output, _repeated_energ_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Sn != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Sn);
    }
    if (Oft != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Oft);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Time);
    }
    size += energ_.CalculateSize(_repeated_energ_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AppGetHistEDReqDTO other) {
    if (other == null) {
      return;
    }
    if (other.Sn != 0L) {
      Sn = other.Sn;
    }
    if (other.Oft != 0) {
      Oft = other.Oft;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    energ_.Add(other.energ_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Sn = input.ReadInt64();
          break;
        }
        case 16: {
          Oft = input.ReadInt32();
          break;
        }
        case 24: {
          Time = input.ReadUInt32();
          break;
        }
        case 34: {
          energ_.AddEntriesFrom(input, _repeated_energ_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Sn = input.ReadInt64();
          break;
        }
        case 16: {
          Oft = input.ReadInt32();
          break;
        }
        case 24: {
          Time = input.ReadUInt32();
          break;
        }
        case 34: {
          energ_.AddEntriesFrom(ref input, _repeated_energ_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
