// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ESRegPB.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ESRegPB.proto</summary>
public static partial class ESRegPBReflection {

  #region Descriptor
  /// <summary>File descriptor for ESRegPB.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ESRegPBReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1FU1JlZ1BCLnByb3RvIkAKB0NoZ0NQTU8SFQoNc2VyaWFsX251bWJlchgB",
          "IAEoAxIOCgZzd192ZXIYAiABKAUSDgoGaHdfdmVyGAMgASgFIqoBCgtFU1Jl",
          "Z1JlcURUTxIMCgR0eXBlGAEgASgFEhoKBW1ldGVyGAIgASgLMgsuUmVnTWV0",
          "ZXJNTxIcCglpbnZlcnRlcnMYAyADKAsyCS5SZWdJbnZNTxIQCghnZW5fbW9k",
          "ZRgEIAEoBRIMCgR0aW1lGAUgASgFEg4KBm9mZnNldBgGIAEoBRIWCgNtaWQY",
          "ByADKAsyCS5SZWdNaWRNTxILCgNkZnMYCCABKAMiTQoLRVNSZWdSZXNEVE8S",
          "DAoEdGltZRgBIAEoBRIUCgx0aW1lX3ltZF9obXMYAiABKAwSDgoGb2Zmc2V0",
          "GAMgASgFEgoKAmNwGAQgASgFIq0CCghSZWdJbnZNTxIVCg1zZXJpYWxfbnVt",
          "YmVyGAEgASgDEgwKBHR5cGUYAiABKAUSDgoGaHdfdmVyGAMgASgJEhAKCHN3",
          "X21fdmVyGAQgASgJEhAKCHN3X3NfdmVyGAUgASgJEhIKCnN3X3N5c192ZXIY",
          "BiABKAkSDgoGYm1zX3NuGAcgASgJEhIKCmJtc19od192ZXIYCCABKAkSEgoK",
          "Ym1zX3N3X3ZlchgJIAEoCRIPCgdibXNfY2FwGAogASgFEg4KBnB2X251bRgL",
          "IAEoBRIMCgRhZGRyGAwgASgFEhIKCm1vZGVsX25hbWUYDSABKAkSEAoIYm1z",
          "X3Byb3QYDiABKAUSEAoIYm1zX3R5cGUYDyABKAUSFQoDY3BzGBAgAygLMggu",
          "Q2hnQ1BNTyIyCgpSZWdNZXRlck1PEhUKDXNlcmlhbF9udW1iZXIYASABKAkS",
          "DQoFc25fcHYYAiABKAkiQQoIUmVnTWlkTU8SFQoNc2VyaWFsX251bWJlchgB",
          "IAEoAxIOCgZzd192ZXIYAiABKAkSDgoGaHdfdmVyGAMgASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ChgCPMO), global::ChgCPMO.Parser, new[]{ "SerialNumber", "SwVer", "HwVer" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ESRegReqDTO), global::ESRegReqDTO.Parser, new[]{ "Type", "Meter", "Inverters", "GenMode", "Time", "Offset", "Mid", "Dfs" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ESRegResDTO), global::ESRegResDTO.Parser, new[]{ "Time", "TimeYmdHms", "Offset", "Cp" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RegInvMO), global::RegInvMO.Parser, new[]{ "SerialNumber", "Type", "HwVer", "SwMVer", "SwSVer", "SwSysVer", "BmsSn", "BmsHwVer", "BmsSwVer", "BmsCap", "PvNum", "Addr", "ModelName", "BmsProt", "BmsType", "Cps" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RegMeterMO), global::RegMeterMO.Parser, new[]{ "SerialNumber", "SnPv" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RegMidMO), global::RegMidMO.Parser, new[]{ "SerialNumber", "SwVer", "HwVer" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ChgCPMO : pb::IMessage<ChgCPMO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ChgCPMO> _parser = new pb::MessageParser<ChgCPMO>(() => new ChgCPMO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ChgCPMO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ESRegPBReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChgCPMO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChgCPMO(ChgCPMO other) : this() {
    serialNumber_ = other.serialNumber_;
    swVer_ = other.swVer_;
    hwVer_ = other.hwVer_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChgCPMO Clone() {
    return new ChgCPMO(this);
  }

  /// <summary>Field number for the "serial_number" field.</summary>
  public const int SerialNumberFieldNumber = 1;
  private long serialNumber_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long SerialNumber {
    get { return serialNumber_; }
    set {
      serialNumber_ = value;
    }
  }

  /// <summary>Field number for the "sw_ver" field.</summary>
  public const int SwVerFieldNumber = 2;
  private int swVer_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SwVer {
    get { return swVer_; }
    set {
      swVer_ = value;
    }
  }

  /// <summary>Field number for the "hw_ver" field.</summary>
  public const int HwVerFieldNumber = 3;
  private int hwVer_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int HwVer {
    get { return hwVer_; }
    set {
      hwVer_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ChgCPMO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ChgCPMO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SerialNumber != other.SerialNumber) return false;
    if (SwVer != other.SwVer) return false;
    if (HwVer != other.HwVer) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SerialNumber != 0L) hash ^= SerialNumber.GetHashCode();
    if (SwVer != 0) hash ^= SwVer.GetHashCode();
    if (HwVer != 0) hash ^= HwVer.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SerialNumber != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(SerialNumber);
    }
    if (SwVer != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(SwVer);
    }
    if (HwVer != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(HwVer);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SerialNumber != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(SerialNumber);
    }
    if (SwVer != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(SwVer);
    }
    if (HwVer != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(HwVer);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SerialNumber != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(SerialNumber);
    }
    if (SwVer != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SwVer);
    }
    if (HwVer != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(HwVer);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ChgCPMO other) {
    if (other == null) {
      return;
    }
    if (other.SerialNumber != 0L) {
      SerialNumber = other.SerialNumber;
    }
    if (other.SwVer != 0) {
      SwVer = other.SwVer;
    }
    if (other.HwVer != 0) {
      HwVer = other.HwVer;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SerialNumber = input.ReadInt64();
          break;
        }
        case 16: {
          SwVer = input.ReadInt32();
          break;
        }
        case 24: {
          HwVer = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          SerialNumber = input.ReadInt64();
          break;
        }
        case 16: {
          SwVer = input.ReadInt32();
          break;
        }
        case 24: {
          HwVer = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ESRegReqDTO : pb::IMessage<ESRegReqDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ESRegReqDTO> _parser = new pb::MessageParser<ESRegReqDTO>(() => new ESRegReqDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ESRegReqDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ESRegPBReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ESRegReqDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ESRegReqDTO(ESRegReqDTO other) : this() {
    type_ = other.type_;
    meter_ = other.meter_ != null ? other.meter_.Clone() : null;
    inverters_ = other.inverters_.Clone();
    genMode_ = other.genMode_;
    time_ = other.time_;
    offset_ = other.offset_;
    mid_ = other.mid_.Clone();
    dfs_ = other.dfs_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ESRegReqDTO Clone() {
    return new ESRegReqDTO(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private int type_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "meter" field.</summary>
  public const int MeterFieldNumber = 2;
  private global::RegMeterMO meter_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RegMeterMO Meter {
    get { return meter_; }
    set {
      meter_ = value;
    }
  }

  /// <summary>Field number for the "inverters" field.</summary>
  public const int InvertersFieldNumber = 3;
  private static readonly pb::FieldCodec<global::RegInvMO> _repeated_inverters_codec
      = pb::FieldCodec.ForMessage(26, global::RegInvMO.Parser);
  private readonly pbc::RepeatedField<global::RegInvMO> inverters_ = new pbc::RepeatedField<global::RegInvMO>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::RegInvMO> Inverters {
    get { return inverters_; }
  }

  /// <summary>Field number for the "gen_mode" field.</summary>
  public const int GenModeFieldNumber = 4;
  private int genMode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GenMode {
    get { return genMode_; }
    set {
      genMode_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 5;
  private int time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 6;
  private int offset_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Offset {
    get { return offset_; }
    set {
      offset_ = value;
    }
  }

  /// <summary>Field number for the "mid" field.</summary>
  public const int MidFieldNumber = 7;
  private static readonly pb::FieldCodec<global::RegMidMO> _repeated_mid_codec
      = pb::FieldCodec.ForMessage(58, global::RegMidMO.Parser);
  private readonly pbc::RepeatedField<global::RegMidMO> mid_ = new pbc::RepeatedField<global::RegMidMO>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::RegMidMO> Mid {
    get { return mid_; }
  }

  /// <summary>Field number for the "dfs" field.</summary>
  public const int DfsFieldNumber = 8;
  private long dfs_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Dfs {
    get { return dfs_; }
    set {
      dfs_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ESRegReqDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ESRegReqDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (!object.Equals(Meter, other.Meter)) return false;
    if(!inverters_.Equals(other.inverters_)) return false;
    if (GenMode != other.GenMode) return false;
    if (Time != other.Time) return false;
    if (Offset != other.Offset) return false;
    if(!mid_.Equals(other.mid_)) return false;
    if (Dfs != other.Dfs) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != 0) hash ^= Type.GetHashCode();
    if (meter_ != null) hash ^= Meter.GetHashCode();
    hash ^= inverters_.GetHashCode();
    if (GenMode != 0) hash ^= GenMode.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (Offset != 0) hash ^= Offset.GetHashCode();
    hash ^= mid_.GetHashCode();
    if (Dfs != 0L) hash ^= Dfs.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Type);
    }
    if (meter_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Meter);
    }
    inverters_.WriteTo(output, _repeated_inverters_codec);
    if (GenMode != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(GenMode);
    }
    if (Time != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Time);
    }
    if (Offset != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Offset);
    }
    mid_.WriteTo(output, _repeated_mid_codec);
    if (Dfs != 0L) {
      output.WriteRawTag(64);
      output.WriteInt64(Dfs);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Type);
    }
    if (meter_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Meter);
    }
    inverters_.WriteTo(ref output, _repeated_inverters_codec);
    if (GenMode != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(GenMode);
    }
    if (Time != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Time);
    }
    if (Offset != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Offset);
    }
    mid_.WriteTo(ref output, _repeated_mid_codec);
    if (Dfs != 0L) {
      output.WriteRawTag(64);
      output.WriteInt64(Dfs);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
    }
    if (meter_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Meter);
    }
    size += inverters_.CalculateSize(_repeated_inverters_codec);
    if (GenMode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GenMode);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
    }
    if (Offset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
    }
    size += mid_.CalculateSize(_repeated_mid_codec);
    if (Dfs != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Dfs);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ESRegReqDTO other) {
    if (other == null) {
      return;
    }
    if (other.Type != 0) {
      Type = other.Type;
    }
    if (other.meter_ != null) {
      if (meter_ == null) {
        Meter = new global::RegMeterMO();
      }
      Meter.MergeFrom(other.Meter);
    }
    inverters_.Add(other.inverters_);
    if (other.GenMode != 0) {
      GenMode = other.GenMode;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    if (other.Offset != 0) {
      Offset = other.Offset;
    }
    mid_.Add(other.mid_);
    if (other.Dfs != 0L) {
      Dfs = other.Dfs;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = input.ReadInt32();
          break;
        }
        case 18: {
          if (meter_ == null) {
            Meter = new global::RegMeterMO();
          }
          input.ReadMessage(Meter);
          break;
        }
        case 26: {
          inverters_.AddEntriesFrom(input, _repeated_inverters_codec);
          break;
        }
        case 32: {
          GenMode = input.ReadInt32();
          break;
        }
        case 40: {
          Time = input.ReadInt32();
          break;
        }
        case 48: {
          Offset = input.ReadInt32();
          break;
        }
        case 58: {
          mid_.AddEntriesFrom(input, _repeated_mid_codec);
          break;
        }
        case 64: {
          Dfs = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = input.ReadInt32();
          break;
        }
        case 18: {
          if (meter_ == null) {
            Meter = new global::RegMeterMO();
          }
          input.ReadMessage(Meter);
          break;
        }
        case 26: {
          inverters_.AddEntriesFrom(ref input, _repeated_inverters_codec);
          break;
        }
        case 32: {
          GenMode = input.ReadInt32();
          break;
        }
        case 40: {
          Time = input.ReadInt32();
          break;
        }
        case 48: {
          Offset = input.ReadInt32();
          break;
        }
        case 58: {
          mid_.AddEntriesFrom(ref input, _repeated_mid_codec);
          break;
        }
        case 64: {
          Dfs = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ESRegResDTO : pb::IMessage<ESRegResDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ESRegResDTO> _parser = new pb::MessageParser<ESRegResDTO>(() => new ESRegResDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ESRegResDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ESRegPBReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ESRegResDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ESRegResDTO(ESRegResDTO other) : this() {
    time_ = other.time_;
    timeYmdHms_ = other.timeYmdHms_;
    offset_ = other.offset_;
    cp_ = other.cp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ESRegResDTO Clone() {
    return new ESRegResDTO(this);
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 1;
  private int time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  /// <summary>Field number for the "time_ymd_hms" field.</summary>
  public const int TimeYmdHmsFieldNumber = 2;
  private pb::ByteString timeYmdHms_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString TimeYmdHms {
    get { return timeYmdHms_; }
    set {
      timeYmdHms_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 3;
  private int offset_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Offset {
    get { return offset_; }
    set {
      offset_ = value;
    }
  }

  /// <summary>Field number for the "cp" field.</summary>
  public const int CpFieldNumber = 4;
  private int cp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Cp {
    get { return cp_; }
    set {
      cp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ESRegResDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ESRegResDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Time != other.Time) return false;
    if (TimeYmdHms != other.TimeYmdHms) return false;
    if (Offset != other.Offset) return false;
    if (Cp != other.Cp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Time != 0) hash ^= Time.GetHashCode();
    if (TimeYmdHms.Length != 0) hash ^= TimeYmdHms.GetHashCode();
    if (Offset != 0) hash ^= Offset.GetHashCode();
    if (Cp != 0) hash ^= Cp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Time != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Time);
    }
    if (TimeYmdHms.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(TimeYmdHms);
    }
    if (Offset != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Offset);
    }
    if (Cp != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Cp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Time != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Time);
    }
    if (TimeYmdHms.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(TimeYmdHms);
    }
    if (Offset != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Offset);
    }
    if (Cp != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Cp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
    }
    if (TimeYmdHms.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(TimeYmdHms);
    }
    if (Offset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
    }
    if (Cp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Cp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ESRegResDTO other) {
    if (other == null) {
      return;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    if (other.TimeYmdHms.Length != 0) {
      TimeYmdHms = other.TimeYmdHms;
    }
    if (other.Offset != 0) {
      Offset = other.Offset;
    }
    if (other.Cp != 0) {
      Cp = other.Cp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Time = input.ReadInt32();
          break;
        }
        case 18: {
          TimeYmdHms = input.ReadBytes();
          break;
        }
        case 24: {
          Offset = input.ReadInt32();
          break;
        }
        case 32: {
          Cp = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Time = input.ReadInt32();
          break;
        }
        case 18: {
          TimeYmdHms = input.ReadBytes();
          break;
        }
        case 24: {
          Offset = input.ReadInt32();
          break;
        }
        case 32: {
          Cp = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RegInvMO : pb::IMessage<RegInvMO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RegInvMO> _parser = new pb::MessageParser<RegInvMO>(() => new RegInvMO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RegInvMO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ESRegPBReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegInvMO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegInvMO(RegInvMO other) : this() {
    serialNumber_ = other.serialNumber_;
    type_ = other.type_;
    hwVer_ = other.hwVer_;
    swMVer_ = other.swMVer_;
    swSVer_ = other.swSVer_;
    swSysVer_ = other.swSysVer_;
    bmsSn_ = other.bmsSn_;
    bmsHwVer_ = other.bmsHwVer_;
    bmsSwVer_ = other.bmsSwVer_;
    bmsCap_ = other.bmsCap_;
    pvNum_ = other.pvNum_;
    addr_ = other.addr_;
    modelName_ = other.modelName_;
    bmsProt_ = other.bmsProt_;
    bmsType_ = other.bmsType_;
    cps_ = other.cps_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegInvMO Clone() {
    return new RegInvMO(this);
  }

  /// <summary>Field number for the "serial_number" field.</summary>
  public const int SerialNumberFieldNumber = 1;
  private long serialNumber_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long SerialNumber {
    get { return serialNumber_; }
    set {
      serialNumber_ = value;
    }
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 2;
  private int type_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "hw_ver" field.</summary>
  public const int HwVerFieldNumber = 3;
  private string hwVer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HwVer {
    get { return hwVer_; }
    set {
      hwVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sw_m_ver" field.</summary>
  public const int SwMVerFieldNumber = 4;
  private string swMVer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SwMVer {
    get { return swMVer_; }
    set {
      swMVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sw_s_ver" field.</summary>
  public const int SwSVerFieldNumber = 5;
  private string swSVer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SwSVer {
    get { return swSVer_; }
    set {
      swSVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sw_sys_ver" field.</summary>
  public const int SwSysVerFieldNumber = 6;
  private string swSysVer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SwSysVer {
    get { return swSysVer_; }
    set {
      swSysVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "bms_sn" field.</summary>
  public const int BmsSnFieldNumber = 7;
  private string bmsSn_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string BmsSn {
    get { return bmsSn_; }
    set {
      bmsSn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "bms_hw_ver" field.</summary>
  public const int BmsHwVerFieldNumber = 8;
  private string bmsHwVer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string BmsHwVer {
    get { return bmsHwVer_; }
    set {
      bmsHwVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "bms_sw_ver" field.</summary>
  public const int BmsSwVerFieldNumber = 9;
  private string bmsSwVer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string BmsSwVer {
    get { return bmsSwVer_; }
    set {
      bmsSwVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "bms_cap" field.</summary>
  public const int BmsCapFieldNumber = 10;
  private int bmsCap_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BmsCap {
    get { return bmsCap_; }
    set {
      bmsCap_ = value;
    }
  }

  /// <summary>Field number for the "pv_num" field.</summary>
  public const int PvNumFieldNumber = 11;
  private int pvNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PvNum {
    get { return pvNum_; }
    set {
      pvNum_ = value;
    }
  }

  /// <summary>Field number for the "addr" field.</summary>
  public const int AddrFieldNumber = 12;
  private int addr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Addr {
    get { return addr_; }
    set {
      addr_ = value;
    }
  }

  /// <summary>Field number for the "model_name" field.</summary>
  public const int ModelNameFieldNumber = 13;
  private string modelName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ModelName {
    get { return modelName_; }
    set {
      modelName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "bms_prot" field.</summary>
  public const int BmsProtFieldNumber = 14;
  private int bmsProt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BmsProt {
    get { return bmsProt_; }
    set {
      bmsProt_ = value;
    }
  }

  /// <summary>Field number for the "bms_type" field.</summary>
  public const int BmsTypeFieldNumber = 15;
  private int bmsType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BmsType {
    get { return bmsType_; }
    set {
      bmsType_ = value;
    }
  }

  /// <summary>Field number for the "cps" field.</summary>
  public const int CpsFieldNumber = 16;
  private static readonly pb::FieldCodec<global::ChgCPMO> _repeated_cps_codec
      = pb::FieldCodec.ForMessage(130, global::ChgCPMO.Parser);
  private readonly pbc::RepeatedField<global::ChgCPMO> cps_ = new pbc::RepeatedField<global::ChgCPMO>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ChgCPMO> Cps {
    get { return cps_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RegInvMO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RegInvMO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SerialNumber != other.SerialNumber) return false;
    if (Type != other.Type) return false;
    if (HwVer != other.HwVer) return false;
    if (SwMVer != other.SwMVer) return false;
    if (SwSVer != other.SwSVer) return false;
    if (SwSysVer != other.SwSysVer) return false;
    if (BmsSn != other.BmsSn) return false;
    if (BmsHwVer != other.BmsHwVer) return false;
    if (BmsSwVer != other.BmsSwVer) return false;
    if (BmsCap != other.BmsCap) return false;
    if (PvNum != other.PvNum) return false;
    if (Addr != other.Addr) return false;
    if (ModelName != other.ModelName) return false;
    if (BmsProt != other.BmsProt) return false;
    if (BmsType != other.BmsType) return false;
    if(!cps_.Equals(other.cps_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SerialNumber != 0L) hash ^= SerialNumber.GetHashCode();
    if (Type != 0) hash ^= Type.GetHashCode();
    if (HwVer.Length != 0) hash ^= HwVer.GetHashCode();
    if (SwMVer.Length != 0) hash ^= SwMVer.GetHashCode();
    if (SwSVer.Length != 0) hash ^= SwSVer.GetHashCode();
    if (SwSysVer.Length != 0) hash ^= SwSysVer.GetHashCode();
    if (BmsSn.Length != 0) hash ^= BmsSn.GetHashCode();
    if (BmsHwVer.Length != 0) hash ^= BmsHwVer.GetHashCode();
    if (BmsSwVer.Length != 0) hash ^= BmsSwVer.GetHashCode();
    if (BmsCap != 0) hash ^= BmsCap.GetHashCode();
    if (PvNum != 0) hash ^= PvNum.GetHashCode();
    if (Addr != 0) hash ^= Addr.GetHashCode();
    if (ModelName.Length != 0) hash ^= ModelName.GetHashCode();
    if (BmsProt != 0) hash ^= BmsProt.GetHashCode();
    if (BmsType != 0) hash ^= BmsType.GetHashCode();
    hash ^= cps_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SerialNumber != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(SerialNumber);
    }
    if (Type != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Type);
    }
    if (HwVer.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(HwVer);
    }
    if (SwMVer.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(SwMVer);
    }
    if (SwSVer.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(SwSVer);
    }
    if (SwSysVer.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(SwSysVer);
    }
    if (BmsSn.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(BmsSn);
    }
    if (BmsHwVer.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(BmsHwVer);
    }
    if (BmsSwVer.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(BmsSwVer);
    }
    if (BmsCap != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(BmsCap);
    }
    if (PvNum != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(PvNum);
    }
    if (Addr != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(Addr);
    }
    if (ModelName.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(ModelName);
    }
    if (BmsProt != 0) {
      output.WriteRawTag(112);
      output.WriteInt32(BmsProt);
    }
    if (BmsType != 0) {
      output.WriteRawTag(120);
      output.WriteInt32(BmsType);
    }
    cps_.WriteTo(output, _repeated_cps_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SerialNumber != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(SerialNumber);
    }
    if (Type != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Type);
    }
    if (HwVer.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(HwVer);
    }
    if (SwMVer.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(SwMVer);
    }
    if (SwSVer.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(SwSVer);
    }
    if (SwSysVer.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(SwSysVer);
    }
    if (BmsSn.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(BmsSn);
    }
    if (BmsHwVer.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(BmsHwVer);
    }
    if (BmsSwVer.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(BmsSwVer);
    }
    if (BmsCap != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(BmsCap);
    }
    if (PvNum != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(PvNum);
    }
    if (Addr != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(Addr);
    }
    if (ModelName.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(ModelName);
    }
    if (BmsProt != 0) {
      output.WriteRawTag(112);
      output.WriteInt32(BmsProt);
    }
    if (BmsType != 0) {
      output.WriteRawTag(120);
      output.WriteInt32(BmsType);
    }
    cps_.WriteTo(ref output, _repeated_cps_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SerialNumber != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(SerialNumber);
    }
    if (Type != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
    }
    if (HwVer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HwVer);
    }
    if (SwMVer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SwMVer);
    }
    if (SwSVer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SwSVer);
    }
    if (SwSysVer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SwSysVer);
    }
    if (BmsSn.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(BmsSn);
    }
    if (BmsHwVer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(BmsHwVer);
    }
    if (BmsSwVer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(BmsSwVer);
    }
    if (BmsCap != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BmsCap);
    }
    if (PvNum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PvNum);
    }
    if (Addr != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Addr);
    }
    if (ModelName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ModelName);
    }
    if (BmsProt != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BmsProt);
    }
    if (BmsType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BmsType);
    }
    size += cps_.CalculateSize(_repeated_cps_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RegInvMO other) {
    if (other == null) {
      return;
    }
    if (other.SerialNumber != 0L) {
      SerialNumber = other.SerialNumber;
    }
    if (other.Type != 0) {
      Type = other.Type;
    }
    if (other.HwVer.Length != 0) {
      HwVer = other.HwVer;
    }
    if (other.SwMVer.Length != 0) {
      SwMVer = other.SwMVer;
    }
    if (other.SwSVer.Length != 0) {
      SwSVer = other.SwSVer;
    }
    if (other.SwSysVer.Length != 0) {
      SwSysVer = other.SwSysVer;
    }
    if (other.BmsSn.Length != 0) {
      BmsSn = other.BmsSn;
    }
    if (other.BmsHwVer.Length != 0) {
      BmsHwVer = other.BmsHwVer;
    }
    if (other.BmsSwVer.Length != 0) {
      BmsSwVer = other.BmsSwVer;
    }
    if (other.BmsCap != 0) {
      BmsCap = other.BmsCap;
    }
    if (other.PvNum != 0) {
      PvNum = other.PvNum;
    }
    if (other.Addr != 0) {
      Addr = other.Addr;
    }
    if (other.ModelName.Length != 0) {
      ModelName = other.ModelName;
    }
    if (other.BmsProt != 0) {
      BmsProt = other.BmsProt;
    }
    if (other.BmsType != 0) {
      BmsType = other.BmsType;
    }
    cps_.Add(other.cps_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SerialNumber = input.ReadInt64();
          break;
        }
        case 16: {
          Type = input.ReadInt32();
          break;
        }
        case 26: {
          HwVer = input.ReadString();
          break;
        }
        case 34: {
          SwMVer = input.ReadString();
          break;
        }
        case 42: {
          SwSVer = input.ReadString();
          break;
        }
        case 50: {
          SwSysVer = input.ReadString();
          break;
        }
        case 58: {
          BmsSn = input.ReadString();
          break;
        }
        case 66: {
          BmsHwVer = input.ReadString();
          break;
        }
        case 74: {
          BmsSwVer = input.ReadString();
          break;
        }
        case 80: {
          BmsCap = input.ReadInt32();
          break;
        }
        case 88: {
          PvNum = input.ReadInt32();
          break;
        }
        case 96: {
          Addr = input.ReadInt32();
          break;
        }
        case 106: {
          ModelName = input.ReadString();
          break;
        }
        case 112: {
          BmsProt = input.ReadInt32();
          break;
        }
        case 120: {
          BmsType = input.ReadInt32();
          break;
        }
        case 130: {
          cps_.AddEntriesFrom(input, _repeated_cps_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          SerialNumber = input.ReadInt64();
          break;
        }
        case 16: {
          Type = input.ReadInt32();
          break;
        }
        case 26: {
          HwVer = input.ReadString();
          break;
        }
        case 34: {
          SwMVer = input.ReadString();
          break;
        }
        case 42: {
          SwSVer = input.ReadString();
          break;
        }
        case 50: {
          SwSysVer = input.ReadString();
          break;
        }
        case 58: {
          BmsSn = input.ReadString();
          break;
        }
        case 66: {
          BmsHwVer = input.ReadString();
          break;
        }
        case 74: {
          BmsSwVer = input.ReadString();
          break;
        }
        case 80: {
          BmsCap = input.ReadInt32();
          break;
        }
        case 88: {
          PvNum = input.ReadInt32();
          break;
        }
        case 96: {
          Addr = input.ReadInt32();
          break;
        }
        case 106: {
          ModelName = input.ReadString();
          break;
        }
        case 112: {
          BmsProt = input.ReadInt32();
          break;
        }
        case 120: {
          BmsType = input.ReadInt32();
          break;
        }
        case 130: {
          cps_.AddEntriesFrom(ref input, _repeated_cps_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RegMeterMO : pb::IMessage<RegMeterMO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RegMeterMO> _parser = new pb::MessageParser<RegMeterMO>(() => new RegMeterMO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RegMeterMO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ESRegPBReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegMeterMO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegMeterMO(RegMeterMO other) : this() {
    serialNumber_ = other.serialNumber_;
    snPv_ = other.snPv_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegMeterMO Clone() {
    return new RegMeterMO(this);
  }

  /// <summary>Field number for the "serial_number" field.</summary>
  public const int SerialNumberFieldNumber = 1;
  private string serialNumber_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SerialNumber {
    get { return serialNumber_; }
    set {
      serialNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sn_pv" field.</summary>
  public const int SnPvFieldNumber = 2;
  private string snPv_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SnPv {
    get { return snPv_; }
    set {
      snPv_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RegMeterMO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RegMeterMO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SerialNumber != other.SerialNumber) return false;
    if (SnPv != other.SnPv) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SerialNumber.Length != 0) hash ^= SerialNumber.GetHashCode();
    if (SnPv.Length != 0) hash ^= SnPv.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SerialNumber.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SerialNumber);
    }
    if (SnPv.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(SnPv);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SerialNumber.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SerialNumber);
    }
    if (SnPv.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(SnPv);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SerialNumber.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SerialNumber);
    }
    if (SnPv.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SnPv);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RegMeterMO other) {
    if (other == null) {
      return;
    }
    if (other.SerialNumber.Length != 0) {
      SerialNumber = other.SerialNumber;
    }
    if (other.SnPv.Length != 0) {
      SnPv = other.SnPv;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          SerialNumber = input.ReadString();
          break;
        }
        case 18: {
          SnPv = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          SerialNumber = input.ReadString();
          break;
        }
        case 18: {
          SnPv = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RegMidMO : pb::IMessage<RegMidMO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RegMidMO> _parser = new pb::MessageParser<RegMidMO>(() => new RegMidMO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RegMidMO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ESRegPBReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegMidMO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegMidMO(RegMidMO other) : this() {
    serialNumber_ = other.serialNumber_;
    swVer_ = other.swVer_;
    hwVer_ = other.hwVer_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegMidMO Clone() {
    return new RegMidMO(this);
  }

  /// <summary>Field number for the "serial_number" field.</summary>
  public const int SerialNumberFieldNumber = 1;
  private long serialNumber_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long SerialNumber {
    get { return serialNumber_; }
    set {
      serialNumber_ = value;
    }
  }

  /// <summary>Field number for the "sw_ver" field.</summary>
  public const int SwVerFieldNumber = 2;
  private string swVer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SwVer {
    get { return swVer_; }
    set {
      swVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "hw_ver" field.</summary>
  public const int HwVerFieldNumber = 3;
  private string hwVer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HwVer {
    get { return hwVer_; }
    set {
      hwVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RegMidMO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RegMidMO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SerialNumber != other.SerialNumber) return false;
    if (SwVer != other.SwVer) return false;
    if (HwVer != other.HwVer) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SerialNumber != 0L) hash ^= SerialNumber.GetHashCode();
    if (SwVer.Length != 0) hash ^= SwVer.GetHashCode();
    if (HwVer.Length != 0) hash ^= HwVer.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SerialNumber != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(SerialNumber);
    }
    if (SwVer.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(SwVer);
    }
    if (HwVer.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(HwVer);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SerialNumber != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(SerialNumber);
    }
    if (SwVer.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(SwVer);
    }
    if (HwVer.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(HwVer);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SerialNumber != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(SerialNumber);
    }
    if (SwVer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SwVer);
    }
    if (HwVer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HwVer);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RegMidMO other) {
    if (other == null) {
      return;
    }
    if (other.SerialNumber != 0L) {
      SerialNumber = other.SerialNumber;
    }
    if (other.SwVer.Length != 0) {
      SwVer = other.SwVer;
    }
    if (other.HwVer.Length != 0) {
      HwVer = other.HwVer;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SerialNumber = input.ReadInt64();
          break;
        }
        case 18: {
          SwVer = input.ReadString();
          break;
        }
        case 26: {
          HwVer = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          SerialNumber = input.ReadInt64();
          break;
        }
        case 18: {
          SwVer = input.ReadString();
          break;
        }
        case 26: {
          HwVer = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
