// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EventData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from EventData.proto</summary>
public static partial class EventDataReflection {

  #region Descriptor
  /// <summary>File descriptor for EventData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EventDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9FdmVudERhdGEucHJvdG8iRQoPRXZlbnREYXRhUmVzRFRPEg4KBm9mZnNl",
          "dBgBIAEoBRIMCgR0aW1lGAIgASgFEhQKDHRpbWVfeW1kX2htcxgDIAEoDCLb",
          "AQoHTUlFdmVudBISCgpldmVudF9jb2RlGAEgASgFEhQKDGV2ZW50X3N0YXR1",
          "cxgCIAEoBRITCgtldmVudF9jb3VudBgDIAEoBRISCgpwdl92b2x0YWdlGAQg",
          "ASgFEhQKDGdyaWRfdm9sdGFnZRgFIAEoBRIWCg5ncmlkX2ZyZXF1ZW5jeRgG",
          "IAEoBRISCgpncmlkX3Bvd2VyGAcgASgFEhMKC3RlbXBlcmF0dXJlGAggASgF",
          "Eg0KBW1pX2lkGAkgASgDEhcKD3N0YXJ0X3RpbWVzdGFtcBgKIAEoBSJMCg9F",
          "dmVudERhdGFSZXFEVE8SDgoGb2Zmc2V0GAEgASgFEgwKBHRpbWUYAiABKAUS",
          "GwoJbWlfZXZlbnRzGAMgAygLMgguTUlFdmVudGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::EventDataResDTO), global::EventDataResDTO.Parser, new[]{ "Offset", "Time", "TimeYmdHms" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::MIEvent), global::MIEvent.Parser, new[]{ "EventCode", "EventStatus", "EventCount", "PvVoltage", "GridVoltage", "GridFrequency", "GridPower", "Temperature", "MiId", "StartTimestamp" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EventDataReqDTO), global::EventDataReqDTO.Parser, new[]{ "Offset", "Time", "MiEvents" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EventDataResDTO : pb::IMessage<EventDataResDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EventDataResDTO> _parser = new pb::MessageParser<EventDataResDTO>(() => new EventDataResDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EventDataResDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EventDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EventDataResDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EventDataResDTO(EventDataResDTO other) : this() {
    offset_ = other.offset_;
    time_ = other.time_;
    timeYmdHms_ = other.timeYmdHms_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EventDataResDTO Clone() {
    return new EventDataResDTO(this);
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 1;
  private int offset_;
  /// <summary>
  /// Offset in the response
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Offset {
    get { return offset_; }
    set {
      offset_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private int time_;
  /// <summary>
  /// Timestamp of the response
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  /// <summary>Field number for the "time_ymd_hms" field.</summary>
  public const int TimeYmdHmsFieldNumber = 3;
  private pb::ByteString timeYmdHms_ = pb::ByteString.Empty;
  /// <summary>
  /// Start timestamp in YYYY-MM-DD HH:MM:SS format
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString TimeYmdHms {
    get { return timeYmdHms_; }
    set {
      timeYmdHms_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EventDataResDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EventDataResDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Offset != other.Offset) return false;
    if (Time != other.Time) return false;
    if (TimeYmdHms != other.TimeYmdHms) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Offset != 0) hash ^= Offset.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (TimeYmdHms.Length != 0) hash ^= TimeYmdHms.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Offset != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Time);
    }
    if (TimeYmdHms.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(TimeYmdHms);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Offset != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Time);
    }
    if (TimeYmdHms.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(TimeYmdHms);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Offset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
    }
    if (TimeYmdHms.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(TimeYmdHms);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EventDataResDTO other) {
    if (other == null) {
      return;
    }
    if (other.Offset != 0) {
      Offset = other.Offset;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    if (other.TimeYmdHms.Length != 0) {
      TimeYmdHms = other.TimeYmdHms;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Offset = input.ReadInt32();
          break;
        }
        case 16: {
          Time = input.ReadInt32();
          break;
        }
        case 26: {
          TimeYmdHms = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Offset = input.ReadInt32();
          break;
        }
        case 16: {
          Time = input.ReadInt32();
          break;
        }
        case 26: {
          TimeYmdHms = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class MIEvent : pb::IMessage<MIEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MIEvent> _parser = new pb::MessageParser<MIEvent>(() => new MIEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MIEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EventDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MIEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MIEvent(MIEvent other) : this() {
    eventCode_ = other.eventCode_;
    eventStatus_ = other.eventStatus_;
    eventCount_ = other.eventCount_;
    pvVoltage_ = other.pvVoltage_;
    gridVoltage_ = other.gridVoltage_;
    gridFrequency_ = other.gridFrequency_;
    gridPower_ = other.gridPower_;
    temperature_ = other.temperature_;
    miId_ = other.miId_;
    startTimestamp_ = other.startTimestamp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MIEvent Clone() {
    return new MIEvent(this);
  }

  /// <summary>Field number for the "event_code" field.</summary>
  public const int EventCodeFieldNumber = 1;
  private int eventCode_;
  /// <summary>
  /// Event code
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int EventCode {
    get { return eventCode_; }
    set {
      eventCode_ = value;
    }
  }

  /// <summary>Field number for the "event_status" field.</summary>
  public const int EventStatusFieldNumber = 2;
  private int eventStatus_;
  /// <summary>
  /// Event status
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int EventStatus {
    get { return eventStatus_; }
    set {
      eventStatus_ = value;
    }
  }

  /// <summary>Field number for the "event_count" field.</summary>
  public const int EventCountFieldNumber = 3;
  private int eventCount_;
  /// <summary>
  /// Event count
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int EventCount {
    get { return eventCount_; }
    set {
      eventCount_ = value;
    }
  }

  /// <summary>Field number for the "pv_voltage" field.</summary>
  public const int PvVoltageFieldNumber = 4;
  private int pvVoltage_;
  /// <summary>
  /// PV voltage
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PvVoltage {
    get { return pvVoltage_; }
    set {
      pvVoltage_ = value;
    }
  }

  /// <summary>Field number for the "grid_voltage" field.</summary>
  public const int GridVoltageFieldNumber = 5;
  private int gridVoltage_;
  /// <summary>
  /// Grid voltage
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GridVoltage {
    get { return gridVoltage_; }
    set {
      gridVoltage_ = value;
    }
  }

  /// <summary>Field number for the "grid_frequency" field.</summary>
  public const int GridFrequencyFieldNumber = 6;
  private int gridFrequency_;
  /// <summary>
  /// Grid frequency
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GridFrequency {
    get { return gridFrequency_; }
    set {
      gridFrequency_ = value;
    }
  }

  /// <summary>Field number for the "grid_power" field.</summary>
  public const int GridPowerFieldNumber = 7;
  private int gridPower_;
  /// <summary>
  /// Grid power
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GridPower {
    get { return gridPower_; }
    set {
      gridPower_ = value;
    }
  }

  /// <summary>Field number for the "temperature" field.</summary>
  public const int TemperatureFieldNumber = 8;
  private int temperature_;
  /// <summary>
  /// Temperature
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Temperature {
    get { return temperature_; }
    set {
      temperature_ = value;
    }
  }

  /// <summary>Field number for the "mi_id" field.</summary>
  public const int MiIdFieldNumber = 9;
  private long miId_;
  /// <summary>
  /// Meter Interface (MI) ID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long MiId {
    get { return miId_; }
    set {
      miId_ = value;
    }
  }

  /// <summary>Field number for the "start_timestamp" field.</summary>
  public const int StartTimestampFieldNumber = 10;
  private int startTimestamp_;
  /// <summary>
  /// Start timestamp
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int StartTimestamp {
    get { return startTimestamp_; }
    set {
      startTimestamp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MIEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MIEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EventCode != other.EventCode) return false;
    if (EventStatus != other.EventStatus) return false;
    if (EventCount != other.EventCount) return false;
    if (PvVoltage != other.PvVoltage) return false;
    if (GridVoltage != other.GridVoltage) return false;
    if (GridFrequency != other.GridFrequency) return false;
    if (GridPower != other.GridPower) return false;
    if (Temperature != other.Temperature) return false;
    if (MiId != other.MiId) return false;
    if (StartTimestamp != other.StartTimestamp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EventCode != 0) hash ^= EventCode.GetHashCode();
    if (EventStatus != 0) hash ^= EventStatus.GetHashCode();
    if (EventCount != 0) hash ^= EventCount.GetHashCode();
    if (PvVoltage != 0) hash ^= PvVoltage.GetHashCode();
    if (GridVoltage != 0) hash ^= GridVoltage.GetHashCode();
    if (GridFrequency != 0) hash ^= GridFrequency.GetHashCode();
    if (GridPower != 0) hash ^= GridPower.GetHashCode();
    if (Temperature != 0) hash ^= Temperature.GetHashCode();
    if (MiId != 0L) hash ^= MiId.GetHashCode();
    if (StartTimestamp != 0) hash ^= StartTimestamp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EventCode != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(EventCode);
    }
    if (EventStatus != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(EventStatus);
    }
    if (EventCount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(EventCount);
    }
    if (PvVoltage != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(PvVoltage);
    }
    if (GridVoltage != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(GridVoltage);
    }
    if (GridFrequency != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(GridFrequency);
    }
    if (GridPower != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(GridPower);
    }
    if (Temperature != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(Temperature);
    }
    if (MiId != 0L) {
      output.WriteRawTag(72);
      output.WriteInt64(MiId);
    }
    if (StartTimestamp != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(StartTimestamp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EventCode != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(EventCode);
    }
    if (EventStatus != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(EventStatus);
    }
    if (EventCount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(EventCount);
    }
    if (PvVoltage != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(PvVoltage);
    }
    if (GridVoltage != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(GridVoltage);
    }
    if (GridFrequency != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(GridFrequency);
    }
    if (GridPower != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(GridPower);
    }
    if (Temperature != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(Temperature);
    }
    if (MiId != 0L) {
      output.WriteRawTag(72);
      output.WriteInt64(MiId);
    }
    if (StartTimestamp != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(StartTimestamp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EventCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(EventCode);
    }
    if (EventStatus != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(EventStatus);
    }
    if (EventCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(EventCount);
    }
    if (PvVoltage != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PvVoltage);
    }
    if (GridVoltage != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridVoltage);
    }
    if (GridFrequency != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridFrequency);
    }
    if (GridPower != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridPower);
    }
    if (Temperature != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Temperature);
    }
    if (MiId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(MiId);
    }
    if (StartTimestamp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartTimestamp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MIEvent other) {
    if (other == null) {
      return;
    }
    if (other.EventCode != 0) {
      EventCode = other.EventCode;
    }
    if (other.EventStatus != 0) {
      EventStatus = other.EventStatus;
    }
    if (other.EventCount != 0) {
      EventCount = other.EventCount;
    }
    if (other.PvVoltage != 0) {
      PvVoltage = other.PvVoltage;
    }
    if (other.GridVoltage != 0) {
      GridVoltage = other.GridVoltage;
    }
    if (other.GridFrequency != 0) {
      GridFrequency = other.GridFrequency;
    }
    if (other.GridPower != 0) {
      GridPower = other.GridPower;
    }
    if (other.Temperature != 0) {
      Temperature = other.Temperature;
    }
    if (other.MiId != 0L) {
      MiId = other.MiId;
    }
    if (other.StartTimestamp != 0) {
      StartTimestamp = other.StartTimestamp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EventCode = input.ReadInt32();
          break;
        }
        case 16: {
          EventStatus = input.ReadInt32();
          break;
        }
        case 24: {
          EventCount = input.ReadInt32();
          break;
        }
        case 32: {
          PvVoltage = input.ReadInt32();
          break;
        }
        case 40: {
          GridVoltage = input.ReadInt32();
          break;
        }
        case 48: {
          GridFrequency = input.ReadInt32();
          break;
        }
        case 56: {
          GridPower = input.ReadInt32();
          break;
        }
        case 64: {
          Temperature = input.ReadInt32();
          break;
        }
        case 72: {
          MiId = input.ReadInt64();
          break;
        }
        case 80: {
          StartTimestamp = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          EventCode = input.ReadInt32();
          break;
        }
        case 16: {
          EventStatus = input.ReadInt32();
          break;
        }
        case 24: {
          EventCount = input.ReadInt32();
          break;
        }
        case 32: {
          PvVoltage = input.ReadInt32();
          break;
        }
        case 40: {
          GridVoltage = input.ReadInt32();
          break;
        }
        case 48: {
          GridFrequency = input.ReadInt32();
          break;
        }
        case 56: {
          GridPower = input.ReadInt32();
          break;
        }
        case 64: {
          Temperature = input.ReadInt32();
          break;
        }
        case 72: {
          MiId = input.ReadInt64();
          break;
        }
        case 80: {
          StartTimestamp = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EventDataReqDTO : pb::IMessage<EventDataReqDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EventDataReqDTO> _parser = new pb::MessageParser<EventDataReqDTO>(() => new EventDataReqDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EventDataReqDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EventDataReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EventDataReqDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EventDataReqDTO(EventDataReqDTO other) : this() {
    offset_ = other.offset_;
    time_ = other.time_;
    miEvents_ = other.miEvents_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EventDataReqDTO Clone() {
    return new EventDataReqDTO(this);
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 1;
  private int offset_;
  /// <summary>
  /// Offset in the request
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Offset {
    get { return offset_; }
    set {
      offset_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private int time_;
  /// <summary>
  /// Timestamp of the request
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  /// <summary>Field number for the "mi_events" field.</summary>
  public const int MiEventsFieldNumber = 3;
  private static readonly pb::FieldCodec<global::MIEvent> _repeated_miEvents_codec
      = pb::FieldCodec.ForMessage(26, global::MIEvent.Parser);
  private readonly pbc::RepeatedField<global::MIEvent> miEvents_ = new pbc::RepeatedField<global::MIEvent>();
  /// <summary>
  /// List of MI (Meter Interface) events
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::MIEvent> MiEvents {
    get { return miEvents_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EventDataReqDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EventDataReqDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Offset != other.Offset) return false;
    if (Time != other.Time) return false;
    if(!miEvents_.Equals(other.miEvents_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Offset != 0) hash ^= Offset.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    hash ^= miEvents_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Offset != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Time);
    }
    miEvents_.WriteTo(output, _repeated_miEvents_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Offset != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Time);
    }
    miEvents_.WriteTo(ref output, _repeated_miEvents_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Offset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
    }
    size += miEvents_.CalculateSize(_repeated_miEvents_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EventDataReqDTO other) {
    if (other == null) {
      return;
    }
    if (other.Offset != 0) {
      Offset = other.Offset;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    miEvents_.Add(other.miEvents_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Offset = input.ReadInt32();
          break;
        }
        case 16: {
          Time = input.ReadInt32();
          break;
        }
        case 26: {
          miEvents_.AddEntriesFrom(input, _repeated_miEvents_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Offset = input.ReadInt32();
          break;
        }
        case 16: {
          Time = input.ReadInt32();
          break;
        }
        case 26: {
          miEvents_.AddEntriesFrom(ref input, _repeated_miEvents_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
