// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetConfig.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetConfig.proto</summary>
public static partial class GetConfigReflection {

  #region Descriptor
  /// <summary>File descriptor for GetConfig.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetConfigReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9HZXRDb25maWcucHJvdG8iLwoPR2V0Q29uZmlnUmVzRFRPEg4KBm9mZnNl",
          "dBgBIAEoBRIMCgR0aW1lGAIgASgNIskKCg9HZXRDb25maWdSZXFEVE8SFgoO",
          "cmVxdWVzdF9vZmZzZXQYASABKAUSFAoMcmVxdWVzdF90aW1lGAIgASgNEhUK",
          "DWxvY2tfcGFzc3dvcmQYAyABKAUSEQoJbG9ja190aW1lGAQgASgFEhsKE2xp",
          "bWl0X3Bvd2VyX215cG93ZXIYBSABKAUSHAoUemVyb19leHBvcnRfNDMzX2Fk",
          "ZHIYBiABKAUSGgoSemVyb19leHBvcnRfZW5hYmxlGAcgASgFEhYKDm5ldG1v",
          "ZGVfc2VsZWN0GAggASgFEhYKDmNoYW5uZWxfc2VsZWN0GAkgASgFEhgKEHNl",
          "cnZlcl9zZW5kX3RpbWUYCiABKAUSEQoJd2lmaV9yc3NpGAsgASgFEhIKCnNl",
          "cnZlcnBvcnQYDCABKAUSDwoHYXBuX3NldBgNIAEoCRISCgptZXRlcl9raW5k",
          "GA4gASgJEhcKD21ldGVyX2ludGVyZmFjZRgPIAEoCRIRCgl3aWZpX3NzaWQY",
          "ECABKAkSFQoNd2lmaV9wYXNzd29yZBgRIAEoCRIaChJzZXJ2ZXJfZG9tYWlu",
          "X25hbWUYEiABKAkSEAoIaW52X3R5cGUYEyABKAUSDgoGZHR1X3NuGBQgASgJ",
          "EhQKDGFjY2Vzc19tb2RlbBgVIAEoBRINCgVtYWNfMBgWIAEoBRINCgVtYWNf",
          "MRgXIAEoBRINCgVtYWNfMhgYIAEoBRINCgVtYWNfMxgZIAEoBRITCgtkaGNw",
          "X3N3aXRjaBgaIAEoBRIRCglpcF9hZGRyXzAYGyABKAUSEQoJaXBfYWRkcl8x",
          "GBwgASgFEhEKCWlwX2FkZHJfMhgdIAEoBRIRCglpcF9hZGRyXzMYHiABKAUS",
          "FQoNc3VibmV0X21hc2tfMBgfIAEoBRIVCg1zdWJuZXRfbWFza18xGCAgASgF",
          "EhUKDXN1Ym5ldF9tYXNrXzIYISABKAUSFQoNc3VibmV0X21hc2tfMxgiIAEo",
          "BRIZChFkZWZhdWx0X2dhdGV3YXlfMBgjIAEoBRIZChFkZWZhdWx0X2dhdGV3",
          "YXlfMRgkIAEoBRIZChFkZWZhdWx0X2dhdGV3YXlfMhglIAEoBRIZChFkZWZh",
          "dWx0X2dhdGV3YXlfMxgmIAEoBRIOCgZrYV9udWIYJyABKAkSEAoIYXBuX25h",
          "bWUYKCABKAkSFAoMYXBuX3Bhc3N3b3JkGCkgASgJEhoKEnN1YjFnX3N3ZWVw",
          "X3N3aXRjaBgqIAEoBRIaChJzdWIxZ193b3JrX2NoYW5uZWwYKyABKAUSEwoL",
          "Y2FibGVfZG5zXzAYLCABKAUSEwoLY2FibGVfZG5zXzEYLSABKAUSEwoLY2Fi",
          "bGVfZG5zXzIYLiABKAUSEwoLY2FibGVfZG5zXzMYLyABKAUSFgoOd2lmaV9p",
          "cF9hZGRyXzAYMCABKAUSFgoOd2lmaV9pcF9hZGRyXzEYMSABKAUSFgoOd2lm",
          "aV9pcF9hZGRyXzIYMiABKAUSFgoOd2lmaV9pcF9hZGRyXzMYMyABKAUSDQoF",
          "bWFjXzQYNCABKAUSDQoFbWFjXzUYNSABKAUSEgoKd2lmaV9tYWNfMBg2IAEo",
          "BRISCgp3aWZpX21hY18xGDcgASgFEhIKCndpZmlfbWFjXzIYOCABKAUSEgoK",
          "d2lmaV9tYWNfMxg5IAEoBRISCgp3aWZpX21hY180GDogASgFEhIKCndpZmlf",
          "bWFjXzUYOyABKAUSEQoJZ3Byc19pbWVpGDwgASgJEhMKC2R0dV9hcF9zc2lk",
          "GD0gASgJEhMKC2R0dV9hcF9wYXNzGD4gASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetConfigResDTO), global::GetConfigResDTO.Parser, new[]{ "Offset", "Time" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GetConfigReqDTO), global::GetConfigReqDTO.Parser, new[]{ "RequestOffset", "RequestTime", "LockPassword", "LockTime", "LimitPowerMypower", "ZeroExport433Addr", "ZeroExportEnable", "NetmodeSelect", "ChannelSelect", "ServerSendTime", "WifiRssi", "Serverport", "ApnSet", "MeterKind", "MeterInterface", "WifiSsid", "WifiPassword", "ServerDomainName", "InvType", "DtuSn", "AccessModel", "Mac0", "Mac1", "Mac2", "Mac3", "DhcpSwitch", "IpAddr0", "IpAddr1", "IpAddr2", "IpAddr3", "SubnetMask0", "SubnetMask1", "SubnetMask2", "SubnetMask3", "DefaultGateway0", "DefaultGateway1", "DefaultGateway2", "DefaultGateway3", "KaNub", "ApnName", "ApnPassword", "Sub1GSweepSwitch", "Sub1GWorkChannel", "CableDns0", "CableDns1", "CableDns2", "CableDns3", "WifiIpAddr0", "WifiIpAddr1", "WifiIpAddr2", "WifiIpAddr3", "Mac4", "Mac5", "WifiMac0", "WifiMac1", "WifiMac2", "WifiMac3", "WifiMac4", "WifiMac5", "GprsImei", "DtuApSsid", "DtuApPass" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GetConfigResDTO : pb::IMessage<GetConfigResDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetConfigResDTO> _parser = new pb::MessageParser<GetConfigResDTO>(() => new GetConfigResDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetConfigResDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetConfigReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetConfigResDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetConfigResDTO(GetConfigResDTO other) : this() {
    offset_ = other.offset_;
    time_ = other.time_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetConfigResDTO Clone() {
    return new GetConfigResDTO(this);
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 1;
  private int offset_;
  /// <summary>
  /// Offset in the response
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Offset {
    get { return offset_; }
    set {
      offset_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private uint time_;
  /// <summary>
  /// Timestamp of the response
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetConfigResDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetConfigResDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Offset != other.Offset) return false;
    if (Time != other.Time) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Offset != 0) hash ^= Offset.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Offset != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Offset != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Offset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetConfigResDTO other) {
    if (other == null) {
      return;
    }
    if (other.Offset != 0) {
      Offset = other.Offset;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Offset = input.ReadInt32();
          break;
        }
        case 16: {
          Time = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Offset = input.ReadInt32();
          break;
        }
        case 16: {
          Time = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GetConfigReqDTO : pb::IMessage<GetConfigReqDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetConfigReqDTO> _parser = new pb::MessageParser<GetConfigReqDTO>(() => new GetConfigReqDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetConfigReqDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetConfigReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetConfigReqDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetConfigReqDTO(GetConfigReqDTO other) : this() {
    requestOffset_ = other.requestOffset_;
    requestTime_ = other.requestTime_;
    lockPassword_ = other.lockPassword_;
    lockTime_ = other.lockTime_;
    limitPowerMypower_ = other.limitPowerMypower_;
    zeroExport433Addr_ = other.zeroExport433Addr_;
    zeroExportEnable_ = other.zeroExportEnable_;
    netmodeSelect_ = other.netmodeSelect_;
    channelSelect_ = other.channelSelect_;
    serverSendTime_ = other.serverSendTime_;
    wifiRssi_ = other.wifiRssi_;
    serverport_ = other.serverport_;
    apnSet_ = other.apnSet_;
    meterKind_ = other.meterKind_;
    meterInterface_ = other.meterInterface_;
    wifiSsid_ = other.wifiSsid_;
    wifiPassword_ = other.wifiPassword_;
    serverDomainName_ = other.serverDomainName_;
    invType_ = other.invType_;
    dtuSn_ = other.dtuSn_;
    accessModel_ = other.accessModel_;
    mac0_ = other.mac0_;
    mac1_ = other.mac1_;
    mac2_ = other.mac2_;
    mac3_ = other.mac3_;
    dhcpSwitch_ = other.dhcpSwitch_;
    ipAddr0_ = other.ipAddr0_;
    ipAddr1_ = other.ipAddr1_;
    ipAddr2_ = other.ipAddr2_;
    ipAddr3_ = other.ipAddr3_;
    subnetMask0_ = other.subnetMask0_;
    subnetMask1_ = other.subnetMask1_;
    subnetMask2_ = other.subnetMask2_;
    subnetMask3_ = other.subnetMask3_;
    defaultGateway0_ = other.defaultGateway0_;
    defaultGateway1_ = other.defaultGateway1_;
    defaultGateway2_ = other.defaultGateway2_;
    defaultGateway3_ = other.defaultGateway3_;
    kaNub_ = other.kaNub_;
    apnName_ = other.apnName_;
    apnPassword_ = other.apnPassword_;
    sub1GSweepSwitch_ = other.sub1GSweepSwitch_;
    sub1GWorkChannel_ = other.sub1GWorkChannel_;
    cableDns0_ = other.cableDns0_;
    cableDns1_ = other.cableDns1_;
    cableDns2_ = other.cableDns2_;
    cableDns3_ = other.cableDns3_;
    wifiIpAddr0_ = other.wifiIpAddr0_;
    wifiIpAddr1_ = other.wifiIpAddr1_;
    wifiIpAddr2_ = other.wifiIpAddr2_;
    wifiIpAddr3_ = other.wifiIpAddr3_;
    mac4_ = other.mac4_;
    mac5_ = other.mac5_;
    wifiMac0_ = other.wifiMac0_;
    wifiMac1_ = other.wifiMac1_;
    wifiMac2_ = other.wifiMac2_;
    wifiMac3_ = other.wifiMac3_;
    wifiMac4_ = other.wifiMac4_;
    wifiMac5_ = other.wifiMac5_;
    gprsImei_ = other.gprsImei_;
    dtuApSsid_ = other.dtuApSsid_;
    dtuApPass_ = other.dtuApPass_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetConfigReqDTO Clone() {
    return new GetConfigReqDTO(this);
  }

  /// <summary>Field number for the "request_offset" field.</summary>
  public const int RequestOffsetFieldNumber = 1;
  private int requestOffset_;
  /// <summary>
  /// Offset in the request
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RequestOffset {
    get { return requestOffset_; }
    set {
      requestOffset_ = value;
    }
  }

  /// <summary>Field number for the "request_time" field.</summary>
  public const int RequestTimeFieldNumber = 2;
  private uint requestTime_;
  /// <summary>
  /// Timestamp of the request
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RequestTime {
    get { return requestTime_; }
    set {
      requestTime_ = value;
    }
  }

  /// <summary>Field number for the "lock_password" field.</summary>
  public const int LockPasswordFieldNumber = 3;
  private int lockPassword_;
  /// <summary>
  /// Lock password
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LockPassword {
    get { return lockPassword_; }
    set {
      lockPassword_ = value;
    }
  }

  /// <summary>Field number for the "lock_time" field.</summary>
  public const int LockTimeFieldNumber = 4;
  private int lockTime_;
  /// <summary>
  /// Lock time
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LockTime {
    get { return lockTime_; }
    set {
      lockTime_ = value;
    }
  }

  /// <summary>Field number for the "limit_power_mypower" field.</summary>
  public const int LimitPowerMypowerFieldNumber = 5;
  private int limitPowerMypower_;
  /// <summary>
  /// Limit power mypower
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LimitPowerMypower {
    get { return limitPowerMypower_; }
    set {
      limitPowerMypower_ = value;
    }
  }

  /// <summary>Field number for the "zero_export_433_addr" field.</summary>
  public const int ZeroExport433AddrFieldNumber = 6;
  private int zeroExport433Addr_;
  /// <summary>
  /// Zero export 433 address
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ZeroExport433Addr {
    get { return zeroExport433Addr_; }
    set {
      zeroExport433Addr_ = value;
    }
  }

  /// <summary>Field number for the "zero_export_enable" field.</summary>
  public const int ZeroExportEnableFieldNumber = 7;
  private int zeroExportEnable_;
  /// <summary>
  /// Zero export enable
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ZeroExportEnable {
    get { return zeroExportEnable_; }
    set {
      zeroExportEnable_ = value;
    }
  }

  /// <summary>Field number for the "netmode_select" field.</summary>
  public const int NetmodeSelectFieldNumber = 8;
  private int netmodeSelect_;
  /// <summary>
  /// Netmode select
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NetmodeSelect {
    get { return netmodeSelect_; }
    set {
      netmodeSelect_ = value;
    }
  }

  /// <summary>Field number for the "channel_select" field.</summary>
  public const int ChannelSelectFieldNumber = 9;
  private int channelSelect_;
  /// <summary>
  /// Channel select
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ChannelSelect {
    get { return channelSelect_; }
    set {
      channelSelect_ = value;
    }
  }

  /// <summary>Field number for the "server_send_time" field.</summary>
  public const int ServerSendTimeFieldNumber = 10;
  private int serverSendTime_;
  /// <summary>
  /// Server send time
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ServerSendTime {
    get { return serverSendTime_; }
    set {
      serverSendTime_ = value;
    }
  }

  /// <summary>Field number for the "wifi_rssi" field.</summary>
  public const int WifiRssiFieldNumber = 11;
  private int wifiRssi_;
  /// <summary>
  /// Wifi RSSI
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WifiRssi {
    get { return wifiRssi_; }
    set {
      wifiRssi_ = value;
    }
  }

  /// <summary>Field number for the "serverport" field.</summary>
  public const int ServerportFieldNumber = 12;
  private int serverport_;
  /// <summary>
  /// Server port
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Serverport {
    get { return serverport_; }
    set {
      serverport_ = value;
    }
  }

  /// <summary>Field number for the "apn_set" field.</summary>
  public const int ApnSetFieldNumber = 13;
  private string apnSet_ = "";
  /// <summary>
  /// Access Point Name (APN) set
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ApnSet {
    get { return apnSet_; }
    set {
      apnSet_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "meter_kind" field.</summary>
  public const int MeterKindFieldNumber = 14;
  private string meterKind_ = "";
  /// <summary>
  /// Meter kind
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string MeterKind {
    get { return meterKind_; }
    set {
      meterKind_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "meter_interface" field.</summary>
  public const int MeterInterfaceFieldNumber = 15;
  private string meterInterface_ = "";
  /// <summary>
  /// Meter interface
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string MeterInterface {
    get { return meterInterface_; }
    set {
      meterInterface_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "wifi_ssid" field.</summary>
  public const int WifiSsidFieldNumber = 16;
  private string wifiSsid_ = "";
  /// <summary>
  /// Wifi SSID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string WifiSsid {
    get { return wifiSsid_; }
    set {
      wifiSsid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "wifi_password" field.</summary>
  public const int WifiPasswordFieldNumber = 17;
  private string wifiPassword_ = "";
  /// <summary>
  /// Wifi password
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string WifiPassword {
    get { return wifiPassword_; }
    set {
      wifiPassword_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "server_domain_name" field.</summary>
  public const int ServerDomainNameFieldNumber = 18;
  private string serverDomainName_ = "";
  /// <summary>
  /// Server domain name
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ServerDomainName {
    get { return serverDomainName_; }
    set {
      serverDomainName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "inv_type" field.</summary>
  public const int InvTypeFieldNumber = 19;
  private int invType_;
  /// <summary>
  /// Inverter type
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int InvType {
    get { return invType_; }
    set {
      invType_ = value;
    }
  }

  /// <summary>Field number for the "dtu_sn" field.</summary>
  public const int DtuSnFieldNumber = 20;
  private string dtuSn_ = "";
  /// <summary>
  /// DTU serial number
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DtuSn {
    get { return dtuSn_; }
    set {
      dtuSn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "access_model" field.</summary>
  public const int AccessModelFieldNumber = 21;
  private int accessModel_;
  /// <summary>
  /// Access model
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int AccessModel {
    get { return accessModel_; }
    set {
      accessModel_ = value;
    }
  }

  /// <summary>Field number for the "mac_0" field.</summary>
  public const int Mac0FieldNumber = 22;
  private int mac0_;
  /// <summary>
  /// MAC address byte 0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Mac0 {
    get { return mac0_; }
    set {
      mac0_ = value;
    }
  }

  /// <summary>Field number for the "mac_1" field.</summary>
  public const int Mac1FieldNumber = 23;
  private int mac1_;
  /// <summary>
  /// MAC address byte 1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Mac1 {
    get { return mac1_; }
    set {
      mac1_ = value;
    }
  }

  /// <summary>Field number for the "mac_2" field.</summary>
  public const int Mac2FieldNumber = 24;
  private int mac2_;
  /// <summary>
  /// MAC address byte 2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Mac2 {
    get { return mac2_; }
    set {
      mac2_ = value;
    }
  }

  /// <summary>Field number for the "mac_3" field.</summary>
  public const int Mac3FieldNumber = 25;
  private int mac3_;
  /// <summary>
  /// MAC address byte 3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Mac3 {
    get { return mac3_; }
    set {
      mac3_ = value;
    }
  }

  /// <summary>Field number for the "dhcp_switch" field.</summary>
  public const int DhcpSwitchFieldNumber = 26;
  private int dhcpSwitch_;
  /// <summary>
  /// DHCP switch
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int DhcpSwitch {
    get { return dhcpSwitch_; }
    set {
      dhcpSwitch_ = value;
    }
  }

  /// <summary>Field number for the "ip_addr_0" field.</summary>
  public const int IpAddr0FieldNumber = 27;
  private int ipAddr0_;
  /// <summary>
  /// IP address byte 0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IpAddr0 {
    get { return ipAddr0_; }
    set {
      ipAddr0_ = value;
    }
  }

  /// <summary>Field number for the "ip_addr_1" field.</summary>
  public const int IpAddr1FieldNumber = 28;
  private int ipAddr1_;
  /// <summary>
  /// IP address byte 1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IpAddr1 {
    get { return ipAddr1_; }
    set {
      ipAddr1_ = value;
    }
  }

  /// <summary>Field number for the "ip_addr_2" field.</summary>
  public const int IpAddr2FieldNumber = 29;
  private int ipAddr2_;
  /// <summary>
  /// IP address byte 2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IpAddr2 {
    get { return ipAddr2_; }
    set {
      ipAddr2_ = value;
    }
  }

  /// <summary>Field number for the "ip_addr_3" field.</summary>
  public const int IpAddr3FieldNumber = 30;
  private int ipAddr3_;
  /// <summary>
  /// IP address byte 3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IpAddr3 {
    get { return ipAddr3_; }
    set {
      ipAddr3_ = value;
    }
  }

  /// <summary>Field number for the "subnet_mask_0" field.</summary>
  public const int SubnetMask0FieldNumber = 31;
  private int subnetMask0_;
  /// <summary>
  /// Subnet mask byte 0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SubnetMask0 {
    get { return subnetMask0_; }
    set {
      subnetMask0_ = value;
    }
  }

  /// <summary>Field number for the "subnet_mask_1" field.</summary>
  public const int SubnetMask1FieldNumber = 32;
  private int subnetMask1_;
  /// <summary>
  /// Subnet mask byte 1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SubnetMask1 {
    get { return subnetMask1_; }
    set {
      subnetMask1_ = value;
    }
  }

  /// <summary>Field number for the "subnet_mask_2" field.</summary>
  public const int SubnetMask2FieldNumber = 33;
  private int subnetMask2_;
  /// <summary>
  /// Subnet mask byte 2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SubnetMask2 {
    get { return subnetMask2_; }
    set {
      subnetMask2_ = value;
    }
  }

  /// <summary>Field number for the "subnet_mask_3" field.</summary>
  public const int SubnetMask3FieldNumber = 34;
  private int subnetMask3_;
  /// <summary>
  /// Subnet mask byte 3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SubnetMask3 {
    get { return subnetMask3_; }
    set {
      subnetMask3_ = value;
    }
  }

  /// <summary>Field number for the "default_gateway_0" field.</summary>
  public const int DefaultGateway0FieldNumber = 35;
  private int defaultGateway0_;
  /// <summary>
  /// Default gateway byte 0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int DefaultGateway0 {
    get { return defaultGateway0_; }
    set {
      defaultGateway0_ = value;
    }
  }

  /// <summary>Field number for the "default_gateway_1" field.</summary>
  public const int DefaultGateway1FieldNumber = 36;
  private int defaultGateway1_;
  /// <summary>
  /// Default gateway byte 1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int DefaultGateway1 {
    get { return defaultGateway1_; }
    set {
      defaultGateway1_ = value;
    }
  }

  /// <summary>Field number for the "default_gateway_2" field.</summary>
  public const int DefaultGateway2FieldNumber = 37;
  private int defaultGateway2_;
  /// <summary>
  /// Default gateway byte 2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int DefaultGateway2 {
    get { return defaultGateway2_; }
    set {
      defaultGateway2_ = value;
    }
  }

  /// <summary>Field number for the "default_gateway_3" field.</summary>
  public const int DefaultGateway3FieldNumber = 38;
  private int defaultGateway3_;
  /// <summary>
  /// Default gateway byte 3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int DefaultGateway3 {
    get { return defaultGateway3_; }
    set {
      defaultGateway3_ = value;
    }
  }

  /// <summary>Field number for the "ka_nub" field.</summary>
  public const int KaNubFieldNumber = 39;
  private string kaNub_ = "";
  /// <summary>
  /// KA number
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string KaNub {
    get { return kaNub_; }
    set {
      kaNub_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "apn_name" field.</summary>
  public const int ApnNameFieldNumber = 40;
  private string apnName_ = "";
  /// <summary>
  /// APN name
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ApnName {
    get { return apnName_; }
    set {
      apnName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "apn_password" field.</summary>
  public const int ApnPasswordFieldNumber = 41;
  private string apnPassword_ = "";
  /// <summary>
  /// APN password
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ApnPassword {
    get { return apnPassword_; }
    set {
      apnPassword_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sub1g_sweep_switch" field.</summary>
  public const int Sub1GSweepSwitchFieldNumber = 42;
  private int sub1GSweepSwitch_;
  /// <summary>
  /// Sub1G sweep switch
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Sub1GSweepSwitch {
    get { return sub1GSweepSwitch_; }
    set {
      sub1GSweepSwitch_ = value;
    }
  }

  /// <summary>Field number for the "sub1g_work_channel" field.</summary>
  public const int Sub1GWorkChannelFieldNumber = 43;
  private int sub1GWorkChannel_;
  /// <summary>
  /// Sub1G work channel
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Sub1GWorkChannel {
    get { return sub1GWorkChannel_; }
    set {
      sub1GWorkChannel_ = value;
    }
  }

  /// <summary>Field number for the "cable_dns_0" field.</summary>
  public const int CableDns0FieldNumber = 44;
  private int cableDns0_;
  /// <summary>
  /// Cable DNS byte 0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CableDns0 {
    get { return cableDns0_; }
    set {
      cableDns0_ = value;
    }
  }

  /// <summary>Field number for the "cable_dns_1" field.</summary>
  public const int CableDns1FieldNumber = 45;
  private int cableDns1_;
  /// <summary>
  /// Cable DNS byte 1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CableDns1 {
    get { return cableDns1_; }
    set {
      cableDns1_ = value;
    }
  }

  /// <summary>Field number for the "cable_dns_2" field.</summary>
  public const int CableDns2FieldNumber = 46;
  private int cableDns2_;
  /// <summary>
  /// Cable DNS byte 2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CableDns2 {
    get { return cableDns2_; }
    set {
      cableDns2_ = value;
    }
  }

  /// <summary>Field number for the "cable_dns_3" field.</summary>
  public const int CableDns3FieldNumber = 47;
  private int cableDns3_;
  /// <summary>
  /// Cable DNS byte 3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CableDns3 {
    get { return cableDns3_; }
    set {
      cableDns3_ = value;
    }
  }

  /// <summary>Field number for the "wifi_ip_addr_0" field.</summary>
  public const int WifiIpAddr0FieldNumber = 48;
  private int wifiIpAddr0_;
  /// <summary>
  /// Wifi IP address byte 0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WifiIpAddr0 {
    get { return wifiIpAddr0_; }
    set {
      wifiIpAddr0_ = value;
    }
  }

  /// <summary>Field number for the "wifi_ip_addr_1" field.</summary>
  public const int WifiIpAddr1FieldNumber = 49;
  private int wifiIpAddr1_;
  /// <summary>
  /// Wifi IP address byte 1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WifiIpAddr1 {
    get { return wifiIpAddr1_; }
    set {
      wifiIpAddr1_ = value;
    }
  }

  /// <summary>Field number for the "wifi_ip_addr_2" field.</summary>
  public const int WifiIpAddr2FieldNumber = 50;
  private int wifiIpAddr2_;
  /// <summary>
  /// Wifi IP address byte 2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WifiIpAddr2 {
    get { return wifiIpAddr2_; }
    set {
      wifiIpAddr2_ = value;
    }
  }

  /// <summary>Field number for the "wifi_ip_addr_3" field.</summary>
  public const int WifiIpAddr3FieldNumber = 51;
  private int wifiIpAddr3_;
  /// <summary>
  /// Wifi IP address byte 3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WifiIpAddr3 {
    get { return wifiIpAddr3_; }
    set {
      wifiIpAddr3_ = value;
    }
  }

  /// <summary>Field number for the "mac_4" field.</summary>
  public const int Mac4FieldNumber = 52;
  private int mac4_;
  /// <summary>
  /// MAC address byte 4
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Mac4 {
    get { return mac4_; }
    set {
      mac4_ = value;
    }
  }

  /// <summary>Field number for the "mac_5" field.</summary>
  public const int Mac5FieldNumber = 53;
  private int mac5_;
  /// <summary>
  /// MAC address byte 5
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Mac5 {
    get { return mac5_; }
    set {
      mac5_ = value;
    }
  }

  /// <summary>Field number for the "wifi_mac_0" field.</summary>
  public const int WifiMac0FieldNumber = 54;
  private int wifiMac0_;
  /// <summary>
  /// Wifi MAC address byte 0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WifiMac0 {
    get { return wifiMac0_; }
    set {
      wifiMac0_ = value;
    }
  }

  /// <summary>Field number for the "wifi_mac_1" field.</summary>
  public const int WifiMac1FieldNumber = 55;
  private int wifiMac1_;
  /// <summary>
  /// Wifi MAC address byte 1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WifiMac1 {
    get { return wifiMac1_; }
    set {
      wifiMac1_ = value;
    }
  }

  /// <summary>Field number for the "wifi_mac_2" field.</summary>
  public const int WifiMac2FieldNumber = 56;
  private int wifiMac2_;
  /// <summary>
  /// Wifi MAC address byte 2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WifiMac2 {
    get { return wifiMac2_; }
    set {
      wifiMac2_ = value;
    }
  }

  /// <summary>Field number for the "wifi_mac_3" field.</summary>
  public const int WifiMac3FieldNumber = 57;
  private int wifiMac3_;
  /// <summary>
  /// Wifi MAC address byte 3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WifiMac3 {
    get { return wifiMac3_; }
    set {
      wifiMac3_ = value;
    }
  }

  /// <summary>Field number for the "wifi_mac_4" field.</summary>
  public const int WifiMac4FieldNumber = 58;
  private int wifiMac4_;
  /// <summary>
  /// Wifi MAC address byte 4
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WifiMac4 {
    get { return wifiMac4_; }
    set {
      wifiMac4_ = value;
    }
  }

  /// <summary>Field number for the "wifi_mac_5" field.</summary>
  public const int WifiMac5FieldNumber = 59;
  private int wifiMac5_;
  /// <summary>
  /// Wifi MAC address byte 5
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WifiMac5 {
    get { return wifiMac5_; }
    set {
      wifiMac5_ = value;
    }
  }

  /// <summary>Field number for the "gprs_imei" field.</summary>
  public const int GprsImeiFieldNumber = 60;
  private string gprsImei_ = "";
  /// <summary>
  /// GPRS IMEI
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GprsImei {
    get { return gprsImei_; }
    set {
      gprsImei_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "dtu_ap_ssid" field.</summary>
  public const int DtuApSsidFieldNumber = 61;
  private string dtuApSsid_ = "";
  /// <summary>
  /// DTU Access Point (AP) SSID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DtuApSsid {
    get { return dtuApSsid_; }
    set {
      dtuApSsid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "dtu_ap_pass" field.</summary>
  public const int DtuApPassFieldNumber = 62;
  private string dtuApPass_ = "";
  /// <summary>
  /// DTU AP password
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DtuApPass {
    get { return dtuApPass_; }
    set {
      dtuApPass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetConfigReqDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetConfigReqDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RequestOffset != other.RequestOffset) return false;
    if (RequestTime != other.RequestTime) return false;
    if (LockPassword != other.LockPassword) return false;
    if (LockTime != other.LockTime) return false;
    if (LimitPowerMypower != other.LimitPowerMypower) return false;
    if (ZeroExport433Addr != other.ZeroExport433Addr) return false;
    if (ZeroExportEnable != other.ZeroExportEnable) return false;
    if (NetmodeSelect != other.NetmodeSelect) return false;
    if (ChannelSelect != other.ChannelSelect) return false;
    if (ServerSendTime != other.ServerSendTime) return false;
    if (WifiRssi != other.WifiRssi) return false;
    if (Serverport != other.Serverport) return false;
    if (ApnSet != other.ApnSet) return false;
    if (MeterKind != other.MeterKind) return false;
    if (MeterInterface != other.MeterInterface) return false;
    if (WifiSsid != other.WifiSsid) return false;
    if (WifiPassword != other.WifiPassword) return false;
    if (ServerDomainName != other.ServerDomainName) return false;
    if (InvType != other.InvType) return false;
    if (DtuSn != other.DtuSn) return false;
    if (AccessModel != other.AccessModel) return false;
    if (Mac0 != other.Mac0) return false;
    if (Mac1 != other.Mac1) return false;
    if (Mac2 != other.Mac2) return false;
    if (Mac3 != other.Mac3) return false;
    if (DhcpSwitch != other.DhcpSwitch) return false;
    if (IpAddr0 != other.IpAddr0) return false;
    if (IpAddr1 != other.IpAddr1) return false;
    if (IpAddr2 != other.IpAddr2) return false;
    if (IpAddr3 != other.IpAddr3) return false;
    if (SubnetMask0 != other.SubnetMask0) return false;
    if (SubnetMask1 != other.SubnetMask1) return false;
    if (SubnetMask2 != other.SubnetMask2) return false;
    if (SubnetMask3 != other.SubnetMask3) return false;
    if (DefaultGateway0 != other.DefaultGateway0) return false;
    if (DefaultGateway1 != other.DefaultGateway1) return false;
    if (DefaultGateway2 != other.DefaultGateway2) return false;
    if (DefaultGateway3 != other.DefaultGateway3) return false;
    if (KaNub != other.KaNub) return false;
    if (ApnName != other.ApnName) return false;
    if (ApnPassword != other.ApnPassword) return false;
    if (Sub1GSweepSwitch != other.Sub1GSweepSwitch) return false;
    if (Sub1GWorkChannel != other.Sub1GWorkChannel) return false;
    if (CableDns0 != other.CableDns0) return false;
    if (CableDns1 != other.CableDns1) return false;
    if (CableDns2 != other.CableDns2) return false;
    if (CableDns3 != other.CableDns3) return false;
    if (WifiIpAddr0 != other.WifiIpAddr0) return false;
    if (WifiIpAddr1 != other.WifiIpAddr1) return false;
    if (WifiIpAddr2 != other.WifiIpAddr2) return false;
    if (WifiIpAddr3 != other.WifiIpAddr3) return false;
    if (Mac4 != other.Mac4) return false;
    if (Mac5 != other.Mac5) return false;
    if (WifiMac0 != other.WifiMac0) return false;
    if (WifiMac1 != other.WifiMac1) return false;
    if (WifiMac2 != other.WifiMac2) return false;
    if (WifiMac3 != other.WifiMac3) return false;
    if (WifiMac4 != other.WifiMac4) return false;
    if (WifiMac5 != other.WifiMac5) return false;
    if (GprsImei != other.GprsImei) return false;
    if (DtuApSsid != other.DtuApSsid) return false;
    if (DtuApPass != other.DtuApPass) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (RequestOffset != 0) hash ^= RequestOffset.GetHashCode();
    if (RequestTime != 0) hash ^= RequestTime.GetHashCode();
    if (LockPassword != 0) hash ^= LockPassword.GetHashCode();
    if (LockTime != 0) hash ^= LockTime.GetHashCode();
    if (LimitPowerMypower != 0) hash ^= LimitPowerMypower.GetHashCode();
    if (ZeroExport433Addr != 0) hash ^= ZeroExport433Addr.GetHashCode();
    if (ZeroExportEnable != 0) hash ^= ZeroExportEnable.GetHashCode();
    if (NetmodeSelect != 0) hash ^= NetmodeSelect.GetHashCode();
    if (ChannelSelect != 0) hash ^= ChannelSelect.GetHashCode();
    if (ServerSendTime != 0) hash ^= ServerSendTime.GetHashCode();
    if (WifiRssi != 0) hash ^= WifiRssi.GetHashCode();
    if (Serverport != 0) hash ^= Serverport.GetHashCode();
    if (ApnSet.Length != 0) hash ^= ApnSet.GetHashCode();
    if (MeterKind.Length != 0) hash ^= MeterKind.GetHashCode();
    if (MeterInterface.Length != 0) hash ^= MeterInterface.GetHashCode();
    if (WifiSsid.Length != 0) hash ^= WifiSsid.GetHashCode();
    if (WifiPassword.Length != 0) hash ^= WifiPassword.GetHashCode();
    if (ServerDomainName.Length != 0) hash ^= ServerDomainName.GetHashCode();
    if (InvType != 0) hash ^= InvType.GetHashCode();
    if (DtuSn.Length != 0) hash ^= DtuSn.GetHashCode();
    if (AccessModel != 0) hash ^= AccessModel.GetHashCode();
    if (Mac0 != 0) hash ^= Mac0.GetHashCode();
    if (Mac1 != 0) hash ^= Mac1.GetHashCode();
    if (Mac2 != 0) hash ^= Mac2.GetHashCode();
    if (Mac3 != 0) hash ^= Mac3.GetHashCode();
    if (DhcpSwitch != 0) hash ^= DhcpSwitch.GetHashCode();
    if (IpAddr0 != 0) hash ^= IpAddr0.GetHashCode();
    if (IpAddr1 != 0) hash ^= IpAddr1.GetHashCode();
    if (IpAddr2 != 0) hash ^= IpAddr2.GetHashCode();
    if (IpAddr3 != 0) hash ^= IpAddr3.GetHashCode();
    if (SubnetMask0 != 0) hash ^= SubnetMask0.GetHashCode();
    if (SubnetMask1 != 0) hash ^= SubnetMask1.GetHashCode();
    if (SubnetMask2 != 0) hash ^= SubnetMask2.GetHashCode();
    if (SubnetMask3 != 0) hash ^= SubnetMask3.GetHashCode();
    if (DefaultGateway0 != 0) hash ^= DefaultGateway0.GetHashCode();
    if (DefaultGateway1 != 0) hash ^= DefaultGateway1.GetHashCode();
    if (DefaultGateway2 != 0) hash ^= DefaultGateway2.GetHashCode();
    if (DefaultGateway3 != 0) hash ^= DefaultGateway3.GetHashCode();
    if (KaNub.Length != 0) hash ^= KaNub.GetHashCode();
    if (ApnName.Length != 0) hash ^= ApnName.GetHashCode();
    if (ApnPassword.Length != 0) hash ^= ApnPassword.GetHashCode();
    if (Sub1GSweepSwitch != 0) hash ^= Sub1GSweepSwitch.GetHashCode();
    if (Sub1GWorkChannel != 0) hash ^= Sub1GWorkChannel.GetHashCode();
    if (CableDns0 != 0) hash ^= CableDns0.GetHashCode();
    if (CableDns1 != 0) hash ^= CableDns1.GetHashCode();
    if (CableDns2 != 0) hash ^= CableDns2.GetHashCode();
    if (CableDns3 != 0) hash ^= CableDns3.GetHashCode();
    if (WifiIpAddr0 != 0) hash ^= WifiIpAddr0.GetHashCode();
    if (WifiIpAddr1 != 0) hash ^= WifiIpAddr1.GetHashCode();
    if (WifiIpAddr2 != 0) hash ^= WifiIpAddr2.GetHashCode();
    if (WifiIpAddr3 != 0) hash ^= WifiIpAddr3.GetHashCode();
    if (Mac4 != 0) hash ^= Mac4.GetHashCode();
    if (Mac5 != 0) hash ^= Mac5.GetHashCode();
    if (WifiMac0 != 0) hash ^= WifiMac0.GetHashCode();
    if (WifiMac1 != 0) hash ^= WifiMac1.GetHashCode();
    if (WifiMac2 != 0) hash ^= WifiMac2.GetHashCode();
    if (WifiMac3 != 0) hash ^= WifiMac3.GetHashCode();
    if (WifiMac4 != 0) hash ^= WifiMac4.GetHashCode();
    if (WifiMac5 != 0) hash ^= WifiMac5.GetHashCode();
    if (GprsImei.Length != 0) hash ^= GprsImei.GetHashCode();
    if (DtuApSsid.Length != 0) hash ^= DtuApSsid.GetHashCode();
    if (DtuApPass.Length != 0) hash ^= DtuApPass.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (RequestOffset != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(RequestOffset);
    }
    if (RequestTime != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(RequestTime);
    }
    if (LockPassword != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(LockPassword);
    }
    if (LockTime != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(LockTime);
    }
    if (LimitPowerMypower != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(LimitPowerMypower);
    }
    if (ZeroExport433Addr != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(ZeroExport433Addr);
    }
    if (ZeroExportEnable != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(ZeroExportEnable);
    }
    if (NetmodeSelect != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(NetmodeSelect);
    }
    if (ChannelSelect != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(ChannelSelect);
    }
    if (ServerSendTime != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(ServerSendTime);
    }
    if (WifiRssi != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(WifiRssi);
    }
    if (Serverport != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(Serverport);
    }
    if (ApnSet.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(ApnSet);
    }
    if (MeterKind.Length != 0) {
      output.WriteRawTag(114);
      output.WriteString(MeterKind);
    }
    if (MeterInterface.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(MeterInterface);
    }
    if (WifiSsid.Length != 0) {
      output.WriteRawTag(130, 1);
      output.WriteString(WifiSsid);
    }
    if (WifiPassword.Length != 0) {
      output.WriteRawTag(138, 1);
      output.WriteString(WifiPassword);
    }
    if (ServerDomainName.Length != 0) {
      output.WriteRawTag(146, 1);
      output.WriteString(ServerDomainName);
    }
    if (InvType != 0) {
      output.WriteRawTag(152, 1);
      output.WriteInt32(InvType);
    }
    if (DtuSn.Length != 0) {
      output.WriteRawTag(162, 1);
      output.WriteString(DtuSn);
    }
    if (AccessModel != 0) {
      output.WriteRawTag(168, 1);
      output.WriteInt32(AccessModel);
    }
    if (Mac0 != 0) {
      output.WriteRawTag(176, 1);
      output.WriteInt32(Mac0);
    }
    if (Mac1 != 0) {
      output.WriteRawTag(184, 1);
      output.WriteInt32(Mac1);
    }
    if (Mac2 != 0) {
      output.WriteRawTag(192, 1);
      output.WriteInt32(Mac2);
    }
    if (Mac3 != 0) {
      output.WriteRawTag(200, 1);
      output.WriteInt32(Mac3);
    }
    if (DhcpSwitch != 0) {
      output.WriteRawTag(208, 1);
      output.WriteInt32(DhcpSwitch);
    }
    if (IpAddr0 != 0) {
      output.WriteRawTag(216, 1);
      output.WriteInt32(IpAddr0);
    }
    if (IpAddr1 != 0) {
      output.WriteRawTag(224, 1);
      output.WriteInt32(IpAddr1);
    }
    if (IpAddr2 != 0) {
      output.WriteRawTag(232, 1);
      output.WriteInt32(IpAddr2);
    }
    if (IpAddr3 != 0) {
      output.WriteRawTag(240, 1);
      output.WriteInt32(IpAddr3);
    }
    if (SubnetMask0 != 0) {
      output.WriteRawTag(248, 1);
      output.WriteInt32(SubnetMask0);
    }
    if (SubnetMask1 != 0) {
      output.WriteRawTag(128, 2);
      output.WriteInt32(SubnetMask1);
    }
    if (SubnetMask2 != 0) {
      output.WriteRawTag(136, 2);
      output.WriteInt32(SubnetMask2);
    }
    if (SubnetMask3 != 0) {
      output.WriteRawTag(144, 2);
      output.WriteInt32(SubnetMask3);
    }
    if (DefaultGateway0 != 0) {
      output.WriteRawTag(152, 2);
      output.WriteInt32(DefaultGateway0);
    }
    if (DefaultGateway1 != 0) {
      output.WriteRawTag(160, 2);
      output.WriteInt32(DefaultGateway1);
    }
    if (DefaultGateway2 != 0) {
      output.WriteRawTag(168, 2);
      output.WriteInt32(DefaultGateway2);
    }
    if (DefaultGateway3 != 0) {
      output.WriteRawTag(176, 2);
      output.WriteInt32(DefaultGateway3);
    }
    if (KaNub.Length != 0) {
      output.WriteRawTag(186, 2);
      output.WriteString(KaNub);
    }
    if (ApnName.Length != 0) {
      output.WriteRawTag(194, 2);
      output.WriteString(ApnName);
    }
    if (ApnPassword.Length != 0) {
      output.WriteRawTag(202, 2);
      output.WriteString(ApnPassword);
    }
    if (Sub1GSweepSwitch != 0) {
      output.WriteRawTag(208, 2);
      output.WriteInt32(Sub1GSweepSwitch);
    }
    if (Sub1GWorkChannel != 0) {
      output.WriteRawTag(216, 2);
      output.WriteInt32(Sub1GWorkChannel);
    }
    if (CableDns0 != 0) {
      output.WriteRawTag(224, 2);
      output.WriteInt32(CableDns0);
    }
    if (CableDns1 != 0) {
      output.WriteRawTag(232, 2);
      output.WriteInt32(CableDns1);
    }
    if (CableDns2 != 0) {
      output.WriteRawTag(240, 2);
      output.WriteInt32(CableDns2);
    }
    if (CableDns3 != 0) {
      output.WriteRawTag(248, 2);
      output.WriteInt32(CableDns3);
    }
    if (WifiIpAddr0 != 0) {
      output.WriteRawTag(128, 3);
      output.WriteInt32(WifiIpAddr0);
    }
    if (WifiIpAddr1 != 0) {
      output.WriteRawTag(136, 3);
      output.WriteInt32(WifiIpAddr1);
    }
    if (WifiIpAddr2 != 0) {
      output.WriteRawTag(144, 3);
      output.WriteInt32(WifiIpAddr2);
    }
    if (WifiIpAddr3 != 0) {
      output.WriteRawTag(152, 3);
      output.WriteInt32(WifiIpAddr3);
    }
    if (Mac4 != 0) {
      output.WriteRawTag(160, 3);
      output.WriteInt32(Mac4);
    }
    if (Mac5 != 0) {
      output.WriteRawTag(168, 3);
      output.WriteInt32(Mac5);
    }
    if (WifiMac0 != 0) {
      output.WriteRawTag(176, 3);
      output.WriteInt32(WifiMac0);
    }
    if (WifiMac1 != 0) {
      output.WriteRawTag(184, 3);
      output.WriteInt32(WifiMac1);
    }
    if (WifiMac2 != 0) {
      output.WriteRawTag(192, 3);
      output.WriteInt32(WifiMac2);
    }
    if (WifiMac3 != 0) {
      output.WriteRawTag(200, 3);
      output.WriteInt32(WifiMac3);
    }
    if (WifiMac4 != 0) {
      output.WriteRawTag(208, 3);
      output.WriteInt32(WifiMac4);
    }
    if (WifiMac5 != 0) {
      output.WriteRawTag(216, 3);
      output.WriteInt32(WifiMac5);
    }
    if (GprsImei.Length != 0) {
      output.WriteRawTag(226, 3);
      output.WriteString(GprsImei);
    }
    if (DtuApSsid.Length != 0) {
      output.WriteRawTag(234, 3);
      output.WriteString(DtuApSsid);
    }
    if (DtuApPass.Length != 0) {
      output.WriteRawTag(242, 3);
      output.WriteString(DtuApPass);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (RequestOffset != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(RequestOffset);
    }
    if (RequestTime != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(RequestTime);
    }
    if (LockPassword != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(LockPassword);
    }
    if (LockTime != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(LockTime);
    }
    if (LimitPowerMypower != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(LimitPowerMypower);
    }
    if (ZeroExport433Addr != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(ZeroExport433Addr);
    }
    if (ZeroExportEnable != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(ZeroExportEnable);
    }
    if (NetmodeSelect != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(NetmodeSelect);
    }
    if (ChannelSelect != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(ChannelSelect);
    }
    if (ServerSendTime != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(ServerSendTime);
    }
    if (WifiRssi != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(WifiRssi);
    }
    if (Serverport != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(Serverport);
    }
    if (ApnSet.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(ApnSet);
    }
    if (MeterKind.Length != 0) {
      output.WriteRawTag(114);
      output.WriteString(MeterKind);
    }
    if (MeterInterface.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(MeterInterface);
    }
    if (WifiSsid.Length != 0) {
      output.WriteRawTag(130, 1);
      output.WriteString(WifiSsid);
    }
    if (WifiPassword.Length != 0) {
      output.WriteRawTag(138, 1);
      output.WriteString(WifiPassword);
    }
    if (ServerDomainName.Length != 0) {
      output.WriteRawTag(146, 1);
      output.WriteString(ServerDomainName);
    }
    if (InvType != 0) {
      output.WriteRawTag(152, 1);
      output.WriteInt32(InvType);
    }
    if (DtuSn.Length != 0) {
      output.WriteRawTag(162, 1);
      output.WriteString(DtuSn);
    }
    if (AccessModel != 0) {
      output.WriteRawTag(168, 1);
      output.WriteInt32(AccessModel);
    }
    if (Mac0 != 0) {
      output.WriteRawTag(176, 1);
      output.WriteInt32(Mac0);
    }
    if (Mac1 != 0) {
      output.WriteRawTag(184, 1);
      output.WriteInt32(Mac1);
    }
    if (Mac2 != 0) {
      output.WriteRawTag(192, 1);
      output.WriteInt32(Mac2);
    }
    if (Mac3 != 0) {
      output.WriteRawTag(200, 1);
      output.WriteInt32(Mac3);
    }
    if (DhcpSwitch != 0) {
      output.WriteRawTag(208, 1);
      output.WriteInt32(DhcpSwitch);
    }
    if (IpAddr0 != 0) {
      output.WriteRawTag(216, 1);
      output.WriteInt32(IpAddr0);
    }
    if (IpAddr1 != 0) {
      output.WriteRawTag(224, 1);
      output.WriteInt32(IpAddr1);
    }
    if (IpAddr2 != 0) {
      output.WriteRawTag(232, 1);
      output.WriteInt32(IpAddr2);
    }
    if (IpAddr3 != 0) {
      output.WriteRawTag(240, 1);
      output.WriteInt32(IpAddr3);
    }
    if (SubnetMask0 != 0) {
      output.WriteRawTag(248, 1);
      output.WriteInt32(SubnetMask0);
    }
    if (SubnetMask1 != 0) {
      output.WriteRawTag(128, 2);
      output.WriteInt32(SubnetMask1);
    }
    if (SubnetMask2 != 0) {
      output.WriteRawTag(136, 2);
      output.WriteInt32(SubnetMask2);
    }
    if (SubnetMask3 != 0) {
      output.WriteRawTag(144, 2);
      output.WriteInt32(SubnetMask3);
    }
    if (DefaultGateway0 != 0) {
      output.WriteRawTag(152, 2);
      output.WriteInt32(DefaultGateway0);
    }
    if (DefaultGateway1 != 0) {
      output.WriteRawTag(160, 2);
      output.WriteInt32(DefaultGateway1);
    }
    if (DefaultGateway2 != 0) {
      output.WriteRawTag(168, 2);
      output.WriteInt32(DefaultGateway2);
    }
    if (DefaultGateway3 != 0) {
      output.WriteRawTag(176, 2);
      output.WriteInt32(DefaultGateway3);
    }
    if (KaNub.Length != 0) {
      output.WriteRawTag(186, 2);
      output.WriteString(KaNub);
    }
    if (ApnName.Length != 0) {
      output.WriteRawTag(194, 2);
      output.WriteString(ApnName);
    }
    if (ApnPassword.Length != 0) {
      output.WriteRawTag(202, 2);
      output.WriteString(ApnPassword);
    }
    if (Sub1GSweepSwitch != 0) {
      output.WriteRawTag(208, 2);
      output.WriteInt32(Sub1GSweepSwitch);
    }
    if (Sub1GWorkChannel != 0) {
      output.WriteRawTag(216, 2);
      output.WriteInt32(Sub1GWorkChannel);
    }
    if (CableDns0 != 0) {
      output.WriteRawTag(224, 2);
      output.WriteInt32(CableDns0);
    }
    if (CableDns1 != 0) {
      output.WriteRawTag(232, 2);
      output.WriteInt32(CableDns1);
    }
    if (CableDns2 != 0) {
      output.WriteRawTag(240, 2);
      output.WriteInt32(CableDns2);
    }
    if (CableDns3 != 0) {
      output.WriteRawTag(248, 2);
      output.WriteInt32(CableDns3);
    }
    if (WifiIpAddr0 != 0) {
      output.WriteRawTag(128, 3);
      output.WriteInt32(WifiIpAddr0);
    }
    if (WifiIpAddr1 != 0) {
      output.WriteRawTag(136, 3);
      output.WriteInt32(WifiIpAddr1);
    }
    if (WifiIpAddr2 != 0) {
      output.WriteRawTag(144, 3);
      output.WriteInt32(WifiIpAddr2);
    }
    if (WifiIpAddr3 != 0) {
      output.WriteRawTag(152, 3);
      output.WriteInt32(WifiIpAddr3);
    }
    if (Mac4 != 0) {
      output.WriteRawTag(160, 3);
      output.WriteInt32(Mac4);
    }
    if (Mac5 != 0) {
      output.WriteRawTag(168, 3);
      output.WriteInt32(Mac5);
    }
    if (WifiMac0 != 0) {
      output.WriteRawTag(176, 3);
      output.WriteInt32(WifiMac0);
    }
    if (WifiMac1 != 0) {
      output.WriteRawTag(184, 3);
      output.WriteInt32(WifiMac1);
    }
    if (WifiMac2 != 0) {
      output.WriteRawTag(192, 3);
      output.WriteInt32(WifiMac2);
    }
    if (WifiMac3 != 0) {
      output.WriteRawTag(200, 3);
      output.WriteInt32(WifiMac3);
    }
    if (WifiMac4 != 0) {
      output.WriteRawTag(208, 3);
      output.WriteInt32(WifiMac4);
    }
    if (WifiMac5 != 0) {
      output.WriteRawTag(216, 3);
      output.WriteInt32(WifiMac5);
    }
    if (GprsImei.Length != 0) {
      output.WriteRawTag(226, 3);
      output.WriteString(GprsImei);
    }
    if (DtuApSsid.Length != 0) {
      output.WriteRawTag(234, 3);
      output.WriteString(DtuApSsid);
    }
    if (DtuApPass.Length != 0) {
      output.WriteRawTag(242, 3);
      output.WriteString(DtuApPass);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (RequestOffset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RequestOffset);
    }
    if (RequestTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RequestTime);
    }
    if (LockPassword != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LockPassword);
    }
    if (LockTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LockTime);
    }
    if (LimitPowerMypower != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LimitPowerMypower);
    }
    if (ZeroExport433Addr != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ZeroExport433Addr);
    }
    if (ZeroExportEnable != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ZeroExportEnable);
    }
    if (NetmodeSelect != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NetmodeSelect);
    }
    if (ChannelSelect != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChannelSelect);
    }
    if (ServerSendTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerSendTime);
    }
    if (WifiRssi != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(WifiRssi);
    }
    if (Serverport != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Serverport);
    }
    if (ApnSet.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ApnSet);
    }
    if (MeterKind.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MeterKind);
    }
    if (MeterInterface.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MeterInterface);
    }
    if (WifiSsid.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(WifiSsid);
    }
    if (WifiPassword.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(WifiPassword);
    }
    if (ServerDomainName.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(ServerDomainName);
    }
    if (InvType != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(InvType);
    }
    if (DtuSn.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(DtuSn);
    }
    if (AccessModel != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(AccessModel);
    }
    if (Mac0 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Mac0);
    }
    if (Mac1 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Mac1);
    }
    if (Mac2 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Mac2);
    }
    if (Mac3 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Mac3);
    }
    if (DhcpSwitch != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(DhcpSwitch);
    }
    if (IpAddr0 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IpAddr0);
    }
    if (IpAddr1 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IpAddr1);
    }
    if (IpAddr2 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IpAddr2);
    }
    if (IpAddr3 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IpAddr3);
    }
    if (SubnetMask0 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(SubnetMask0);
    }
    if (SubnetMask1 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(SubnetMask1);
    }
    if (SubnetMask2 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(SubnetMask2);
    }
    if (SubnetMask3 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(SubnetMask3);
    }
    if (DefaultGateway0 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(DefaultGateway0);
    }
    if (DefaultGateway1 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(DefaultGateway1);
    }
    if (DefaultGateway2 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(DefaultGateway2);
    }
    if (DefaultGateway3 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(DefaultGateway3);
    }
    if (KaNub.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(KaNub);
    }
    if (ApnName.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(ApnName);
    }
    if (ApnPassword.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(ApnPassword);
    }
    if (Sub1GSweepSwitch != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Sub1GSweepSwitch);
    }
    if (Sub1GWorkChannel != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Sub1GWorkChannel);
    }
    if (CableDns0 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(CableDns0);
    }
    if (CableDns1 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(CableDns1);
    }
    if (CableDns2 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(CableDns2);
    }
    if (CableDns3 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(CableDns3);
    }
    if (WifiIpAddr0 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(WifiIpAddr0);
    }
    if (WifiIpAddr1 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(WifiIpAddr1);
    }
    if (WifiIpAddr2 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(WifiIpAddr2);
    }
    if (WifiIpAddr3 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(WifiIpAddr3);
    }
    if (Mac4 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Mac4);
    }
    if (Mac5 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Mac5);
    }
    if (WifiMac0 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(WifiMac0);
    }
    if (WifiMac1 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(WifiMac1);
    }
    if (WifiMac2 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(WifiMac2);
    }
    if (WifiMac3 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(WifiMac3);
    }
    if (WifiMac4 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(WifiMac4);
    }
    if (WifiMac5 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(WifiMac5);
    }
    if (GprsImei.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(GprsImei);
    }
    if (DtuApSsid.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(DtuApSsid);
    }
    if (DtuApPass.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(DtuApPass);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetConfigReqDTO other) {
    if (other == null) {
      return;
    }
    if (other.RequestOffset != 0) {
      RequestOffset = other.RequestOffset;
    }
    if (other.RequestTime != 0) {
      RequestTime = other.RequestTime;
    }
    if (other.LockPassword != 0) {
      LockPassword = other.LockPassword;
    }
    if (other.LockTime != 0) {
      LockTime = other.LockTime;
    }
    if (other.LimitPowerMypower != 0) {
      LimitPowerMypower = other.LimitPowerMypower;
    }
    if (other.ZeroExport433Addr != 0) {
      ZeroExport433Addr = other.ZeroExport433Addr;
    }
    if (other.ZeroExportEnable != 0) {
      ZeroExportEnable = other.ZeroExportEnable;
    }
    if (other.NetmodeSelect != 0) {
      NetmodeSelect = other.NetmodeSelect;
    }
    if (other.ChannelSelect != 0) {
      ChannelSelect = other.ChannelSelect;
    }
    if (other.ServerSendTime != 0) {
      ServerSendTime = other.ServerSendTime;
    }
    if (other.WifiRssi != 0) {
      WifiRssi = other.WifiRssi;
    }
    if (other.Serverport != 0) {
      Serverport = other.Serverport;
    }
    if (other.ApnSet.Length != 0) {
      ApnSet = other.ApnSet;
    }
    if (other.MeterKind.Length != 0) {
      MeterKind = other.MeterKind;
    }
    if (other.MeterInterface.Length != 0) {
      MeterInterface = other.MeterInterface;
    }
    if (other.WifiSsid.Length != 0) {
      WifiSsid = other.WifiSsid;
    }
    if (other.WifiPassword.Length != 0) {
      WifiPassword = other.WifiPassword;
    }
    if (other.ServerDomainName.Length != 0) {
      ServerDomainName = other.ServerDomainName;
    }
    if (other.InvType != 0) {
      InvType = other.InvType;
    }
    if (other.DtuSn.Length != 0) {
      DtuSn = other.DtuSn;
    }
    if (other.AccessModel != 0) {
      AccessModel = other.AccessModel;
    }
    if (other.Mac0 != 0) {
      Mac0 = other.Mac0;
    }
    if (other.Mac1 != 0) {
      Mac1 = other.Mac1;
    }
    if (other.Mac2 != 0) {
      Mac2 = other.Mac2;
    }
    if (other.Mac3 != 0) {
      Mac3 = other.Mac3;
    }
    if (other.DhcpSwitch != 0) {
      DhcpSwitch = other.DhcpSwitch;
    }
    if (other.IpAddr0 != 0) {
      IpAddr0 = other.IpAddr0;
    }
    if (other.IpAddr1 != 0) {
      IpAddr1 = other.IpAddr1;
    }
    if (other.IpAddr2 != 0) {
      IpAddr2 = other.IpAddr2;
    }
    if (other.IpAddr3 != 0) {
      IpAddr3 = other.IpAddr3;
    }
    if (other.SubnetMask0 != 0) {
      SubnetMask0 = other.SubnetMask0;
    }
    if (other.SubnetMask1 != 0) {
      SubnetMask1 = other.SubnetMask1;
    }
    if (other.SubnetMask2 != 0) {
      SubnetMask2 = other.SubnetMask2;
    }
    if (other.SubnetMask3 != 0) {
      SubnetMask3 = other.SubnetMask3;
    }
    if (other.DefaultGateway0 != 0) {
      DefaultGateway0 = other.DefaultGateway0;
    }
    if (other.DefaultGateway1 != 0) {
      DefaultGateway1 = other.DefaultGateway1;
    }
    if (other.DefaultGateway2 != 0) {
      DefaultGateway2 = other.DefaultGateway2;
    }
    if (other.DefaultGateway3 != 0) {
      DefaultGateway3 = other.DefaultGateway3;
    }
    if (other.KaNub.Length != 0) {
      KaNub = other.KaNub;
    }
    if (other.ApnName.Length != 0) {
      ApnName = other.ApnName;
    }
    if (other.ApnPassword.Length != 0) {
      ApnPassword = other.ApnPassword;
    }
    if (other.Sub1GSweepSwitch != 0) {
      Sub1GSweepSwitch = other.Sub1GSweepSwitch;
    }
    if (other.Sub1GWorkChannel != 0) {
      Sub1GWorkChannel = other.Sub1GWorkChannel;
    }
    if (other.CableDns0 != 0) {
      CableDns0 = other.CableDns0;
    }
    if (other.CableDns1 != 0) {
      CableDns1 = other.CableDns1;
    }
    if (other.CableDns2 != 0) {
      CableDns2 = other.CableDns2;
    }
    if (other.CableDns3 != 0) {
      CableDns3 = other.CableDns3;
    }
    if (other.WifiIpAddr0 != 0) {
      WifiIpAddr0 = other.WifiIpAddr0;
    }
    if (other.WifiIpAddr1 != 0) {
      WifiIpAddr1 = other.WifiIpAddr1;
    }
    if (other.WifiIpAddr2 != 0) {
      WifiIpAddr2 = other.WifiIpAddr2;
    }
    if (other.WifiIpAddr3 != 0) {
      WifiIpAddr3 = other.WifiIpAddr3;
    }
    if (other.Mac4 != 0) {
      Mac4 = other.Mac4;
    }
    if (other.Mac5 != 0) {
      Mac5 = other.Mac5;
    }
    if (other.WifiMac0 != 0) {
      WifiMac0 = other.WifiMac0;
    }
    if (other.WifiMac1 != 0) {
      WifiMac1 = other.WifiMac1;
    }
    if (other.WifiMac2 != 0) {
      WifiMac2 = other.WifiMac2;
    }
    if (other.WifiMac3 != 0) {
      WifiMac3 = other.WifiMac3;
    }
    if (other.WifiMac4 != 0) {
      WifiMac4 = other.WifiMac4;
    }
    if (other.WifiMac5 != 0) {
      WifiMac5 = other.WifiMac5;
    }
    if (other.GprsImei.Length != 0) {
      GprsImei = other.GprsImei;
    }
    if (other.DtuApSsid.Length != 0) {
      DtuApSsid = other.DtuApSsid;
    }
    if (other.DtuApPass.Length != 0) {
      DtuApPass = other.DtuApPass;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          RequestOffset = input.ReadInt32();
          break;
        }
        case 16: {
          RequestTime = input.ReadUInt32();
          break;
        }
        case 24: {
          LockPassword = input.ReadInt32();
          break;
        }
        case 32: {
          LockTime = input.ReadInt32();
          break;
        }
        case 40: {
          LimitPowerMypower = input.ReadInt32();
          break;
        }
        case 48: {
          ZeroExport433Addr = input.ReadInt32();
          break;
        }
        case 56: {
          ZeroExportEnable = input.ReadInt32();
          break;
        }
        case 64: {
          NetmodeSelect = input.ReadInt32();
          break;
        }
        case 72: {
          ChannelSelect = input.ReadInt32();
          break;
        }
        case 80: {
          ServerSendTime = input.ReadInt32();
          break;
        }
        case 88: {
          WifiRssi = input.ReadInt32();
          break;
        }
        case 96: {
          Serverport = input.ReadInt32();
          break;
        }
        case 106: {
          ApnSet = input.ReadString();
          break;
        }
        case 114: {
          MeterKind = input.ReadString();
          break;
        }
        case 122: {
          MeterInterface = input.ReadString();
          break;
        }
        case 130: {
          WifiSsid = input.ReadString();
          break;
        }
        case 138: {
          WifiPassword = input.ReadString();
          break;
        }
        case 146: {
          ServerDomainName = input.ReadString();
          break;
        }
        case 152: {
          InvType = input.ReadInt32();
          break;
        }
        case 162: {
          DtuSn = input.ReadString();
          break;
        }
        case 168: {
          AccessModel = input.ReadInt32();
          break;
        }
        case 176: {
          Mac0 = input.ReadInt32();
          break;
        }
        case 184: {
          Mac1 = input.ReadInt32();
          break;
        }
        case 192: {
          Mac2 = input.ReadInt32();
          break;
        }
        case 200: {
          Mac3 = input.ReadInt32();
          break;
        }
        case 208: {
          DhcpSwitch = input.ReadInt32();
          break;
        }
        case 216: {
          IpAddr0 = input.ReadInt32();
          break;
        }
        case 224: {
          IpAddr1 = input.ReadInt32();
          break;
        }
        case 232: {
          IpAddr2 = input.ReadInt32();
          break;
        }
        case 240: {
          IpAddr3 = input.ReadInt32();
          break;
        }
        case 248: {
          SubnetMask0 = input.ReadInt32();
          break;
        }
        case 256: {
          SubnetMask1 = input.ReadInt32();
          break;
        }
        case 264: {
          SubnetMask2 = input.ReadInt32();
          break;
        }
        case 272: {
          SubnetMask3 = input.ReadInt32();
          break;
        }
        case 280: {
          DefaultGateway0 = input.ReadInt32();
          break;
        }
        case 288: {
          DefaultGateway1 = input.ReadInt32();
          break;
        }
        case 296: {
          DefaultGateway2 = input.ReadInt32();
          break;
        }
        case 304: {
          DefaultGateway3 = input.ReadInt32();
          break;
        }
        case 314: {
          KaNub = input.ReadString();
          break;
        }
        case 322: {
          ApnName = input.ReadString();
          break;
        }
        case 330: {
          ApnPassword = input.ReadString();
          break;
        }
        case 336: {
          Sub1GSweepSwitch = input.ReadInt32();
          break;
        }
        case 344: {
          Sub1GWorkChannel = input.ReadInt32();
          break;
        }
        case 352: {
          CableDns0 = input.ReadInt32();
          break;
        }
        case 360: {
          CableDns1 = input.ReadInt32();
          break;
        }
        case 368: {
          CableDns2 = input.ReadInt32();
          break;
        }
        case 376: {
          CableDns3 = input.ReadInt32();
          break;
        }
        case 384: {
          WifiIpAddr0 = input.ReadInt32();
          break;
        }
        case 392: {
          WifiIpAddr1 = input.ReadInt32();
          break;
        }
        case 400: {
          WifiIpAddr2 = input.ReadInt32();
          break;
        }
        case 408: {
          WifiIpAddr3 = input.ReadInt32();
          break;
        }
        case 416: {
          Mac4 = input.ReadInt32();
          break;
        }
        case 424: {
          Mac5 = input.ReadInt32();
          break;
        }
        case 432: {
          WifiMac0 = input.ReadInt32();
          break;
        }
        case 440: {
          WifiMac1 = input.ReadInt32();
          break;
        }
        case 448: {
          WifiMac2 = input.ReadInt32();
          break;
        }
        case 456: {
          WifiMac3 = input.ReadInt32();
          break;
        }
        case 464: {
          WifiMac4 = input.ReadInt32();
          break;
        }
        case 472: {
          WifiMac5 = input.ReadInt32();
          break;
        }
        case 482: {
          GprsImei = input.ReadString();
          break;
        }
        case 490: {
          DtuApSsid = input.ReadString();
          break;
        }
        case 498: {
          DtuApPass = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          RequestOffset = input.ReadInt32();
          break;
        }
        case 16: {
          RequestTime = input.ReadUInt32();
          break;
        }
        case 24: {
          LockPassword = input.ReadInt32();
          break;
        }
        case 32: {
          LockTime = input.ReadInt32();
          break;
        }
        case 40: {
          LimitPowerMypower = input.ReadInt32();
          break;
        }
        case 48: {
          ZeroExport433Addr = input.ReadInt32();
          break;
        }
        case 56: {
          ZeroExportEnable = input.ReadInt32();
          break;
        }
        case 64: {
          NetmodeSelect = input.ReadInt32();
          break;
        }
        case 72: {
          ChannelSelect = input.ReadInt32();
          break;
        }
        case 80: {
          ServerSendTime = input.ReadInt32();
          break;
        }
        case 88: {
          WifiRssi = input.ReadInt32();
          break;
        }
        case 96: {
          Serverport = input.ReadInt32();
          break;
        }
        case 106: {
          ApnSet = input.ReadString();
          break;
        }
        case 114: {
          MeterKind = input.ReadString();
          break;
        }
        case 122: {
          MeterInterface = input.ReadString();
          break;
        }
        case 130: {
          WifiSsid = input.ReadString();
          break;
        }
        case 138: {
          WifiPassword = input.ReadString();
          break;
        }
        case 146: {
          ServerDomainName = input.ReadString();
          break;
        }
        case 152: {
          InvType = input.ReadInt32();
          break;
        }
        case 162: {
          DtuSn = input.ReadString();
          break;
        }
        case 168: {
          AccessModel = input.ReadInt32();
          break;
        }
        case 176: {
          Mac0 = input.ReadInt32();
          break;
        }
        case 184: {
          Mac1 = input.ReadInt32();
          break;
        }
        case 192: {
          Mac2 = input.ReadInt32();
          break;
        }
        case 200: {
          Mac3 = input.ReadInt32();
          break;
        }
        case 208: {
          DhcpSwitch = input.ReadInt32();
          break;
        }
        case 216: {
          IpAddr0 = input.ReadInt32();
          break;
        }
        case 224: {
          IpAddr1 = input.ReadInt32();
          break;
        }
        case 232: {
          IpAddr2 = input.ReadInt32();
          break;
        }
        case 240: {
          IpAddr3 = input.ReadInt32();
          break;
        }
        case 248: {
          SubnetMask0 = input.ReadInt32();
          break;
        }
        case 256: {
          SubnetMask1 = input.ReadInt32();
          break;
        }
        case 264: {
          SubnetMask2 = input.ReadInt32();
          break;
        }
        case 272: {
          SubnetMask3 = input.ReadInt32();
          break;
        }
        case 280: {
          DefaultGateway0 = input.ReadInt32();
          break;
        }
        case 288: {
          DefaultGateway1 = input.ReadInt32();
          break;
        }
        case 296: {
          DefaultGateway2 = input.ReadInt32();
          break;
        }
        case 304: {
          DefaultGateway3 = input.ReadInt32();
          break;
        }
        case 314: {
          KaNub = input.ReadString();
          break;
        }
        case 322: {
          ApnName = input.ReadString();
          break;
        }
        case 330: {
          ApnPassword = input.ReadString();
          break;
        }
        case 336: {
          Sub1GSweepSwitch = input.ReadInt32();
          break;
        }
        case 344: {
          Sub1GWorkChannel = input.ReadInt32();
          break;
        }
        case 352: {
          CableDns0 = input.ReadInt32();
          break;
        }
        case 360: {
          CableDns1 = input.ReadInt32();
          break;
        }
        case 368: {
          CableDns2 = input.ReadInt32();
          break;
        }
        case 376: {
          CableDns3 = input.ReadInt32();
          break;
        }
        case 384: {
          WifiIpAddr0 = input.ReadInt32();
          break;
        }
        case 392: {
          WifiIpAddr1 = input.ReadInt32();
          break;
        }
        case 400: {
          WifiIpAddr2 = input.ReadInt32();
          break;
        }
        case 408: {
          WifiIpAddr3 = input.ReadInt32();
          break;
        }
        case 416: {
          Mac4 = input.ReadInt32();
          break;
        }
        case 424: {
          Mac5 = input.ReadInt32();
          break;
        }
        case 432: {
          WifiMac0 = input.ReadInt32();
          break;
        }
        case 440: {
          WifiMac1 = input.ReadInt32();
          break;
        }
        case 448: {
          WifiMac2 = input.ReadInt32();
          break;
        }
        case 456: {
          WifiMac3 = input.ReadInt32();
          break;
        }
        case 464: {
          WifiMac4 = input.ReadInt32();
          break;
        }
        case 472: {
          WifiMac5 = input.ReadInt32();
          break;
        }
        case 482: {
          GprsImei = input.ReadString();
          break;
        }
        case 490: {
          DtuApSsid = input.ReadString();
          break;
        }
        case 498: {
          DtuApPass = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
