// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GPSTData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GPSTData.proto</summary>
public static partial class GPSTDataReflection {

  #region Descriptor
  /// <summary>File descriptor for GPSTData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GPSTDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5HUFNURGF0YS5wcm90byJfCgdTVFZhbE1PEgwKBGNvZGUYASABKAUSEAoI",
          "ZGZsdF92YWwYAiABKAUSEAoIZGZsdF90aW0YAyABKAUSEAoIcnNsdF92YWwY",
          "BCABKAUSEAoIcnNsdF90aW0YBSABKAUiuQIKCUdQU1RWYWxNTxINCgVwdl9z",
          "bhgBIAEoAxILCgN2ZXIYAiABKAUSCgoCc3QYAyABKAUSCwoDZ3BmGAQgASgF",
          "Eg8KB2dwZl92ZXIYBSABKAUSGwoJaHYxX3N0dmFsGAYgASgLMgguU1RWYWxN",
          "TxIbCglsdjFfc3R2YWwYByABKAsyCC5TVFZhbE1PEhsKCWh2Ml9zdHZhbBgI",
          "IAEoCzIILlNUVmFsTU8SGwoJbHYyX3N0dmFsGAkgASgLMgguU1RWYWxNTxIb",
          "CgloZjFfc3R2YWwYCiABKAsyCC5TVFZhbE1PEhsKCWxmMV9zdHZhbBgLIAEo",
          "CzIILlNUVmFsTU8SGwoJaGYyX3N0dmFsGAwgASgLMgguU1RWYWxNTxIbCgls",
          "ZjJfc3R2YWwYDSABKAsyCC5TVFZhbE1PInMKCkdQU1RSZXFEVE8SDgoGZHR1",
          "X3NuGAEgASgJEgwKBHRpbWUYAiABKAUSEwoLcGFja2FnZV9udWIYAyABKAUS",
          "EwoLcGFja2FnZV9ub3cYBCABKAUSHQoJbUdQU1RJbmZvGAUgAygLMgouR1BT",
          "VFZhbE1PImIKCkdQU1RSZXNEVE8SDwoHeW1kX2htcxgBIAEoCRIOCgZvZmZz",
          "ZXQYAiABKAUSEwoLcGFja2FnZV9ub3cYAyABKAUSEAoIZXJyX2NvZGUYBCAB",
          "KAUSDAoEdGltZRgFIAEoBWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::STValMO), global::STValMO.Parser, new[]{ "Code", "DfltVal", "DfltTim", "RsltVal", "RsltTim" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GPSTValMO), global::GPSTValMO.Parser, new[]{ "PvSn", "Ver", "St", "Gpf", "GpfVer", "Hv1Stval", "Lv1Stval", "Hv2Stval", "Lv2Stval", "Hf1Stval", "Lf1Stval", "Hf2Stval", "Lf2Stval" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GPSTReqDTO), global::GPSTReqDTO.Parser, new[]{ "DtuSn", "Time", "PackageNub", "PackageNow", "MGPSTInfo" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GPSTResDTO), global::GPSTResDTO.Parser, new[]{ "YmdHms", "Offset", "PackageNow", "ErrCode", "Time" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class STValMO : pb::IMessage<STValMO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<STValMO> _parser = new pb::MessageParser<STValMO>(() => new STValMO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<STValMO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GPSTDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public STValMO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public STValMO(STValMO other) : this() {
    code_ = other.code_;
    dfltVal_ = other.dfltVal_;
    dfltTim_ = other.dfltTim_;
    rsltVal_ = other.rsltVal_;
    rsltTim_ = other.rsltTim_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public STValMO Clone() {
    return new STValMO(this);
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 1;
  private int code_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Code {
    get { return code_; }
    set {
      code_ = value;
    }
  }

  /// <summary>Field number for the "dflt_val" field.</summary>
  public const int DfltValFieldNumber = 2;
  private int dfltVal_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int DfltVal {
    get { return dfltVal_; }
    set {
      dfltVal_ = value;
    }
  }

  /// <summary>Field number for the "dflt_tim" field.</summary>
  public const int DfltTimFieldNumber = 3;
  private int dfltTim_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int DfltTim {
    get { return dfltTim_; }
    set {
      dfltTim_ = value;
    }
  }

  /// <summary>Field number for the "rslt_val" field.</summary>
  public const int RsltValFieldNumber = 4;
  private int rsltVal_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RsltVal {
    get { return rsltVal_; }
    set {
      rsltVal_ = value;
    }
  }

  /// <summary>Field number for the "rslt_tim" field.</summary>
  public const int RsltTimFieldNumber = 5;
  private int rsltTim_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RsltTim {
    get { return rsltTim_; }
    set {
      rsltTim_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as STValMO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(STValMO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Code != other.Code) return false;
    if (DfltVal != other.DfltVal) return false;
    if (DfltTim != other.DfltTim) return false;
    if (RsltVal != other.RsltVal) return false;
    if (RsltTim != other.RsltTim) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Code != 0) hash ^= Code.GetHashCode();
    if (DfltVal != 0) hash ^= DfltVal.GetHashCode();
    if (DfltTim != 0) hash ^= DfltTim.GetHashCode();
    if (RsltVal != 0) hash ^= RsltVal.GetHashCode();
    if (RsltTim != 0) hash ^= RsltTim.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Code != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Code);
    }
    if (DfltVal != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(DfltVal);
    }
    if (DfltTim != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(DfltTim);
    }
    if (RsltVal != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(RsltVal);
    }
    if (RsltTim != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(RsltTim);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Code != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Code);
    }
    if (DfltVal != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(DfltVal);
    }
    if (DfltTim != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(DfltTim);
    }
    if (RsltVal != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(RsltVal);
    }
    if (RsltTim != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(RsltTim);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Code != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
    }
    if (DfltVal != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(DfltVal);
    }
    if (DfltTim != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(DfltTim);
    }
    if (RsltVal != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RsltVal);
    }
    if (RsltTim != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RsltTim);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(STValMO other) {
    if (other == null) {
      return;
    }
    if (other.Code != 0) {
      Code = other.Code;
    }
    if (other.DfltVal != 0) {
      DfltVal = other.DfltVal;
    }
    if (other.DfltTim != 0) {
      DfltTim = other.DfltTim;
    }
    if (other.RsltVal != 0) {
      RsltVal = other.RsltVal;
    }
    if (other.RsltTim != 0) {
      RsltTim = other.RsltTim;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Code = input.ReadInt32();
          break;
        }
        case 16: {
          DfltVal = input.ReadInt32();
          break;
        }
        case 24: {
          DfltTim = input.ReadInt32();
          break;
        }
        case 32: {
          RsltVal = input.ReadInt32();
          break;
        }
        case 40: {
          RsltTim = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Code = input.ReadInt32();
          break;
        }
        case 16: {
          DfltVal = input.ReadInt32();
          break;
        }
        case 24: {
          DfltTim = input.ReadInt32();
          break;
        }
        case 32: {
          RsltVal = input.ReadInt32();
          break;
        }
        case 40: {
          RsltTim = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GPSTValMO : pb::IMessage<GPSTValMO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GPSTValMO> _parser = new pb::MessageParser<GPSTValMO>(() => new GPSTValMO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GPSTValMO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GPSTDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GPSTValMO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GPSTValMO(GPSTValMO other) : this() {
    pvSn_ = other.pvSn_;
    ver_ = other.ver_;
    st_ = other.st_;
    gpf_ = other.gpf_;
    gpfVer_ = other.gpfVer_;
    hv1Stval_ = other.hv1Stval_ != null ? other.hv1Stval_.Clone() : null;
    lv1Stval_ = other.lv1Stval_ != null ? other.lv1Stval_.Clone() : null;
    hv2Stval_ = other.hv2Stval_ != null ? other.hv2Stval_.Clone() : null;
    lv2Stval_ = other.lv2Stval_ != null ? other.lv2Stval_.Clone() : null;
    hf1Stval_ = other.hf1Stval_ != null ? other.hf1Stval_.Clone() : null;
    lf1Stval_ = other.lf1Stval_ != null ? other.lf1Stval_.Clone() : null;
    hf2Stval_ = other.hf2Stval_ != null ? other.hf2Stval_.Clone() : null;
    lf2Stval_ = other.lf2Stval_ != null ? other.lf2Stval_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GPSTValMO Clone() {
    return new GPSTValMO(this);
  }

  /// <summary>Field number for the "pv_sn" field.</summary>
  public const int PvSnFieldNumber = 1;
  private long pvSn_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long PvSn {
    get { return pvSn_; }
    set {
      pvSn_ = value;
    }
  }

  /// <summary>Field number for the "ver" field.</summary>
  public const int VerFieldNumber = 2;
  private int ver_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Ver {
    get { return ver_; }
    set {
      ver_ = value;
    }
  }

  /// <summary>Field number for the "st" field.</summary>
  public const int StFieldNumber = 3;
  private int st_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int St {
    get { return st_; }
    set {
      st_ = value;
    }
  }

  /// <summary>Field number for the "gpf" field.</summary>
  public const int GpfFieldNumber = 4;
  private int gpf_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Gpf {
    get { return gpf_; }
    set {
      gpf_ = value;
    }
  }

  /// <summary>Field number for the "gpf_ver" field.</summary>
  public const int GpfVerFieldNumber = 5;
  private int gpfVer_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GpfVer {
    get { return gpfVer_; }
    set {
      gpfVer_ = value;
    }
  }

  /// <summary>Field number for the "hv1_stval" field.</summary>
  public const int Hv1StvalFieldNumber = 6;
  private global::STValMO hv1Stval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::STValMO Hv1Stval {
    get { return hv1Stval_; }
    set {
      hv1Stval_ = value;
    }
  }

  /// <summary>Field number for the "lv1_stval" field.</summary>
  public const int Lv1StvalFieldNumber = 7;
  private global::STValMO lv1Stval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::STValMO Lv1Stval {
    get { return lv1Stval_; }
    set {
      lv1Stval_ = value;
    }
  }

  /// <summary>Field number for the "hv2_stval" field.</summary>
  public const int Hv2StvalFieldNumber = 8;
  private global::STValMO hv2Stval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::STValMO Hv2Stval {
    get { return hv2Stval_; }
    set {
      hv2Stval_ = value;
    }
  }

  /// <summary>Field number for the "lv2_stval" field.</summary>
  public const int Lv2StvalFieldNumber = 9;
  private global::STValMO lv2Stval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::STValMO Lv2Stval {
    get { return lv2Stval_; }
    set {
      lv2Stval_ = value;
    }
  }

  /// <summary>Field number for the "hf1_stval" field.</summary>
  public const int Hf1StvalFieldNumber = 10;
  private global::STValMO hf1Stval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::STValMO Hf1Stval {
    get { return hf1Stval_; }
    set {
      hf1Stval_ = value;
    }
  }

  /// <summary>Field number for the "lf1_stval" field.</summary>
  public const int Lf1StvalFieldNumber = 11;
  private global::STValMO lf1Stval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::STValMO Lf1Stval {
    get { return lf1Stval_; }
    set {
      lf1Stval_ = value;
    }
  }

  /// <summary>Field number for the "hf2_stval" field.</summary>
  public const int Hf2StvalFieldNumber = 12;
  private global::STValMO hf2Stval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::STValMO Hf2Stval {
    get { return hf2Stval_; }
    set {
      hf2Stval_ = value;
    }
  }

  /// <summary>Field number for the "lf2_stval" field.</summary>
  public const int Lf2StvalFieldNumber = 13;
  private global::STValMO lf2Stval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::STValMO Lf2Stval {
    get { return lf2Stval_; }
    set {
      lf2Stval_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GPSTValMO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GPSTValMO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PvSn != other.PvSn) return false;
    if (Ver != other.Ver) return false;
    if (St != other.St) return false;
    if (Gpf != other.Gpf) return false;
    if (GpfVer != other.GpfVer) return false;
    if (!object.Equals(Hv1Stval, other.Hv1Stval)) return false;
    if (!object.Equals(Lv1Stval, other.Lv1Stval)) return false;
    if (!object.Equals(Hv2Stval, other.Hv2Stval)) return false;
    if (!object.Equals(Lv2Stval, other.Lv2Stval)) return false;
    if (!object.Equals(Hf1Stval, other.Hf1Stval)) return false;
    if (!object.Equals(Lf1Stval, other.Lf1Stval)) return false;
    if (!object.Equals(Hf2Stval, other.Hf2Stval)) return false;
    if (!object.Equals(Lf2Stval, other.Lf2Stval)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (PvSn != 0L) hash ^= PvSn.GetHashCode();
    if (Ver != 0) hash ^= Ver.GetHashCode();
    if (St != 0) hash ^= St.GetHashCode();
    if (Gpf != 0) hash ^= Gpf.GetHashCode();
    if (GpfVer != 0) hash ^= GpfVer.GetHashCode();
    if (hv1Stval_ != null) hash ^= Hv1Stval.GetHashCode();
    if (lv1Stval_ != null) hash ^= Lv1Stval.GetHashCode();
    if (hv2Stval_ != null) hash ^= Hv2Stval.GetHashCode();
    if (lv2Stval_ != null) hash ^= Lv2Stval.GetHashCode();
    if (hf1Stval_ != null) hash ^= Hf1Stval.GetHashCode();
    if (lf1Stval_ != null) hash ^= Lf1Stval.GetHashCode();
    if (hf2Stval_ != null) hash ^= Hf2Stval.GetHashCode();
    if (lf2Stval_ != null) hash ^= Lf2Stval.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (PvSn != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(PvSn);
    }
    if (Ver != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Ver);
    }
    if (St != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(St);
    }
    if (Gpf != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Gpf);
    }
    if (GpfVer != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(GpfVer);
    }
    if (hv1Stval_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(Hv1Stval);
    }
    if (lv1Stval_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(Lv1Stval);
    }
    if (hv2Stval_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(Hv2Stval);
    }
    if (lv2Stval_ != null) {
      output.WriteRawTag(74);
      output.WriteMessage(Lv2Stval);
    }
    if (hf1Stval_ != null) {
      output.WriteRawTag(82);
      output.WriteMessage(Hf1Stval);
    }
    if (lf1Stval_ != null) {
      output.WriteRawTag(90);
      output.WriteMessage(Lf1Stval);
    }
    if (hf2Stval_ != null) {
      output.WriteRawTag(98);
      output.WriteMessage(Hf2Stval);
    }
    if (lf2Stval_ != null) {
      output.WriteRawTag(106);
      output.WriteMessage(Lf2Stval);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (PvSn != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(PvSn);
    }
    if (Ver != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Ver);
    }
    if (St != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(St);
    }
    if (Gpf != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Gpf);
    }
    if (GpfVer != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(GpfVer);
    }
    if (hv1Stval_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(Hv1Stval);
    }
    if (lv1Stval_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(Lv1Stval);
    }
    if (hv2Stval_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(Hv2Stval);
    }
    if (lv2Stval_ != null) {
      output.WriteRawTag(74);
      output.WriteMessage(Lv2Stval);
    }
    if (hf1Stval_ != null) {
      output.WriteRawTag(82);
      output.WriteMessage(Hf1Stval);
    }
    if (lf1Stval_ != null) {
      output.WriteRawTag(90);
      output.WriteMessage(Lf1Stval);
    }
    if (hf2Stval_ != null) {
      output.WriteRawTag(98);
      output.WriteMessage(Hf2Stval);
    }
    if (lf2Stval_ != null) {
      output.WriteRawTag(106);
      output.WriteMessage(Lf2Stval);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (PvSn != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(PvSn);
    }
    if (Ver != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Ver);
    }
    if (St != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(St);
    }
    if (Gpf != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gpf);
    }
    if (GpfVer != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GpfVer);
    }
    if (hv1Stval_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Hv1Stval);
    }
    if (lv1Stval_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Lv1Stval);
    }
    if (hv2Stval_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Hv2Stval);
    }
    if (lv2Stval_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Lv2Stval);
    }
    if (hf1Stval_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Hf1Stval);
    }
    if (lf1Stval_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Lf1Stval);
    }
    if (hf2Stval_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Hf2Stval);
    }
    if (lf2Stval_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Lf2Stval);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GPSTValMO other) {
    if (other == null) {
      return;
    }
    if (other.PvSn != 0L) {
      PvSn = other.PvSn;
    }
    if (other.Ver != 0) {
      Ver = other.Ver;
    }
    if (other.St != 0) {
      St = other.St;
    }
    if (other.Gpf != 0) {
      Gpf = other.Gpf;
    }
    if (other.GpfVer != 0) {
      GpfVer = other.GpfVer;
    }
    if (other.hv1Stval_ != null) {
      if (hv1Stval_ == null) {
        Hv1Stval = new global::STValMO();
      }
      Hv1Stval.MergeFrom(other.Hv1Stval);
    }
    if (other.lv1Stval_ != null) {
      if (lv1Stval_ == null) {
        Lv1Stval = new global::STValMO();
      }
      Lv1Stval.MergeFrom(other.Lv1Stval);
    }
    if (other.hv2Stval_ != null) {
      if (hv2Stval_ == null) {
        Hv2Stval = new global::STValMO();
      }
      Hv2Stval.MergeFrom(other.Hv2Stval);
    }
    if (other.lv2Stval_ != null) {
      if (lv2Stval_ == null) {
        Lv2Stval = new global::STValMO();
      }
      Lv2Stval.MergeFrom(other.Lv2Stval);
    }
    if (other.hf1Stval_ != null) {
      if (hf1Stval_ == null) {
        Hf1Stval = new global::STValMO();
      }
      Hf1Stval.MergeFrom(other.Hf1Stval);
    }
    if (other.lf1Stval_ != null) {
      if (lf1Stval_ == null) {
        Lf1Stval = new global::STValMO();
      }
      Lf1Stval.MergeFrom(other.Lf1Stval);
    }
    if (other.hf2Stval_ != null) {
      if (hf2Stval_ == null) {
        Hf2Stval = new global::STValMO();
      }
      Hf2Stval.MergeFrom(other.Hf2Stval);
    }
    if (other.lf2Stval_ != null) {
      if (lf2Stval_ == null) {
        Lf2Stval = new global::STValMO();
      }
      Lf2Stval.MergeFrom(other.Lf2Stval);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PvSn = input.ReadInt64();
          break;
        }
        case 16: {
          Ver = input.ReadInt32();
          break;
        }
        case 24: {
          St = input.ReadInt32();
          break;
        }
        case 32: {
          Gpf = input.ReadInt32();
          break;
        }
        case 40: {
          GpfVer = input.ReadInt32();
          break;
        }
        case 50: {
          if (hv1Stval_ == null) {
            Hv1Stval = new global::STValMO();
          }
          input.ReadMessage(Hv1Stval);
          break;
        }
        case 58: {
          if (lv1Stval_ == null) {
            Lv1Stval = new global::STValMO();
          }
          input.ReadMessage(Lv1Stval);
          break;
        }
        case 66: {
          if (hv2Stval_ == null) {
            Hv2Stval = new global::STValMO();
          }
          input.ReadMessage(Hv2Stval);
          break;
        }
        case 74: {
          if (lv2Stval_ == null) {
            Lv2Stval = new global::STValMO();
          }
          input.ReadMessage(Lv2Stval);
          break;
        }
        case 82: {
          if (hf1Stval_ == null) {
            Hf1Stval = new global::STValMO();
          }
          input.ReadMessage(Hf1Stval);
          break;
        }
        case 90: {
          if (lf1Stval_ == null) {
            Lf1Stval = new global::STValMO();
          }
          input.ReadMessage(Lf1Stval);
          break;
        }
        case 98: {
          if (hf2Stval_ == null) {
            Hf2Stval = new global::STValMO();
          }
          input.ReadMessage(Hf2Stval);
          break;
        }
        case 106: {
          if (lf2Stval_ == null) {
            Lf2Stval = new global::STValMO();
          }
          input.ReadMessage(Lf2Stval);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          PvSn = input.ReadInt64();
          break;
        }
        case 16: {
          Ver = input.ReadInt32();
          break;
        }
        case 24: {
          St = input.ReadInt32();
          break;
        }
        case 32: {
          Gpf = input.ReadInt32();
          break;
        }
        case 40: {
          GpfVer = input.ReadInt32();
          break;
        }
        case 50: {
          if (hv1Stval_ == null) {
            Hv1Stval = new global::STValMO();
          }
          input.ReadMessage(Hv1Stval);
          break;
        }
        case 58: {
          if (lv1Stval_ == null) {
            Lv1Stval = new global::STValMO();
          }
          input.ReadMessage(Lv1Stval);
          break;
        }
        case 66: {
          if (hv2Stval_ == null) {
            Hv2Stval = new global::STValMO();
          }
          input.ReadMessage(Hv2Stval);
          break;
        }
        case 74: {
          if (lv2Stval_ == null) {
            Lv2Stval = new global::STValMO();
          }
          input.ReadMessage(Lv2Stval);
          break;
        }
        case 82: {
          if (hf1Stval_ == null) {
            Hf1Stval = new global::STValMO();
          }
          input.ReadMessage(Hf1Stval);
          break;
        }
        case 90: {
          if (lf1Stval_ == null) {
            Lf1Stval = new global::STValMO();
          }
          input.ReadMessage(Lf1Stval);
          break;
        }
        case 98: {
          if (hf2Stval_ == null) {
            Hf2Stval = new global::STValMO();
          }
          input.ReadMessage(Hf2Stval);
          break;
        }
        case 106: {
          if (lf2Stval_ == null) {
            Lf2Stval = new global::STValMO();
          }
          input.ReadMessage(Lf2Stval);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GPSTReqDTO : pb::IMessage<GPSTReqDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GPSTReqDTO> _parser = new pb::MessageParser<GPSTReqDTO>(() => new GPSTReqDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GPSTReqDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GPSTDataReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GPSTReqDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GPSTReqDTO(GPSTReqDTO other) : this() {
    dtuSn_ = other.dtuSn_;
    time_ = other.time_;
    packageNub_ = other.packageNub_;
    packageNow_ = other.packageNow_;
    mGPSTInfo_ = other.mGPSTInfo_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GPSTReqDTO Clone() {
    return new GPSTReqDTO(this);
  }

  /// <summary>Field number for the "dtu_sn" field.</summary>
  public const int DtuSnFieldNumber = 1;
  private string dtuSn_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DtuSn {
    get { return dtuSn_; }
    set {
      dtuSn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private int time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  /// <summary>Field number for the "package_nub" field.</summary>
  public const int PackageNubFieldNumber = 3;
  private int packageNub_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PackageNub {
    get { return packageNub_; }
    set {
      packageNub_ = value;
    }
  }

  /// <summary>Field number for the "package_now" field.</summary>
  public const int PackageNowFieldNumber = 4;
  private int packageNow_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PackageNow {
    get { return packageNow_; }
    set {
      packageNow_ = value;
    }
  }

  /// <summary>Field number for the "mGPSTInfo" field.</summary>
  public const int MGPSTInfoFieldNumber = 5;
  private static readonly pb::FieldCodec<global::GPSTValMO> _repeated_mGPSTInfo_codec
      = pb::FieldCodec.ForMessage(42, global::GPSTValMO.Parser);
  private readonly pbc::RepeatedField<global::GPSTValMO> mGPSTInfo_ = new pbc::RepeatedField<global::GPSTValMO>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::GPSTValMO> MGPSTInfo {
    get { return mGPSTInfo_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GPSTReqDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GPSTReqDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (DtuSn != other.DtuSn) return false;
    if (Time != other.Time) return false;
    if (PackageNub != other.PackageNub) return false;
    if (PackageNow != other.PackageNow) return false;
    if(!mGPSTInfo_.Equals(other.mGPSTInfo_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (DtuSn.Length != 0) hash ^= DtuSn.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (PackageNub != 0) hash ^= PackageNub.GetHashCode();
    if (PackageNow != 0) hash ^= PackageNow.GetHashCode();
    hash ^= mGPSTInfo_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (DtuSn.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DtuSn);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Time);
    }
    if (PackageNub != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PackageNub);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(PackageNow);
    }
    mGPSTInfo_.WriteTo(output, _repeated_mGPSTInfo_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (DtuSn.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DtuSn);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Time);
    }
    if (PackageNub != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PackageNub);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(PackageNow);
    }
    mGPSTInfo_.WriteTo(ref output, _repeated_mGPSTInfo_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (DtuSn.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DtuSn);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
    }
    if (PackageNub != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PackageNub);
    }
    if (PackageNow != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PackageNow);
    }
    size += mGPSTInfo_.CalculateSize(_repeated_mGPSTInfo_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GPSTReqDTO other) {
    if (other == null) {
      return;
    }
    if (other.DtuSn.Length != 0) {
      DtuSn = other.DtuSn;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    if (other.PackageNub != 0) {
      PackageNub = other.PackageNub;
    }
    if (other.PackageNow != 0) {
      PackageNow = other.PackageNow;
    }
    mGPSTInfo_.Add(other.mGPSTInfo_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          DtuSn = input.ReadString();
          break;
        }
        case 16: {
          Time = input.ReadInt32();
          break;
        }
        case 24: {
          PackageNub = input.ReadInt32();
          break;
        }
        case 32: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 42: {
          mGPSTInfo_.AddEntriesFrom(input, _repeated_mGPSTInfo_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          DtuSn = input.ReadString();
          break;
        }
        case 16: {
          Time = input.ReadInt32();
          break;
        }
        case 24: {
          PackageNub = input.ReadInt32();
          break;
        }
        case 32: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 42: {
          mGPSTInfo_.AddEntriesFrom(ref input, _repeated_mGPSTInfo_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GPSTResDTO : pb::IMessage<GPSTResDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GPSTResDTO> _parser = new pb::MessageParser<GPSTResDTO>(() => new GPSTResDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GPSTResDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GPSTDataReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GPSTResDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GPSTResDTO(GPSTResDTO other) : this() {
    ymdHms_ = other.ymdHms_;
    offset_ = other.offset_;
    packageNow_ = other.packageNow_;
    errCode_ = other.errCode_;
    time_ = other.time_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GPSTResDTO Clone() {
    return new GPSTResDTO(this);
  }

  /// <summary>Field number for the "ymd_hms" field.</summary>
  public const int YmdHmsFieldNumber = 1;
  private string ymdHms_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string YmdHms {
    get { return ymdHms_; }
    set {
      ymdHms_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 2;
  private int offset_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Offset {
    get { return offset_; }
    set {
      offset_ = value;
    }
  }

  /// <summary>Field number for the "package_now" field.</summary>
  public const int PackageNowFieldNumber = 3;
  private int packageNow_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PackageNow {
    get { return packageNow_; }
    set {
      packageNow_ = value;
    }
  }

  /// <summary>Field number for the "err_code" field.</summary>
  public const int ErrCodeFieldNumber = 4;
  private int errCode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ErrCode {
    get { return errCode_; }
    set {
      errCode_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 5;
  private int time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GPSTResDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GPSTResDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (YmdHms != other.YmdHms) return false;
    if (Offset != other.Offset) return false;
    if (PackageNow != other.PackageNow) return false;
    if (ErrCode != other.ErrCode) return false;
    if (Time != other.Time) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (YmdHms.Length != 0) hash ^= YmdHms.GetHashCode();
    if (Offset != 0) hash ^= Offset.GetHashCode();
    if (PackageNow != 0) hash ^= PackageNow.GetHashCode();
    if (ErrCode != 0) hash ^= ErrCode.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (YmdHms.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(YmdHms);
    }
    if (Offset != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Offset);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PackageNow);
    }
    if (ErrCode != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(ErrCode);
    }
    if (Time != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (YmdHms.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(YmdHms);
    }
    if (Offset != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Offset);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PackageNow);
    }
    if (ErrCode != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(ErrCode);
    }
    if (Time != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (YmdHms.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(YmdHms);
    }
    if (Offset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
    }
    if (PackageNow != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PackageNow);
    }
    if (ErrCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrCode);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GPSTResDTO other) {
    if (other == null) {
      return;
    }
    if (other.YmdHms.Length != 0) {
      YmdHms = other.YmdHms;
    }
    if (other.Offset != 0) {
      Offset = other.Offset;
    }
    if (other.PackageNow != 0) {
      PackageNow = other.PackageNow;
    }
    if (other.ErrCode != 0) {
      ErrCode = other.ErrCode;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          YmdHms = input.ReadString();
          break;
        }
        case 16: {
          Offset = input.ReadInt32();
          break;
        }
        case 24: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 32: {
          ErrCode = input.ReadInt32();
          break;
        }
        case 40: {
          Time = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          YmdHms = input.ReadString();
          break;
        }
        case 16: {
          Offset = input.ReadInt32();
          break;
        }
        case 24: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 32: {
          ErrCode = input.ReadInt32();
          break;
        }
        case 40: {
          Time = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
