// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NetworkInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from NetworkInfo.proto</summary>
public static partial class NetworkInfoReflection {

  #region Descriptor
  /// <summary>File descriptor for NetworkInfo.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static NetworkInfoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFOZXR3b3JrSW5mby5wcm90byLbAQoRTmV0d29ya0luZm9SZXFEVE8SDgoG",
          "ZHR1X3NuGAEgASgJEgwKBHRpbWUYAiABKA0SEwoLbmV0X3NldF9tb2QYAyAB",
          "KAUSFAoMbmV0X3NldF90aW1lGAQgASgFEhUKDW5ldF9zZXRfc3RhdGUYBSAB",
          "KAUSFAoMbmV0X3dvcmtfbW9kGAYgASgFEhUKDW5ldF93b3JrX3RpbWUYByAB",
          "KAUSCwoDY3NxGAggASgFEhYKDm5ldF93b3JrX3N0YXRlGAkgASgFEhQKDGFw",
          "X3NldF9zdGF0ZRgKIAEoBSIxChFOZXR3b3JrSW5mb1Jlc0RUTxIOCgZvZmZz",
          "ZXQYASABKAUSDAoEdGltZRgCIAEoDWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::NetworkInfoReqDTO), global::NetworkInfoReqDTO.Parser, new[]{ "DtuSn", "Time", "NetSetMod", "NetSetTime", "NetSetState", "NetWorkMod", "NetWorkTime", "Csq", "NetWorkState", "ApSetState" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NetworkInfoResDTO), global::NetworkInfoResDTO.Parser, new[]{ "Offset", "Time" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class NetworkInfoReqDTO : pb::IMessage<NetworkInfoReqDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NetworkInfoReqDTO> _parser = new pb::MessageParser<NetworkInfoReqDTO>(() => new NetworkInfoReqDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NetworkInfoReqDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::NetworkInfoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NetworkInfoReqDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NetworkInfoReqDTO(NetworkInfoReqDTO other) : this() {
    dtuSn_ = other.dtuSn_;
    time_ = other.time_;
    netSetMod_ = other.netSetMod_;
    netSetTime_ = other.netSetTime_;
    netSetState_ = other.netSetState_;
    netWorkMod_ = other.netWorkMod_;
    netWorkTime_ = other.netWorkTime_;
    csq_ = other.csq_;
    netWorkState_ = other.netWorkState_;
    apSetState_ = other.apSetState_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NetworkInfoReqDTO Clone() {
    return new NetworkInfoReqDTO(this);
  }

  /// <summary>Field number for the "dtu_sn" field.</summary>
  public const int DtuSnFieldNumber = 1;
  private string dtuSn_ = "";
  /// <summary>
  /// DTU serial number
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DtuSn {
    get { return dtuSn_; }
    set {
      dtuSn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private uint time_;
  /// <summary>
  /// Timestamp of the request
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  /// <summary>Field number for the "net_set_mod" field.</summary>
  public const int NetSetModFieldNumber = 3;
  private int netSetMod_;
  /// <summary>
  /// Network setting mode
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NetSetMod {
    get { return netSetMod_; }
    set {
      netSetMod_ = value;
    }
  }

  /// <summary>Field number for the "net_set_time" field.</summary>
  public const int NetSetTimeFieldNumber = 4;
  private int netSetTime_;
  /// <summary>
  /// Network setting time
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NetSetTime {
    get { return netSetTime_; }
    set {
      netSetTime_ = value;
    }
  }

  /// <summary>Field number for the "net_set_state" field.</summary>
  public const int NetSetStateFieldNumber = 5;
  private int netSetState_;
  /// <summary>
  /// Network setting state
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NetSetState {
    get { return netSetState_; }
    set {
      netSetState_ = value;
    }
  }

  /// <summary>Field number for the "net_work_mod" field.</summary>
  public const int NetWorkModFieldNumber = 6;
  private int netWorkMod_;
  /// <summary>
  /// Network working mode
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NetWorkMod {
    get { return netWorkMod_; }
    set {
      netWorkMod_ = value;
    }
  }

  /// <summary>Field number for the "net_work_time" field.</summary>
  public const int NetWorkTimeFieldNumber = 7;
  private int netWorkTime_;
  /// <summary>
  /// Network working time
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NetWorkTime {
    get { return netWorkTime_; }
    set {
      netWorkTime_ = value;
    }
  }

  /// <summary>Field number for the "csq" field.</summary>
  public const int CsqFieldNumber = 8;
  private int csq_;
  /// <summary>
  /// Carrier Signal Quality (CSQ)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Csq {
    get { return csq_; }
    set {
      csq_ = value;
    }
  }

  /// <summary>Field number for the "net_work_state" field.</summary>
  public const int NetWorkStateFieldNumber = 9;
  private int netWorkState_;
  /// <summary>
  /// Network working state
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NetWorkState {
    get { return netWorkState_; }
    set {
      netWorkState_ = value;
    }
  }

  /// <summary>Field number for the "ap_set_state" field.</summary>
  public const int ApSetStateFieldNumber = 10;
  private int apSetState_;
  /// <summary>
  /// Access Point (AP) setting state
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ApSetState {
    get { return apSetState_; }
    set {
      apSetState_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NetworkInfoReqDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NetworkInfoReqDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (DtuSn != other.DtuSn) return false;
    if (Time != other.Time) return false;
    if (NetSetMod != other.NetSetMod) return false;
    if (NetSetTime != other.NetSetTime) return false;
    if (NetSetState != other.NetSetState) return false;
    if (NetWorkMod != other.NetWorkMod) return false;
    if (NetWorkTime != other.NetWorkTime) return false;
    if (Csq != other.Csq) return false;
    if (NetWorkState != other.NetWorkState) return false;
    if (ApSetState != other.ApSetState) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (DtuSn.Length != 0) hash ^= DtuSn.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (NetSetMod != 0) hash ^= NetSetMod.GetHashCode();
    if (NetSetTime != 0) hash ^= NetSetTime.GetHashCode();
    if (NetSetState != 0) hash ^= NetSetState.GetHashCode();
    if (NetWorkMod != 0) hash ^= NetWorkMod.GetHashCode();
    if (NetWorkTime != 0) hash ^= NetWorkTime.GetHashCode();
    if (Csq != 0) hash ^= Csq.GetHashCode();
    if (NetWorkState != 0) hash ^= NetWorkState.GetHashCode();
    if (ApSetState != 0) hash ^= ApSetState.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (DtuSn.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DtuSn);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Time);
    }
    if (NetSetMod != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(NetSetMod);
    }
    if (NetSetTime != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NetSetTime);
    }
    if (NetSetState != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(NetSetState);
    }
    if (NetWorkMod != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(NetWorkMod);
    }
    if (NetWorkTime != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(NetWorkTime);
    }
    if (Csq != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(Csq);
    }
    if (NetWorkState != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(NetWorkState);
    }
    if (ApSetState != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(ApSetState);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (DtuSn.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DtuSn);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Time);
    }
    if (NetSetMod != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(NetSetMod);
    }
    if (NetSetTime != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NetSetTime);
    }
    if (NetSetState != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(NetSetState);
    }
    if (NetWorkMod != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(NetWorkMod);
    }
    if (NetWorkTime != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(NetWorkTime);
    }
    if (Csq != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(Csq);
    }
    if (NetWorkState != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(NetWorkState);
    }
    if (ApSetState != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(ApSetState);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (DtuSn.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DtuSn);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Time);
    }
    if (NetSetMod != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NetSetMod);
    }
    if (NetSetTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NetSetTime);
    }
    if (NetSetState != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NetSetState);
    }
    if (NetWorkMod != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NetWorkMod);
    }
    if (NetWorkTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NetWorkTime);
    }
    if (Csq != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Csq);
    }
    if (NetWorkState != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NetWorkState);
    }
    if (ApSetState != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ApSetState);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NetworkInfoReqDTO other) {
    if (other == null) {
      return;
    }
    if (other.DtuSn.Length != 0) {
      DtuSn = other.DtuSn;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    if (other.NetSetMod != 0) {
      NetSetMod = other.NetSetMod;
    }
    if (other.NetSetTime != 0) {
      NetSetTime = other.NetSetTime;
    }
    if (other.NetSetState != 0) {
      NetSetState = other.NetSetState;
    }
    if (other.NetWorkMod != 0) {
      NetWorkMod = other.NetWorkMod;
    }
    if (other.NetWorkTime != 0) {
      NetWorkTime = other.NetWorkTime;
    }
    if (other.Csq != 0) {
      Csq = other.Csq;
    }
    if (other.NetWorkState != 0) {
      NetWorkState = other.NetWorkState;
    }
    if (other.ApSetState != 0) {
      ApSetState = other.ApSetState;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          DtuSn = input.ReadString();
          break;
        }
        case 16: {
          Time = input.ReadUInt32();
          break;
        }
        case 24: {
          NetSetMod = input.ReadInt32();
          break;
        }
        case 32: {
          NetSetTime = input.ReadInt32();
          break;
        }
        case 40: {
          NetSetState = input.ReadInt32();
          break;
        }
        case 48: {
          NetWorkMod = input.ReadInt32();
          break;
        }
        case 56: {
          NetWorkTime = input.ReadInt32();
          break;
        }
        case 64: {
          Csq = input.ReadInt32();
          break;
        }
        case 72: {
          NetWorkState = input.ReadInt32();
          break;
        }
        case 80: {
          ApSetState = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          DtuSn = input.ReadString();
          break;
        }
        case 16: {
          Time = input.ReadUInt32();
          break;
        }
        case 24: {
          NetSetMod = input.ReadInt32();
          break;
        }
        case 32: {
          NetSetTime = input.ReadInt32();
          break;
        }
        case 40: {
          NetSetState = input.ReadInt32();
          break;
        }
        case 48: {
          NetWorkMod = input.ReadInt32();
          break;
        }
        case 56: {
          NetWorkTime = input.ReadInt32();
          break;
        }
        case 64: {
          Csq = input.ReadInt32();
          break;
        }
        case 72: {
          NetWorkState = input.ReadInt32();
          break;
        }
        case 80: {
          ApSetState = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class NetworkInfoResDTO : pb::IMessage<NetworkInfoResDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NetworkInfoResDTO> _parser = new pb::MessageParser<NetworkInfoResDTO>(() => new NetworkInfoResDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NetworkInfoResDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::NetworkInfoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NetworkInfoResDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NetworkInfoResDTO(NetworkInfoResDTO other) : this() {
    offset_ = other.offset_;
    time_ = other.time_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NetworkInfoResDTO Clone() {
    return new NetworkInfoResDTO(this);
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 1;
  private int offset_;
  /// <summary>
  /// Offset value for response
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Offset {
    get { return offset_; }
    set {
      offset_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private uint time_;
  /// <summary>
  /// Timestamp of the response
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NetworkInfoResDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NetworkInfoResDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Offset != other.Offset) return false;
    if (Time != other.Time) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Offset != 0) hash ^= Offset.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Offset != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Offset != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Offset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NetworkInfoResDTO other) {
    if (other == null) {
      return;
    }
    if (other.Offset != 0) {
      Offset = other.Offset;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Offset = input.ReadInt32();
          break;
        }
        case 16: {
          Time = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Offset = input.ReadInt32();
          break;
        }
        case 16: {
          Time = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
