// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WarnData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from WarnData.proto</summary>
public static partial class WarnDataReflection {

  #region Descriptor
  /// <summary>File descriptor for WarnData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static WarnDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5XYXJuRGF0YS5wcm90byKBAQoKV2FyblJlcURUTxIOCgZkdHVfc24YASAB",
          "KAkSDAoEdGltZRgCIAEoBRITCgtwYWNrYWdlX251YhgDIAEoBRITCgtwYWNr",
          "YWdlX25vdxgEIAEoBRITCgt3YXJuX2RldmljZRgFIAEoBRIWCgV3YXJucxgG",
          "IAMoCzIHLldhcm5NTyJ0CgZXYXJuTU8SDQoFcHZfc24YASABKAMSDAoEY29k",
          "ZRgCIAEoBRILCgNudW0YAyABKAUSDgoGc190aW1lGAQgASgFEg4KBmVfdGlt",
          "ZRgFIAEoBRIPCgd3X2RhdGExGAYgASgFEg8KB3dfZGF0YTIYByABKAUiYgoK",
          "V2FyblJlc0RUTxIPCgd5bWRfaG1zGAEgASgJEhMKC3BhY2thZ2Vfbm93GAIg",
          "ASgFEhAKCGVycl9jb2RlGAMgASgFEg4KBm9mZnNldBgEIAEoBRIMCgR0aW1l",
          "GAUgASgFIsMBCgpXYXZlUmVxRFRPEg4KBmR0dV9zbhgBIAEoCRIMCgR0aW1l",
          "GAIgASgFEhMKC3BhY2thZ2VfbnViGAMgASgFEhMKC3BhY2thZ2Vfbm93GAQg",
          "ASgFEg0KBXB2X3NuGAUgASgDEgwKBGNvZGUYBiABKAUSCwoDbnVtGAcgASgF",
          "EhEKCXdhcm5fdGltZRgIIAEoBRIQCghkYXRhX2xlbhgJIAEoBRILCgNwb3MY",
          "CiABKAUSEQoJd2Fybl9kYXRhGAsgASgJImIKCldhdmVSZXNEVE8SDwoHeW1k",
          "X2htcxgBIAEoCRITCgtwYWNrYWdlX25vdxgCIAEoBRIQCghlcnJfY29kZRgD",
          "IAEoBRIOCgZvZmZzZXQYBCABKAUSDAoEdGltZRgFIAEoBWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::WarnReqDTO), global::WarnReqDTO.Parser, new[]{ "DtuSn", "Time", "PackageNub", "PackageNow", "WarnDevice", "Warns" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WarnMO), global::WarnMO.Parser, new[]{ "PvSn", "Code", "Num", "STime", "ETime", "WData1", "WData2" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WarnResDTO), global::WarnResDTO.Parser, new[]{ "YmdHms", "PackageNow", "ErrCode", "Offset", "Time" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WaveReqDTO), global::WaveReqDTO.Parser, new[]{ "DtuSn", "Time", "PackageNub", "PackageNow", "PvSn", "Code", "Num", "WarnTime", "DataLen", "Pos", "WarnData" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WaveResDTO), global::WaveResDTO.Parser, new[]{ "YmdHms", "PackageNow", "ErrCode", "Offset", "Time" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class WarnReqDTO : pb::IMessage<WarnReqDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WarnReqDTO> _parser = new pb::MessageParser<WarnReqDTO>(() => new WarnReqDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<WarnReqDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WarnDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WarnReqDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WarnReqDTO(WarnReqDTO other) : this() {
    dtuSn_ = other.dtuSn_;
    time_ = other.time_;
    packageNub_ = other.packageNub_;
    packageNow_ = other.packageNow_;
    warnDevice_ = other.warnDevice_;
    warns_ = other.warns_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WarnReqDTO Clone() {
    return new WarnReqDTO(this);
  }

  /// <summary>Field number for the "dtu_sn" field.</summary>
  public const int DtuSnFieldNumber = 1;
  private string dtuSn_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DtuSn {
    get { return dtuSn_; }
    set {
      dtuSn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private int time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  /// <summary>Field number for the "package_nub" field.</summary>
  public const int PackageNubFieldNumber = 3;
  private int packageNub_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PackageNub {
    get { return packageNub_; }
    set {
      packageNub_ = value;
    }
  }

  /// <summary>Field number for the "package_now" field.</summary>
  public const int PackageNowFieldNumber = 4;
  private int packageNow_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PackageNow {
    get { return packageNow_; }
    set {
      packageNow_ = value;
    }
  }

  /// <summary>Field number for the "warn_device" field.</summary>
  public const int WarnDeviceFieldNumber = 5;
  private int warnDevice_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WarnDevice {
    get { return warnDevice_; }
    set {
      warnDevice_ = value;
    }
  }

  /// <summary>Field number for the "warns" field.</summary>
  public const int WarnsFieldNumber = 6;
  private static readonly pb::FieldCodec<global::WarnMO> _repeated_warns_codec
      = pb::FieldCodec.ForMessage(50, global::WarnMO.Parser);
  private readonly pbc::RepeatedField<global::WarnMO> warns_ = new pbc::RepeatedField<global::WarnMO>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::WarnMO> Warns {
    get { return warns_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as WarnReqDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(WarnReqDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (DtuSn != other.DtuSn) return false;
    if (Time != other.Time) return false;
    if (PackageNub != other.PackageNub) return false;
    if (PackageNow != other.PackageNow) return false;
    if (WarnDevice != other.WarnDevice) return false;
    if(!warns_.Equals(other.warns_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (DtuSn.Length != 0) hash ^= DtuSn.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (PackageNub != 0) hash ^= PackageNub.GetHashCode();
    if (PackageNow != 0) hash ^= PackageNow.GetHashCode();
    if (WarnDevice != 0) hash ^= WarnDevice.GetHashCode();
    hash ^= warns_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (DtuSn.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DtuSn);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Time);
    }
    if (PackageNub != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PackageNub);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(PackageNow);
    }
    if (WarnDevice != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(WarnDevice);
    }
    warns_.WriteTo(output, _repeated_warns_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (DtuSn.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DtuSn);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Time);
    }
    if (PackageNub != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PackageNub);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(PackageNow);
    }
    if (WarnDevice != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(WarnDevice);
    }
    warns_.WriteTo(ref output, _repeated_warns_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (DtuSn.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DtuSn);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
    }
    if (PackageNub != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PackageNub);
    }
    if (PackageNow != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PackageNow);
    }
    if (WarnDevice != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(WarnDevice);
    }
    size += warns_.CalculateSize(_repeated_warns_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(WarnReqDTO other) {
    if (other == null) {
      return;
    }
    if (other.DtuSn.Length != 0) {
      DtuSn = other.DtuSn;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    if (other.PackageNub != 0) {
      PackageNub = other.PackageNub;
    }
    if (other.PackageNow != 0) {
      PackageNow = other.PackageNow;
    }
    if (other.WarnDevice != 0) {
      WarnDevice = other.WarnDevice;
    }
    warns_.Add(other.warns_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          DtuSn = input.ReadString();
          break;
        }
        case 16: {
          Time = input.ReadInt32();
          break;
        }
        case 24: {
          PackageNub = input.ReadInt32();
          break;
        }
        case 32: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 40: {
          WarnDevice = input.ReadInt32();
          break;
        }
        case 50: {
          warns_.AddEntriesFrom(input, _repeated_warns_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          DtuSn = input.ReadString();
          break;
        }
        case 16: {
          Time = input.ReadInt32();
          break;
        }
        case 24: {
          PackageNub = input.ReadInt32();
          break;
        }
        case 32: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 40: {
          WarnDevice = input.ReadInt32();
          break;
        }
        case 50: {
          warns_.AddEntriesFrom(ref input, _repeated_warns_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class WarnMO : pb::IMessage<WarnMO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WarnMO> _parser = new pb::MessageParser<WarnMO>(() => new WarnMO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<WarnMO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WarnDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WarnMO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WarnMO(WarnMO other) : this() {
    pvSn_ = other.pvSn_;
    code_ = other.code_;
    num_ = other.num_;
    sTime_ = other.sTime_;
    eTime_ = other.eTime_;
    wData1_ = other.wData1_;
    wData2_ = other.wData2_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WarnMO Clone() {
    return new WarnMO(this);
  }

  /// <summary>Field number for the "pv_sn" field.</summary>
  public const int PvSnFieldNumber = 1;
  private long pvSn_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long PvSn {
    get { return pvSn_; }
    set {
      pvSn_ = value;
    }
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 2;
  private int code_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Code {
    get { return code_; }
    set {
      code_ = value;
    }
  }

  /// <summary>Field number for the "num" field.</summary>
  public const int NumFieldNumber = 3;
  private int num_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Num {
    get { return num_; }
    set {
      num_ = value;
    }
  }

  /// <summary>Field number for the "s_time" field.</summary>
  public const int STimeFieldNumber = 4;
  private int sTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int STime {
    get { return sTime_; }
    set {
      sTime_ = value;
    }
  }

  /// <summary>Field number for the "e_time" field.</summary>
  public const int ETimeFieldNumber = 5;
  private int eTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ETime {
    get { return eTime_; }
    set {
      eTime_ = value;
    }
  }

  /// <summary>Field number for the "w_data1" field.</summary>
  public const int WData1FieldNumber = 6;
  private int wData1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WData1 {
    get { return wData1_; }
    set {
      wData1_ = value;
    }
  }

  /// <summary>Field number for the "w_data2" field.</summary>
  public const int WData2FieldNumber = 7;
  private int wData2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WData2 {
    get { return wData2_; }
    set {
      wData2_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as WarnMO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(WarnMO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PvSn != other.PvSn) return false;
    if (Code != other.Code) return false;
    if (Num != other.Num) return false;
    if (STime != other.STime) return false;
    if (ETime != other.ETime) return false;
    if (WData1 != other.WData1) return false;
    if (WData2 != other.WData2) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (PvSn != 0L) hash ^= PvSn.GetHashCode();
    if (Code != 0) hash ^= Code.GetHashCode();
    if (Num != 0) hash ^= Num.GetHashCode();
    if (STime != 0) hash ^= STime.GetHashCode();
    if (ETime != 0) hash ^= ETime.GetHashCode();
    if (WData1 != 0) hash ^= WData1.GetHashCode();
    if (WData2 != 0) hash ^= WData2.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (PvSn != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(PvSn);
    }
    if (Code != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Code);
    }
    if (Num != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Num);
    }
    if (STime != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(STime);
    }
    if (ETime != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(ETime);
    }
    if (WData1 != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(WData1);
    }
    if (WData2 != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(WData2);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (PvSn != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(PvSn);
    }
    if (Code != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Code);
    }
    if (Num != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Num);
    }
    if (STime != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(STime);
    }
    if (ETime != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(ETime);
    }
    if (WData1 != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(WData1);
    }
    if (WData2 != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(WData2);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (PvSn != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(PvSn);
    }
    if (Code != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
    }
    if (Num != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
    }
    if (STime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(STime);
    }
    if (ETime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ETime);
    }
    if (WData1 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(WData1);
    }
    if (WData2 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(WData2);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(WarnMO other) {
    if (other == null) {
      return;
    }
    if (other.PvSn != 0L) {
      PvSn = other.PvSn;
    }
    if (other.Code != 0) {
      Code = other.Code;
    }
    if (other.Num != 0) {
      Num = other.Num;
    }
    if (other.STime != 0) {
      STime = other.STime;
    }
    if (other.ETime != 0) {
      ETime = other.ETime;
    }
    if (other.WData1 != 0) {
      WData1 = other.WData1;
    }
    if (other.WData2 != 0) {
      WData2 = other.WData2;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PvSn = input.ReadInt64();
          break;
        }
        case 16: {
          Code = input.ReadInt32();
          break;
        }
        case 24: {
          Num = input.ReadInt32();
          break;
        }
        case 32: {
          STime = input.ReadInt32();
          break;
        }
        case 40: {
          ETime = input.ReadInt32();
          break;
        }
        case 48: {
          WData1 = input.ReadInt32();
          break;
        }
        case 56: {
          WData2 = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          PvSn = input.ReadInt64();
          break;
        }
        case 16: {
          Code = input.ReadInt32();
          break;
        }
        case 24: {
          Num = input.ReadInt32();
          break;
        }
        case 32: {
          STime = input.ReadInt32();
          break;
        }
        case 40: {
          ETime = input.ReadInt32();
          break;
        }
        case 48: {
          WData1 = input.ReadInt32();
          break;
        }
        case 56: {
          WData2 = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class WarnResDTO : pb::IMessage<WarnResDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WarnResDTO> _parser = new pb::MessageParser<WarnResDTO>(() => new WarnResDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<WarnResDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WarnDataReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WarnResDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WarnResDTO(WarnResDTO other) : this() {
    ymdHms_ = other.ymdHms_;
    packageNow_ = other.packageNow_;
    errCode_ = other.errCode_;
    offset_ = other.offset_;
    time_ = other.time_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WarnResDTO Clone() {
    return new WarnResDTO(this);
  }

  /// <summary>Field number for the "ymd_hms" field.</summary>
  public const int YmdHmsFieldNumber = 1;
  private string ymdHms_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string YmdHms {
    get { return ymdHms_; }
    set {
      ymdHms_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "package_now" field.</summary>
  public const int PackageNowFieldNumber = 2;
  private int packageNow_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PackageNow {
    get { return packageNow_; }
    set {
      packageNow_ = value;
    }
  }

  /// <summary>Field number for the "err_code" field.</summary>
  public const int ErrCodeFieldNumber = 3;
  private int errCode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ErrCode {
    get { return errCode_; }
    set {
      errCode_ = value;
    }
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 4;
  private int offset_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Offset {
    get { return offset_; }
    set {
      offset_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 5;
  private int time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as WarnResDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(WarnResDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (YmdHms != other.YmdHms) return false;
    if (PackageNow != other.PackageNow) return false;
    if (ErrCode != other.ErrCode) return false;
    if (Offset != other.Offset) return false;
    if (Time != other.Time) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (YmdHms.Length != 0) hash ^= YmdHms.GetHashCode();
    if (PackageNow != 0) hash ^= PackageNow.GetHashCode();
    if (ErrCode != 0) hash ^= ErrCode.GetHashCode();
    if (Offset != 0) hash ^= Offset.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (YmdHms.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(YmdHms);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PackageNow);
    }
    if (ErrCode != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ErrCode);
    }
    if (Offset != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (YmdHms.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(YmdHms);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PackageNow);
    }
    if (ErrCode != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ErrCode);
    }
    if (Offset != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (YmdHms.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(YmdHms);
    }
    if (PackageNow != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PackageNow);
    }
    if (ErrCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrCode);
    }
    if (Offset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(WarnResDTO other) {
    if (other == null) {
      return;
    }
    if (other.YmdHms.Length != 0) {
      YmdHms = other.YmdHms;
    }
    if (other.PackageNow != 0) {
      PackageNow = other.PackageNow;
    }
    if (other.ErrCode != 0) {
      ErrCode = other.ErrCode;
    }
    if (other.Offset != 0) {
      Offset = other.Offset;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          YmdHms = input.ReadString();
          break;
        }
        case 16: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 24: {
          ErrCode = input.ReadInt32();
          break;
        }
        case 32: {
          Offset = input.ReadInt32();
          break;
        }
        case 40: {
          Time = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          YmdHms = input.ReadString();
          break;
        }
        case 16: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 24: {
          ErrCode = input.ReadInt32();
          break;
        }
        case 32: {
          Offset = input.ReadInt32();
          break;
        }
        case 40: {
          Time = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class WaveReqDTO : pb::IMessage<WaveReqDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WaveReqDTO> _parser = new pb::MessageParser<WaveReqDTO>(() => new WaveReqDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<WaveReqDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WarnDataReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WaveReqDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WaveReqDTO(WaveReqDTO other) : this() {
    dtuSn_ = other.dtuSn_;
    time_ = other.time_;
    packageNub_ = other.packageNub_;
    packageNow_ = other.packageNow_;
    pvSn_ = other.pvSn_;
    code_ = other.code_;
    num_ = other.num_;
    warnTime_ = other.warnTime_;
    dataLen_ = other.dataLen_;
    pos_ = other.pos_;
    warnData_ = other.warnData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WaveReqDTO Clone() {
    return new WaveReqDTO(this);
  }

  /// <summary>Field number for the "dtu_sn" field.</summary>
  public const int DtuSnFieldNumber = 1;
  private string dtuSn_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DtuSn {
    get { return dtuSn_; }
    set {
      dtuSn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private int time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  /// <summary>Field number for the "package_nub" field.</summary>
  public const int PackageNubFieldNumber = 3;
  private int packageNub_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PackageNub {
    get { return packageNub_; }
    set {
      packageNub_ = value;
    }
  }

  /// <summary>Field number for the "package_now" field.</summary>
  public const int PackageNowFieldNumber = 4;
  private int packageNow_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PackageNow {
    get { return packageNow_; }
    set {
      packageNow_ = value;
    }
  }

  /// <summary>Field number for the "pv_sn" field.</summary>
  public const int PvSnFieldNumber = 5;
  private long pvSn_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long PvSn {
    get { return pvSn_; }
    set {
      pvSn_ = value;
    }
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 6;
  private int code_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Code {
    get { return code_; }
    set {
      code_ = value;
    }
  }

  /// <summary>Field number for the "num" field.</summary>
  public const int NumFieldNumber = 7;
  private int num_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Num {
    get { return num_; }
    set {
      num_ = value;
    }
  }

  /// <summary>Field number for the "warn_time" field.</summary>
  public const int WarnTimeFieldNumber = 8;
  private int warnTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WarnTime {
    get { return warnTime_; }
    set {
      warnTime_ = value;
    }
  }

  /// <summary>Field number for the "data_len" field.</summary>
  public const int DataLenFieldNumber = 9;
  private int dataLen_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int DataLen {
    get { return dataLen_; }
    set {
      dataLen_ = value;
    }
  }

  /// <summary>Field number for the "pos" field.</summary>
  public const int PosFieldNumber = 10;
  private int pos_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Pos {
    get { return pos_; }
    set {
      pos_ = value;
    }
  }

  /// <summary>Field number for the "warn_data" field.</summary>
  public const int WarnDataFieldNumber = 11;
  private string warnData_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string WarnData {
    get { return warnData_; }
    set {
      warnData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as WaveReqDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(WaveReqDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (DtuSn != other.DtuSn) return false;
    if (Time != other.Time) return false;
    if (PackageNub != other.PackageNub) return false;
    if (PackageNow != other.PackageNow) return false;
    if (PvSn != other.PvSn) return false;
    if (Code != other.Code) return false;
    if (Num != other.Num) return false;
    if (WarnTime != other.WarnTime) return false;
    if (DataLen != other.DataLen) return false;
    if (Pos != other.Pos) return false;
    if (WarnData != other.WarnData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (DtuSn.Length != 0) hash ^= DtuSn.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (PackageNub != 0) hash ^= PackageNub.GetHashCode();
    if (PackageNow != 0) hash ^= PackageNow.GetHashCode();
    if (PvSn != 0L) hash ^= PvSn.GetHashCode();
    if (Code != 0) hash ^= Code.GetHashCode();
    if (Num != 0) hash ^= Num.GetHashCode();
    if (WarnTime != 0) hash ^= WarnTime.GetHashCode();
    if (DataLen != 0) hash ^= DataLen.GetHashCode();
    if (Pos != 0) hash ^= Pos.GetHashCode();
    if (WarnData.Length != 0) hash ^= WarnData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (DtuSn.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DtuSn);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Time);
    }
    if (PackageNub != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PackageNub);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(PackageNow);
    }
    if (PvSn != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(PvSn);
    }
    if (Code != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Code);
    }
    if (Num != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Num);
    }
    if (WarnTime != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(WarnTime);
    }
    if (DataLen != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(DataLen);
    }
    if (Pos != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(Pos);
    }
    if (WarnData.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(WarnData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (DtuSn.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DtuSn);
    }
    if (Time != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Time);
    }
    if (PackageNub != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PackageNub);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(PackageNow);
    }
    if (PvSn != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(PvSn);
    }
    if (Code != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Code);
    }
    if (Num != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Num);
    }
    if (WarnTime != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(WarnTime);
    }
    if (DataLen != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(DataLen);
    }
    if (Pos != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(Pos);
    }
    if (WarnData.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(WarnData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (DtuSn.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DtuSn);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
    }
    if (PackageNub != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PackageNub);
    }
    if (PackageNow != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PackageNow);
    }
    if (PvSn != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(PvSn);
    }
    if (Code != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
    }
    if (Num != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
    }
    if (WarnTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(WarnTime);
    }
    if (DataLen != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(DataLen);
    }
    if (Pos != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pos);
    }
    if (WarnData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(WarnData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(WaveReqDTO other) {
    if (other == null) {
      return;
    }
    if (other.DtuSn.Length != 0) {
      DtuSn = other.DtuSn;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    if (other.PackageNub != 0) {
      PackageNub = other.PackageNub;
    }
    if (other.PackageNow != 0) {
      PackageNow = other.PackageNow;
    }
    if (other.PvSn != 0L) {
      PvSn = other.PvSn;
    }
    if (other.Code != 0) {
      Code = other.Code;
    }
    if (other.Num != 0) {
      Num = other.Num;
    }
    if (other.WarnTime != 0) {
      WarnTime = other.WarnTime;
    }
    if (other.DataLen != 0) {
      DataLen = other.DataLen;
    }
    if (other.Pos != 0) {
      Pos = other.Pos;
    }
    if (other.WarnData.Length != 0) {
      WarnData = other.WarnData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          DtuSn = input.ReadString();
          break;
        }
        case 16: {
          Time = input.ReadInt32();
          break;
        }
        case 24: {
          PackageNub = input.ReadInt32();
          break;
        }
        case 32: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 40: {
          PvSn = input.ReadInt64();
          break;
        }
        case 48: {
          Code = input.ReadInt32();
          break;
        }
        case 56: {
          Num = input.ReadInt32();
          break;
        }
        case 64: {
          WarnTime = input.ReadInt32();
          break;
        }
        case 72: {
          DataLen = input.ReadInt32();
          break;
        }
        case 80: {
          Pos = input.ReadInt32();
          break;
        }
        case 90: {
          WarnData = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          DtuSn = input.ReadString();
          break;
        }
        case 16: {
          Time = input.ReadInt32();
          break;
        }
        case 24: {
          PackageNub = input.ReadInt32();
          break;
        }
        case 32: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 40: {
          PvSn = input.ReadInt64();
          break;
        }
        case 48: {
          Code = input.ReadInt32();
          break;
        }
        case 56: {
          Num = input.ReadInt32();
          break;
        }
        case 64: {
          WarnTime = input.ReadInt32();
          break;
        }
        case 72: {
          DataLen = input.ReadInt32();
          break;
        }
        case 80: {
          Pos = input.ReadInt32();
          break;
        }
        case 90: {
          WarnData = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class WaveResDTO : pb::IMessage<WaveResDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WaveResDTO> _parser = new pb::MessageParser<WaveResDTO>(() => new WaveResDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<WaveResDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WarnDataReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WaveResDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WaveResDTO(WaveResDTO other) : this() {
    ymdHms_ = other.ymdHms_;
    packageNow_ = other.packageNow_;
    errCode_ = other.errCode_;
    offset_ = other.offset_;
    time_ = other.time_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WaveResDTO Clone() {
    return new WaveResDTO(this);
  }

  /// <summary>Field number for the "ymd_hms" field.</summary>
  public const int YmdHmsFieldNumber = 1;
  private string ymdHms_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string YmdHms {
    get { return ymdHms_; }
    set {
      ymdHms_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "package_now" field.</summary>
  public const int PackageNowFieldNumber = 2;
  private int packageNow_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PackageNow {
    get { return packageNow_; }
    set {
      packageNow_ = value;
    }
  }

  /// <summary>Field number for the "err_code" field.</summary>
  public const int ErrCodeFieldNumber = 3;
  private int errCode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ErrCode {
    get { return errCode_; }
    set {
      errCode_ = value;
    }
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 4;
  private int offset_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Offset {
    get { return offset_; }
    set {
      offset_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 5;
  private int time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as WaveResDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(WaveResDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (YmdHms != other.YmdHms) return false;
    if (PackageNow != other.PackageNow) return false;
    if (ErrCode != other.ErrCode) return false;
    if (Offset != other.Offset) return false;
    if (Time != other.Time) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (YmdHms.Length != 0) hash ^= YmdHms.GetHashCode();
    if (PackageNow != 0) hash ^= PackageNow.GetHashCode();
    if (ErrCode != 0) hash ^= ErrCode.GetHashCode();
    if (Offset != 0) hash ^= Offset.GetHashCode();
    if (Time != 0) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (YmdHms.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(YmdHms);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PackageNow);
    }
    if (ErrCode != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ErrCode);
    }
    if (Offset != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (YmdHms.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(YmdHms);
    }
    if (PackageNow != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PackageNow);
    }
    if (ErrCode != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ErrCode);
    }
    if (Offset != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Offset);
    }
    if (Time != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (YmdHms.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(YmdHms);
    }
    if (PackageNow != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PackageNow);
    }
    if (ErrCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrCode);
    }
    if (Offset != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
    }
    if (Time != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(WaveResDTO other) {
    if (other == null) {
      return;
    }
    if (other.YmdHms.Length != 0) {
      YmdHms = other.YmdHms;
    }
    if (other.PackageNow != 0) {
      PackageNow = other.PackageNow;
    }
    if (other.ErrCode != 0) {
      ErrCode = other.ErrCode;
    }
    if (other.Offset != 0) {
      Offset = other.Offset;
    }
    if (other.Time != 0) {
      Time = other.Time;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          YmdHms = input.ReadString();
          break;
        }
        case 16: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 24: {
          ErrCode = input.ReadInt32();
          break;
        }
        case 32: {
          Offset = input.ReadInt32();
          break;
        }
        case 40: {
          Time = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          YmdHms = input.ReadString();
          break;
        }
        case 16: {
          PackageNow = input.ReadInt32();
          break;
        }
        case 24: {
          ErrCode = input.ReadInt32();
          break;
        }
        case 32: {
          Offset = input.ReadInt32();
          break;
        }
        case 40: {
          Time = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
